### ISSUE TITLE
Double Quotes vs Single Quotes

### ISSUE THREAD

**Issue by IvanLieckens** [mikeedwards83/Glass.Mapper#101]
When using the BeginRenderLink in GlassMapper Sitecore MVC I ran into the issue where I had added an extra attribute onto my link for rendering the GA tracking: new { onclick = "ga('send', 'event', 'category', 'action', 'label');" }

This mangled the HTML output however due to the single quotes being used by the GlassMapper HtmlHelper. All our HTML is using double quotes and our js is using single quotes. I'm aware this is a flavor issue (and I fixed it for now by using double quotes in the attribute) but would it be possible to turn this into an option what quoting you prefer? It'd help my OCD getting all the quotes to match ;-)

**Comment by mikeedwards83** [comment]
Ivan, please see the latest nightly build, you will see that I have added a GlassHtml.QuotationMark as an option:

https://github.com/mikeedwards83/Glass.Mapper/blob/develop/Source/Glass.Mapper.Sc/GlassHtml.cs#L69

**Comment by IvanLieckens** [comment]
Thanks for the effort Mike!

**Comment by mikeedwards83** [comment]
No problem, I have written a unit test for it but let me know if you find
any issues.

This is currently only available on the feed from the Glass build server.

**Comment by mikeedwards83** [comment]
Released

**Comment by SNiels** [comment]
Is there a specific reason that single quotes are being used? I think double quotes should be the default, but if you want single quotes you can override it.
I understand both double quotes as single quotes are valid, but it seems that double quotes is an unspoken standard and single quotes are only used in specific cases where you want to use double quotes as the value of your attribute.
