### ISSUE TITLE
Glass Model not populated in GlassView after upgrade

### ISSUE THREAD

**Issue by tomunderhill** [mikeedwards83/Glass.Mapper#102]
Previously we had a working solution using the following Glass packages:

    Glass.Mapper 3.0.10.23
    Glass.Mapper.Sc 3.2.0.34
    Glass.Mapper.Sc.CastleWindsor 3.2.0.17
    Glass.Mapper.Sc.Mvc-5 3.2.0.1

I've just updated to:

    Glass.Mapper 3.0.14.26
    Glass.Mapper.Sc 3.2.3.46
    Glass.Mapper.Sc.CastleWindsor 3.2.0.17
    Glass.Mapper.Sc.Mvc-5 3.3.0.44

Now I have an issue with certain Glass models not populating in GlassViews.

The following call in the controller returns the correctly populated model:

     sitecoreContext.GetCurrentItem<CourseBaseModel >

But a view set up like this:

    @inherits Glass.Mapper.Sc.Web.Mvc.GlassView<CourseBaseModel>

returns null for all properties.

Model is as follows:

    [SitecoreType(AutoMap = true, TemplateId = ContentReferences.Course.CourseBaseTemplateId)]
    public class CourseBaseModel : PageModel, CourseAvailabilityEnabledModel, ICourseSettingsModel
    {
        
        [IndexField("alphapagetitlesort")]
        public string PageTitleSort { get; set; }

        [IndexField("Introduction")]
        public virtual string Introduction { get; set; }

        [IndexField("Overview")]
        public virtual string Overview { get; set; }

        [IndexField("Careers")]
        public virtual string Careers { get; set; }

        [SitecoreQuery(ContentReferences.SupportingItemPath + "/Settings")]
        public virtual GlobalSettingsModel GlobalSettings { get; set; }

        public string OverviewWithDefaultShowHideText
        {
            get
            {
                return this.Overview.Replace("{LinkText}", this.GlobalSettings.ShowHideLinkText);
            }
        }
        
        public virtual string WhereYouStudy { get; set; }
        
        public virtual string FeesAndFunding { get; set; }

        [IgnoreIndexField]
        public virtual LookupReferenceModel LevelOfStudy { get; set; }

        [IgnoreIndexField]
        public virtual FacultyModel Faculty { get; set; }

        [IgnoreIndexField]
        public virtual DepartmentModel Department { get; set; }

        [IgnoreIndexField]
        [SitecoreField(Setting = SitecoreFieldSettings.InferType)]
        public virtual IEnumerable<LookupReferenceModel> ModeOfStudy { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<LookupReferenceModel> Availability { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<LookupReferenceModel> Categories { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<LookupReferenceModel> Duration { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<LookupReferenceModel> StartDate { get; set; }
        
        public virtual string SitsCode { get; set; }
        
        public virtual string TeachingTimes { get; set; }

        //this field has display title Campus in Sitecore
        [IgnoreIndexField]
        public virtual IEnumerable<CampusModel> Location { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<Guid> LocationOverride { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<RichTextModel> ReducedFeesInfo { get; set; }

        [IgnoreIndexField]
        public virtual TripleContentRowModel FeePaymentInfo { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<FeeBandModel> FeeBands { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<RichTextModel> FundingInfoText { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<RichTextModel> InternationalFundingInfo { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<RichTextModel> EntryRequirementInfo { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<RichTextModel> HighlightedEntryInfo { get; set; }

        [IgnoreIndexField]
        public virtual IEnumerable<CallToActionModel> CallToAction { get; set; }

        [IgnoreIndexField]
        [SitecoreField(Setting = SitecoreFieldSettings.InferType)]
        public virtual IEnumerable<ItemModel> ModuleTitlesAndModules { get; set; }

        [IgnoreIndexField]
        [SitecoreQuery(ContentReferences.Course.SupportingPath)]
        public virtual CourseSettingsModel CourseSettings { get; set; }

        private IList<CallToActionModel> callToActionList;
        public virtual IList<CallToActionModel> CallToActionList
        {
            get
            {
                if (this.callToActionList == null)
                    this.callToActionList = this.CallToAction.ToList();
                return this.callToActionList;
            }
        }

**Comment by mikeedwards83** [comment]
Hi Tom

Do you get kind of error? Does it give you a stacktrace? 

Mike

**Comment by tomunderhill** [comment]
Hi Mike,

It didn't, but we've resolved some issues with conflicted versions of the Sitecore dlls in our solution and the problem has gone away - so guess it wasn't a Glass problem.

Cheers,
Tom
