### ISSUE TITLE
MediaPath field has been removed from 7.1 and type link break DI container

### ISSUE THREAD

**Issue by mmulvogue-work** [mikeedwards83/Glass.Mapper#105]
When structuremap runs a type scan on Glass.Mapper.Sc with Sitecore 7.1 version of Sitecore.Kernel. A "Could not load type 'Sitecore.Data.Fields.MediaPath' from assembly 'Sitecore.Kernel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'." error occurs because Sitecore.Data.Fields.MediaPath was marked as obsolete in 7.0 and has been removed from 7.1.

**Comment by tomunderhill** [comment]
This causes CodeAnalysis warnings, which fail a solution build in certain circumstances

**Comment by dthunziker** [comment]
I am getting this error when instantiating my Castle Windsor IoC container.

**Comment by mikeedwards83** [comment]
I have searched the entire Glass code base and I can't find a reference to this.

**Comment by mikeedwards83** [comment]
I have removed the reference to MediaPath.

**Comment by mikeedwards83** [comment]
Released
