### ISSUE TITLE
Feature Request: Automatically add querystring to url property for internal links

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#106]
Hi Mike,

for `Link` fields, I use the `Url` property to get the url of a specific link. For external links this get's me the correct url with all the query string parameters. For internal links it only adds the link to the specific item. The querystring parameters (if available) are only stored within the `Query` property of the `Link`. This means, for every `Link` property I have to check if there is a querystring available and add this manually.

In a current project we have created an extension method for this:

    public static string GetUrl(this Link link)
    {
        if (link == null) return null;

        if (link.Type == LinkType.Internal)
        {
            if (!string.IsNullOrWhiteSpace(link.Query))
            {
                return string.Format("{0}?{1}", link.Url, link.Query);
            }
        }

        return link.Url;
    }

IMO it would make sense that the `Url` property of each link has the "final" url I could call (i.e. adding the query to the url here: https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/DataMappers/SitecoreFieldLinkMapper.cs#L127).

The disadvantage of this is, that it's then no more a 1:1 mapping between the model class in the code and the Sitecore field's data.

What do you think? Does it make sense to always add the query to the url?

Thanks and greets,
Kevin

**Comment by mikeedwards83** [comment]
Kevin

I wouldn't want to change how the URL field works, but I could add a GetFullUrl method to the Link class with the logic above.

Mike

**Comment by aquasonic** [comment]
Would be fine for me.

**Comment by mikeedwards83** [comment]
Kevin

Just realised that we had the BuildUrl method on the Link class. Is that sufficient? 

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/Fields/Link.cs#L88

Mike

**Comment by aquasonic** [comment]
Hi Mike,

oh yes, didn't see this. Yes this is enough I think. Thanks a lot :)

Greets,
Kevin
