### ISSUE TITLE
Inexplicable nullreference exception: Castle Proxy?

### ISSUE THREAD

**Issue by IvanLieckens** [mikeedwards83/Glass.Mapper#107]
In an MVC view I'm receiving a nullreference exception after checking all references for NULL and when calling said methods and properties in debug mode there's not a single null reference in sight. I have a strong suspicion that the castle proxies are responsible but can't find an immediate explanation as to why this exception occurs.

My view is `@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<Product_Category>` I'm using generated template classes using TDS code generation. In the TT file I slightly expanded the IGlassBase and GlassBase with the following:

    public partial interface IGlassBase
    {
        [SitecoreId]
        Guid Id { get; }

        [SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string DisplayName { get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }

        [SitecoreInfo(SitecoreInfoType.Url, UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)]
        string AbsoluteUrl { get; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IGlassBase> Children { get; }

        [SitecoreParent(InferType = true)]
        IGlassBase Parent { get; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        string Path { get; }
    }

    public abstract partial class GlassBase : IGlassBase
    {    
        [SitecoreId]
        public virtual Guid Id { get; private set;}

        [SitecoreInfo(SitecoreInfoType.Name)]
        public virtual string Name { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        public virtual string DisplayName { get; set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url, UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)]
        public virtual string AbsoluteUrl { get; private set; }

        [SitecoreChildren(InferType = true)]
        public virtual IEnumerable<IGlassBase> Children { get; set; }

        [SitecoreParent(InferType = true)]
        public virtual IGlassBase Parent { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateId {get; set; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        public virtual string Path { get; set; }
    }

Additionally I extended the Product_Category with a partial containing:

        private List<IProduct> _products; 

        public IEnumerable<Product_Page> ProductPages
        {
            get { return ProtectedProductPages ?? new Product_Page[0]; }
        }

        public List<IProduct> Products
        {
            get
            {
                return _products ?? (_products = GetProducts());
            }
        }
        
        [SitecoreChildren]
        protected virtual IEnumerable<Product_Page> ProtectedProductPages { get; set; }

        private List<IProduct> GetProducts()
        {
            List<IProduct> result = new List<IProduct>();
            if (Children != null && Children.Any())
            {
                foreach (IGlassBase child in Children)
                {
                    Template template = TemplateManager.GetTemplate(new ID(child.TemplateId), Sitecore.Context.Database);
                    if (template.DescendsFrom(IProduct_PageConstants.TemplateId))
                    {
                        result.Add((IProduct)child);
                    }
                }
            }

            return result;
        }

I then looped through this in my view in the following way:

                    @foreach (IProduct product in Model.Products.Where(p => p.Children != null && (p.Children.FirstOrDefault() as IProduct_Variant) != null))
                    {
                        IProduct_Variant firstVariant = (IProduct_Variant)product.Children.First();

So as you can see I'm covering my bases with nullchecks trying to figure out why this line `IProduct_Variant firstVariant = (IProduct_Variant)product.Children.First()` throws a nullreference exception while neither product, nor its children, nor the casted result has any null reference...

**Comment by mikeedwards83** [comment]
Can you add the stack trace as well?

**Comment by IvanLieckens** [comment]
System.InvalidOperationException: Error while rendering view: '/Views/ProductCategory/ProductGrid.cshtml' (model: 'MyAssembly.SC.Product_Category, MyAssembly.SC').
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ASP._Page_Views_ProductCategory_ProductGrid_cshtml.Execute() in c:\Sites\MyAssembly\Website\Views\ProductCategory\ProductGrid.cshtml:line 14
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
   --- End of inner exception stack trace ---
   at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
   at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args)
   at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args)
   at MyAssembly.SC.Pipelines.Mvc.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) in d:\Projects\MyAssembly.Sitecore\Development\MAIN\MyAssembly\MyAssembly.SC\Pipelines\Mvc\RenderRendering\ExecuteRenderer.cs:line 54

line 14 is the illustrious line I referred to in the first part. The renderer is the one you can find at http://www.sitecore.net/Learn/Blogs/Technical-Blogs/John-West-Sitecore-Blog/Posts/2012/09/Handling-Rendering-Exceptions-in-MVC-Solutions-with-the-Sitecore-ASPNET-CMS.aspx in case this matters.

**Comment by IvanLieckens** [comment]
Mike I found that this issue occurs when some parents do not have a version. I "resolved" the issue temporarily in our project by using Lazy = true on the [SitecoreParent] relation.

**Comment by mikeedwards83** [comment]
Thanks for the info. I will see if I can write a unit test for this scenario.

**Comment by mikeedwards83** [comment]
Ivan

From my unit test things are behaving as expected:

https://github.com/mikeedwards83/Glass.Mapper/blob/develop/Tests/Integration%20Tests/Sitecore/Glass.Mapper.Sc.Integration/DataMappers/SitecoreParentMapperFixture.cs#L132

If an item does not have a version Glass by default returns null therefore you need to do a null check.

Glass does have a version check disabler class that you can wrap calls into force it not to do the check:

using(new VersionCountDisabler()){
  //your logic here
}

However it might also be an idea to have this on the SitecoreParent and SitecoreChildren configurations as well.

**Comment by mikeedwards83** [comment]
Can this issue be closed?

**Comment by IvanLieckens** [comment]
Hi Mike,

Yes I believe it can. I havent detected it anymore in the past month.

Sincerely,
Ivan Lieckens

Sent from my iPhone, please excuse the brevity of the message.
