### ISSUE TITLE
Page Editor crashes, when editor has no access to linked on page item.

### ISSUE THREAD

**Issue by VladimirZaverugo** [mikeedwards83/Glass.Mapper#108]
GlassMapper is used on Sitecore project. Project contains several websites. Each website with its own tree and logic.
There are multiple security roles set on the project. Some roles have access to all trees, some only to 1-2 trees.
Site can contain link to another website. 
When user with limited access (has access to only 1 website) opens Page Editor on page, which contains link to another website (that he has no access), Page Editor crashes. Field for link – General link.

Stack Trace:
 
[ArgumentNullException: Value cannot be null.
Parameter name: item]
   Sitecore.Data.Managers.TemplateProvider.GetTemplate(Item item) +293
   Dorel.SitecoreControls.LinkProvider.LinkProviderEx.GetItemUrl(Item item, UrlOptions options) in d:\Data\Teamcity.BuildAgent4\work\ea28d276798ba625\Sources\Website\SitecoreControls\LinkProvider\LinkProviderEx.cs:36
   Dorel.Handlers.GlassMapper.LinkDataHandler.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) in d:\Data\Teamcity.BuildAgent4\work\ea28d276798ba625\Sources\Website\Handlers\GlassMapper\LinkDataHandler.cs:29
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext) +352
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +99
 
[MapperException: Failed to map to property 'Link' on type 'Dorel.Entities.McBbc3.Entities.TitledImageWithLink']
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +627
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +164
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +131
 
[MapperException: Failed to map property Link on Dorel.Entities.McBbc3.Entities.TitledImageWithLink]
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +545
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +189
 
[MapperException: Failed to map properties on /sitecore/content/MCBBC/BebeConfort/BBC_Intl/Datasources/General/Titled Images With Links/Top Articles Carousel Item.]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +394
   Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(ObjectConstructionArgs args) +968
   Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(ObjectConstructionArgs args) +588
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +197
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
  Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args) +81
   Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) +646
   Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) +754
   Glass.Mapper.Sc.SitecoreService.CreateType(Item item, Boolean isLazy, Boolean inferType) +215
   Glass.Mapper.Sc.Web.Ui.GlassUserControl`1.GetModel() +282
   Glass.Mapper.Sc.Web.Ui.GlassUserControl`1.OnLoad(EventArgs e) +59
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Control.LoadRecursive() +190
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

**Comment by mikeedwards83** [comment]
Hi

I am closing this, the Glass code has checks to eunsure that if the target item is null that the code does not break and an empty URL is returned. Looking at the stack this is a custom handler.

Mike
