### ISSUE TITLE
New with Search fields

### ISSUE THREAD

**Issue by ScottReed** [mikeedwards83/Glass.Mapper#109]
We are using the latest Nuget Glass.Mapper.3.0.14.27 and Glass.Mapper.Sc.3.2.3.49. There are new fields related to Sitecore search and the buckets

-Multilist with search
-General link with search

We aren't using code first just reading the value back and when trying to read a field of General lnik with search out we are getting back NULL. Is there any quick fix other than extending the types?

Nice work, I work with Tom Dudfield at Redweb we all love Glass :-)

Thanks,
Scott

**Comment by mikeedwards83** [comment]
Hi

Are you using the Map method? Could you send me an example of the model and code you are using to do the search?

Thanks

Mike

**Comment by mikeedwards83** [comment]
Closing due to age of ticket please reopen if required.
