### ISSUE TITLE
[SitecoreInfo(SitecoreInfoType.MediaUrl, UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)] does not work

### ISSUE THREAD

**Issue by IvanLieckens** [mikeedwards83/Glass.Mapper#111]
When using the following attribute:
[SitecoreInfo(SitecoreInfoType.MediaUrl, UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)]

The resulting URL is not absolute.

**Comment by sarcjack** [comment]
+1 on this.

**Comment by iss0** [comment]
+1 from me. This is a real problem using EXM. The workarround ain't pretty.

**Comment by mikeedwards83** [comment]
Closing due to age of ticket please reopen if required.

**Comment by kevin5464** [comment]
Age of ticket = never resolved? This is a big problem with FXM because images simply don't work.
