### ISSUE TITLE
Query not appended to Link Url

### ISSUE THREAD

**Issue by dthunziker** [mikeedwards83/Glass.Mapper#116]
In the latest version of Glass, I am not seeing the **Query** appended to the URL for the Sitecore **General Link** field when inserting an **Internal Link** (see example image below). All the other properties are used except the query.

As a workaround, I have tried an extension method to the Link class, however, this does not work with BeginRenderLink / RenderLink in Page Editor, as the lambda expression must evaluate to a member. I am considering a custom Data Mapper, however, I cannot figure out how to override the default LinkField mapper with my custom implementation.

Also, could this be related to: Issue #99?

![links](https://cloud.githubusercontent.com/assets/1148916/6852410/b3ff5b22-d3a1-11e4-8077-de0f2fafc052.PNG)

Sitecore v7.2 Update-3

**Comment by mikeedwards83** [comment]
This looks like a Sitecore interface bug relating to the new design. When the value is save it URL escapes the QueryString value: 

![image](https://cloud.githubusercontent.com/assets/123856/6864217/31b989e8-d456-11e4-991d-97c21bd5df18.png)

This doesn't happen in the original UI. The Glass code isn't expecting an escaped QueryString.

You can also see that if you keep opening and closing the Insert window it keeps escaping the % symbol as well:

![image](https://cloud.githubusercontent.com/assets/123856/6864244/84c2ab6a-d456-11e4-8598-20dc77893bcb.png)

Even if you wrote a custom data mapper to decode the encode string you would still get an incorrect rendering because of the above problem.

I think this issue needs to be raised with Sitecore.

**Comment by mikeedwards83** [comment]
I have just tested the output of the field using the standard Sitecore API:

    <sc:Link runat="server" Field="Link"></sc:Link>

It outputs the following:

    <a href="/sitecore/media library.aspx?test%3Dhello">Media Library</a>

This is incorrect so I am now sure this should be fixed by SC.

**Comment by dthunziker** [comment]
Sitecore was able to reproduce and provided me with a support patch that replaces the General Link field with a new class/assembly. Below is an example of the before/after RAW values for an internal link field:

Before

    <link text="" linktype="internal" class="" title=""  querystring="foo%3Dbar" id="{CC7C5D08-EEDA-4780-B3FB-9BB20C430068}" />

After
    
     <link text="" linktype="internal" class="" title=""  querystring="foo=bar" id="{CC7C5D08-EEDA-4780-B3FB-9BB20C430068}" />

This results in a valid value in my Glass.Mapper.Sc.Fields.Link "Query" property, however, the query value is still not being appended to the Url property. Any ideas?

**Comment by mikeedwards83** [comment]
Can you send me the assembly?

**Comment by dthunziker** [comment]
Sent to hello at glass dot lu

**Comment by dthunziker** [comment]
The email was rejected, so here it is: https://www.dropbox.com/sh/2suz5mm5m3shxm1/AABO1aPzBbCKjSYksS8kVaQma?dl=0

**Comment by mikeedwards83** [comment]
Sorry for the slow reply. With Sitecore's update the field works find on my solution.

**Comment by mikeedwards83** [comment]
Are you still experiencing this problem?

**Comment by dannyc02** [comment]
Hi Mike.

I'm experiencing the same issue.  The patch doesn't work for me, so I'll follow up with Sitecore separately to sort the UI issue.

I still can't get the query string appended from the internal link though.
I've tried both versions of the query string (as per above):

```
<link text="" linktype="internal" class="" title=""  querystring="foo%3Dbar" id="{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}" />
```
I've also tried decoding the query string while in raw view mode, as such:

```
<link text="" linktype="internal" class="" title=""  querystring="foo=bar" id="{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}" />
```

Both of these map to the query property of the link (exactly as they appear above, ***foo%3Dbar*** or ***foo=bar***), but neither is appended to the URL property of the link.

**Comment by mikeedwards83** [comment]
Hi @dannyc02 

Sorry is this still an issue?

Mike

**Comment by zhane** [comment]
Hi @mikeedwards83 - yes I'm still having this issue.

**Comment by Kasaku** [comment]
@dthunziker, are you able to supply the config / db change that is required to apply alongside the DLL?

**Comment by mikeedwards83** [comment]
I have written a unit test and still can't replicate this issue:

https://github.com/mikeedwards83/Glass.Mapper/commit/c9ad852d22fffd3f5553a2cb05d8fb709f1cc550

**Comment by VijayBhaskerM** [comment]
Mike,

I'm experiencing the same issue too.For general link field when trying to insert internal link with querystring, i cant see the querystring values after rendering the link.
Tried with BeginRenderLink and RenderLink , however it works with sc:Link.

Please do let me know if we are missing something.Any help would be greatly appreciated.

Thanks,
Vijay.

**Comment by z00mable** [comment]
@mikeedwards83 Hi Mike. We're experiencing the same issue with the latest release v4.0.10.61.

**Comment by mikeedwards83** [comment]
Closing due to age of ticket please reopen is required.

**Comment by benmccallum** [comment]
I'm having the exact same issues as listed above, both the Sitecore bug (I'm on Sitecore 8.0 Update-3) and the behaviour where I don't get the query on the Url if I access item.MyLinkField.Url.
