### ISSUE TITLE
@Editable caching issue when Model not passed

### ISSUE THREAD

**Issue by smyadam** [mikeedwards83/Glass.Mapper#117]
Hello Mike,

We have noticed that not passing the model in @Editable caches the value.

Example.
@Editable(x => Model.GlassItem.TitleLink)

We cannot add the Model to @Editable because we have to update 600 instances of @Editable code in our code in order to pass the model and the lambda expression.

It would be extremely difficult to change and test all these updates.

Can you please add the feature to disable cache and provide us the code how to do this, so that we can update glass.mapper to the latest version.

Thanks,
Shashi.

**Comment by mikeedwards83** [comment]
Shashi

This has been released as a hotfix, please download version 3.3.1.53. See release notes: http://www.glass.lu/Mapper/Sc/Releases/GlassMapperSc and http://www.glass.lu/Mapper/Sc/Documentation/GlassHtml

Mike

**Comment by smyadam** [comment]
Thanks for clearing this up.
