### ISSUE TITLE
Upgrade to Glass.Mapper V3 - duplicate mappings for properties Error

### ISSUE THREAD

**Issue by smyadam** [mikeedwards83/Glass.Mapper#118]
Hello Mike,

We upgraded glass.mapper from V1 to V3. After the upgrade we are getting the below error. 

You cannot have duplicate mappings for properties. Property Name: DictionaryLabels  Type: IGenericsAccordionModel

We were not getting this error before in V1 and in fact if I rollback the dlls to V1 they work fine.

 I see why this could be happening is because DictionaryLabels  is declared both is base interface and inherited interface with the same name but are of different types in this case but there are instance where they are of same name and same type.

Can you please make this backward compatible or provide a setting which allows for this backward compatibility.

Thanks,
Shashi.

**Comment by smyadam** [comment]
Hello Mike any update on this. We would like to upgrade to V3 but we are unable to upgrade. Due to the above issue.

Thanks,
Shashi.

**Comment by mikeedwards83** [comment]
Hi

In V3 properties must have a unique name per model.

From your description I assume you have an interface setup similar to this:
    
    public interface I1
    {
        string Prop1 { get; set; }
    }

    public interface I2 : I1
    {
        int Prop1 { get; set; }
    }

Although .NET will allow this to happen I don't think this is best practice. If this is the problem then at the moment it isn't likely that I will be adding support for this.

**Comment by smyadam** [comment]
Thanks Mike for the response.

**Comment by mikeedwards83** [comment]
At this time support won't be added.
