### ISSUE TITLE
RenderImage in Edit Mode outputs wrong url for language specific media item

### ISSUE THREAD

**Issue by smyadam** [mikeedwards83/Glass.Mapper#119]
Hello Mike,

     We have notice an issue in RenderImage in Edit Mode. 

This happens if there is language specific media item.(Default En media item works fine).

@RenderImage(Model, x => x.HalfWidthImage,isEditable: true)

The RenderImage outputs URL without the language code (?la=zh). So what is happening is the url is outputted as
http://www.mysite.com/sitecore/shell/-/media/zh/landing-pages/spt_b.gif which is returning a 404. 
 But if you add ?la=zh to the url http://www.mysite.com/sitecore/shell/-/media/zh/landing-pages/spt_b.gif?la=zh it works fine. This happens if there is a language specific media item.

I was looking more into the Glass.mapper code and looks like you use GetMediaUrl to get the URl but if you use the overloaded method and add the Language  options, this will fix the issue.
 
MediaUrlOptions options = new MediaUrlOptions();
options.Language = Context.Language;
img.Src = MediaManager.GetMediaUrl(mediaItem, options);

Let me know if there is any other solution you have for language specific media items.

Thanks,
Shashi.

**Comment by smyadam** [comment]
Hello Mike,  Any update on this.

**Comment by smyadam** [comment]
Hello Mike, Can you please take a look at this and update the code according for media URL.

**Comment by mikeedwards83** [comment]
Hi I will investigate this tomorrow and see what a fix would take. At the moment I can't guarantee anything because we are focused on v4.

**Comment by mikeedwards83** [comment]
Looking at this issue we want to extend support for Media Options, however this will take time and will be released in a future version after V4. 

At the moment you can specify the language as a anonymous attribute on the image:

    @RenderImage(x=>x.Image, new{la=Sitecore.Context.Language.CultureInfo.Name})

**Comment by mikeedwards83** [comment]
We have a fix for this in branch feature/issue133. This will be released soon.

**Comment by mikeedwards83** [comment]
I have pushed a fix to our develop branch. This is available from the nightly build as 4.0.1.27

**Comment by mikeedwards83** [comment]
This has been release in 4.0.1.8, reopen if this is still and issue.
