### ISSUE TITLE
How to retrieve ItemRendering item?

### ISSUE THREAD

**Issue by SanderSchutten** [mikeedwards83/Glass.Mapper#124]
Hi,

I've been working with Glass and Sitecore for a few weeks now, and love the way it helps boosting productivity.

Today i've started using ItemRendering to render child items. In the view i've placed:
@foreach (var articleItem in Model.DataItem.Items)
{
        @Html.Sitecore().ItemRendering(articleItem.Id.ToString());
}

In the controller i've put the following code to get the RendererItem and bind it to the view:
public ActionResult Intro()
{
            var viewModel = new ArticleIntroViewModel(GetRendererItem<Article_Intro>());
            return PartialView("~/Views/Modules/Article/Parts/text/intro.cshtml", viewModel);
}

The implementation of GetRendererItem is:
public virtual T GetRendererItem<T>() where T : class
{
                try
                {
                    return SitecoreContext.GetItem<T>(RenderingContext.Current.Rendering.Item.ID.Guid);                    
                }
                catch (InvalidOperationException)
                {
                    throw;
                }
}

Is there a way to drop the custom implementation of GetRendererItem and use a OOTB Glass implementation?

thanks in advance,
Sander Schutten

**Comment by mikeedwards83** [comment]
Hi Sander

If your controller inherits from GlassController there are several helper methods:

DataSourceItem: 

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Web/Mvc/GlassController.cs#L67

 GetDataSourceItem<T>
https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Web/Mvc/GlassController.cs#L97

I hope this helps.

Mike
