### ISSUE TITLE
RenderignParameters is empty

### ISSUE THREAD

**Issue by red-manul** [mikeedwards83/Glass.Mapper#130]
Method GetRenderingParameters<K>() doesn't seem to work for GlassWebControl. It always gives null. Looks like the problem is in the method 

private string GetRenderingParameters(Control control) 

Since in the case of GlassWebControl control is not a Sublayout it never returns Parameters property.

**Comment by mikeedwards83** [comment]
Hi

We have had a discussion about this but are still trying to decided the best method going forward. The WebControl was written with the intention that it would be used as a control on a sublayout but I am assuming that you are using the WebControl rendering type in Sitecore?

Mike

**Comment by red-manul** [comment]
Hi Mike,
Yes, I'm using it for WebControl rendering. 
Do you think adding one more check would do the job? Something like this:

        private string GetRenderingParameters(Control control)
        {
            if (control == null) return null;

            if (control is Sublayout)
            {
                return ((Sublayout) control).Parameters;
            }

            if (control is WebControl)
            {
                return ((WebControl) control).Parameters;
            }

            return GetRenderingParameters(control.Parent);
        }

in this case it would work both for using in sublayout and in WebControl rendering. 
Or maybe there is another way to use glass.Mapper controls with WebControl rendering Sitecore type?

Cheers,
Elena.

**Comment by mikeedwards83** [comment]
Elena

Looking at the logic it would break for WebControl because the control that
is passed into the method is referenced by "this" which is always a
WebControl.

Mike

**Comment by red-manul** [comment]
You are right, sorry. It should be at least 
if (control is WebControl && ((WebControl) control).Parameters != "")
    return ((WebControl) control).Parameters;

But the whole situation looks weird to me. Shouldn't the WebControl return it's own parameters in the first place instead of its parent's parameters? And if you want to use it in a sublayout and have access to sublayout's parameters it should be pointed explicitly, like GetParentParameters() or GetParentSublayout() or something like that. What do you think? I understand that if you want to keep backward compatibility it might not be an option though.

**Comment by mikeedwards83** [comment]
This was written when most people weren't using webcontrol renderings and I
think that is still the case.

**Comment by mikeedwards83** [comment]
At this time this won't be a change that we will be making and therefore I am closing the issue.
