### ISSUE TITLE
Issues with custom data mappers after upgrade to V4

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#135]
Hi Mark,

I have some issues with my custom data mapper after upgrading to V4. I have my `SitecoreSharedField` as described in my blog post here: http://ctor.io/shared-field-references-in-glass-mapper/

Instead of registering the mapper the old way, I have changed this to the following code:

    public static IDependencyResolver CreateResolver(){
        var config = new Glass.Mapper.Sc.Config();
        var resolver = new DependencyResolver(config);
        resolver.DataMapperFactory.Add(() => new SitecoreSharedFieldTypeMapper());
        return resolver;
    }

Now I receive the following error while loading the page:

> Could not find a data mapper to handle property AbstractPropertyConfiguration Property: Id Type: GlassMapperV4.Models.SampleItem Assembly: GlassMapperV4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

The property `Id` is just the first property on my model. When I move them around, I got the same error on another property.

Is there something we need to adapt also on the custom data mapper (or the attribute/configuration)? Is there something other we need to change or did I configure it wrong? As you can see in the comments of the blog post, there are others having the same issue :)

Thanks for looking into it and cheers,
Kevin

**Comment by Kasaku** [comment]
This would suggest that your `CanHandle` method is returning false (or never being called). Have you debugged that method during execution to ensure it is being called (which will show that the DataMapperFactory is fine) and then to see which of the two conditions you have for it is failing?

**Comment by aquasonic** [comment]
Yes I have. It seems that adding the new mapper removes all available mappers. The first call to my mappers `CanHandle()` method is invoked by the first property of my model (which is the item id). My mapper can not handle this (which is ok) and Glass Mapper then throws the mentioned error that there is no mapper available to handle the Id property.

My data mapper should only handle properties with the `SitecoreSharedField` attribute.

**Comment by Kasaku** [comment]
Ok, I've dug into it a little further and here is the issue. As you've already identified, it's not related to your specific mapper, it happens with adding any mapper.

The `DataMapperConfigFactory` overrides the `AddTypes` method to supply all of the default mappings. `AddTypes` is called in the base class by the `GetItems` method, which only calls it if *no types have been added* already:

```csharp
public virtual IEnumerable<T> GetItems()
{
	if (TypeGenerators.Count == 0)
	{
		AddTypes();
	}

	return TypeGenerators != null
		? TypeGenerators.Select(f => f())
		: null;
}
```

So, as soon as you add a custom mapping, all of the default mappings won't be implemented.

A non-elegant but working fix is to trigger `GetItems()` early, so as to populate the mappers before you add your own:

```csharp
// Dummy call to add in default types.
resolver.DataMapperFactory.GetItems();
resolver.DataMapperFactory.Add( ... );
```

Remember you'll need to use `Insert` if you want your mapper to be hit before one of the standard mappers.

Perhaps @mikeedwards83 can advise on how to proceed? I would suggest that `GetItems()` adding items itself would be unexpected behaviour, so perhaps a slightly different approach to prepopulating the mappers would be better.

**Comment by aquasonic** [comment]
Yes this seems to work, as long as you insert the mapper with `Insert()` :) Let us wait what @mikeedwards83 will say to this. For now, the workaround seems to be ok.

**Comment by mikeedwards83** [comment]
I will take a look... sorry for the problem.

**Comment by mikeedwards83** [comment]
I have a branch with a potential fix. Just waiting for Nat to give it a
second pair of eyes. You can see this on Github.

Le lun. 18 mai 2015 13:46, Kevin Brechbühl <notifications@github.com> a
écrit :

**Comment by mikeedwards83** [comment]
I have pushed a fix to our develop branch. This is available from the nightly build as 4.0.1.27

**Comment by aquasonic** [comment]
Great, thanks a lot Mike :+1:

**Comment by mikeedwards83** [comment]
This has been release in 4.0.1.8, reopen if this is still and issue.
