### ISSUE TITLE
GetModelFromView only works with Default context

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#138]
Hi Mike,

I found an issue with the `GetModelFromView` pipeline processor. There you resolve the `SitecoreContext` with the following code:

    ISitecoreContext scContext = SitecoreContext.GetFromHttpContext();

This get's the `Default` context. When I don't have a default context, it throws an exception:

    The given key was not present in the dictionary.

Is it possible that you can add a parameter to the pipeline configuration where we can specify the context? Or is there maybe a better solution which would also work with multiple contextes?

I initialize my context like this in the `GlassMapperSc.cs`:

    var context = Glass.Mapper.Context.Create(resolver, "MyName"); 

Regards,
Kevin

**Comment by aquasonic** [comment]
Hi Mike,

is this really an enhancement? :) The issue actually is, that is doesn't work when you don't have a "Default" context for Glass. Or is this a requirement from Glass, to have at least one context with the name "Default"?

Cheers,
Kevin

**Comment by mikeedwards83** [comment]
Kevin

I have added the same property and setup as we have in the GetModel class:

https://github.com/mikeedwards83/Glass.Mapper/commit/9d7a895b3e05f9dcf9056d669111305684b894a6

Hopefully this is sufficient, it is in the develop branch at the moment.

Mike

**Comment by aquasonic** [comment]
Hi Mike,

thanks, so it would be possible to configure the pipeline processors as follow, right?

    <mvc.getModel>
        <processor type="Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc">
            <ContextName>MyContext</ContextName>
        </processor>
        <processor type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc">
            <ContextName>MyContext</ContextName>
        </processor>
    </mvc.getModel>

**Comment by mikeedwards83** [comment]
This update has been released. Closing issue.
