### ISSUE TITLE
Upgraded to Glass v4, Custom Data Handlers Problems

### ISSUE THREAD

**Issue by samick6** [mikeedwards83/Glass.Mapper#145]
I upgraded to Glass Mapper v4.  I encountered: https://github.com/mikeedwards83/Glass.Mapper/issues/135

I then download the latest version of Glass from the develop branch.

I have two custom data handlers.  Neither works.

1. I use the Monoco Link list field as shown in this blog: http://www.seanholmesby.com/sitecore-glass-mapper-data-handler-for-a-link-list-field/

The link list field now throws: https://groups.google.com/forum/#!topic/glassmapper/d7AXsl6pW5E
I am at a loss about how to proceed.

2. I have a custom data handler for legacy InternalLink classes.  This class does not throw an exception.  Glass simply fails to map the data.  I re-factored the GlassMapperScCustom.cs as shown here: http://www.glass.lu/Mapper/Sc/Documentation/UpgradingToV4

I added Sitecore Diagnostic Log message to the GetFieldValue and SetFieldValue methods of the class.  The methods are never executed.

Any help is appreciated.  Regards. 

Tom

**Comment by mikeedwards83** [comment]
Hi Tom

I think we had a mistake in our documentation, please try:

            var resolver = new DependencyResolver(config);

            resolver.DataMapperFactory.Insert(0,() = > new MyFieldMapper());

            return resolver;

We have updated the docs on Glass http://www.glass.lu/Mapper/Sc/Documentation/UpgradingToV4

Mike

**Comment by samick6** [comment]
Mike,

You are the man.  Thank you.

Tom

**Comment by mikeedwards83** [comment]
I have added a method called First to do the same in the next version

**Comment by mikeedwards83** [comment]
fixed in 4.0.2

**Comment by muso31** [comment]
Can anybody help with SitecoreInstaller after upgrading from v3 -> v4? In v3 my GlassMapper.Custom.cs used:

`container.Install(new SitecoreInstaller(config));`

is this no longer required? Where can I find syntax for data mapper registrations? For example, must I update all DependacyResolution files such as SitecoreInstaller.cs which previously used the windsor installer with the following syntax...

```
            container.Register(Component.For<ISiteSettings>().UsingFactoryMethod(() =>
                new SiteSettingsFactory(container.Resolve<ISitecoreContext>()).GetSettings()).LifestylePerWebRequest()
            );
```

If so what is the new syntax for this? Thanks in advance

**Comment by ambujshukla1981** [comment]
I upgraded to Glass Mapper v4.  What is new syntax for below code

  //create the resolver
            var resolver = DependencyResolver.CreateStandardResolver();

            //install the custom services
            var config = new Config();

            var container = resolver.Container;
            container.Install(new SitecoreInstaller(config));

            var assembliesSetting = Sitecore.Configuration.Settings.GetSetting("ConfigureIoc.Assemblies");
            var assemblies = assembliesSetting.Split(new[] {','}, StringSplitOptions.RemoveEmptyEntries);
            container.Install(new ControllerInstaller(assemblies));

            //create a context
            var context = Glass.Mapper.Context.Create(resolver);

            context.Load(
                new SitecoreAttributeConfigurationLoader(assemblies)
                );


            //register the Glass components
            container.Register(
                Component.For<ISitecoreContext>().ImplementedBy<SitecoreContext>().LifestyleTransient(),
                Component.For<ISitecoreService>().UsingFactoryMethod(() => new SitecoreService("master")).LifestyleTransient()
                );

            var controllerFactory = new WindsorControllerFactory(ControllerBuilder.Current.GetControllerFactory(), container.Kernel);


            ControllerBuilder.Current.SetControllerFactory(controllerFactory);

**Comment by cardinal252** [comment]
Castle Windsor is no longer required for Glass Mapper to work, the out of the box implementation does not use windsor any more. It looks also like you are using Windsor for your version of an implementation. All of the code required to set up Glass is available when you install the nuget package in App_Start/GlassMapperSc.cs and App_Start/GlassMapperScCustom.cs

Cheers

**Comment by bjouhari** [comment]
@ambujshukla1981 If possible can you please share you App_Start/GlassMapperSc.cs and App_Start/GlassMapperScCustom.cs.
I am also going a glass mapper update form v3 to v4 with Castle Windsor , but not sure about the update steps.
