### ISSUE TITLE
Sitecore Date Field + ServerTimeZone Setting

### ISSUE THREAD

**Issue by rhamille** [mikeedwards83/Glass.Mapper#147]
Hi Mike,

Quick question, with the introduction of ServerTimeZone setting, would it be more appropriate for the GetValueField in SitecoreFieldDateTimeMapper to use the ToServerTime instead of the IsoDateToDateTime?

maybe something like 

public override object GetFieldValue(string fieldValue, Configuration.SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
{
            var result = global::Sitecore.DateUtil.IsoDateToDateTime(fieldValue);
#if (SC80 || SC75)
            result =   global::Sitecore.DateUtil.ToServerTime(result);
#endif
            return result;
}

Thanks!

Regards,

Rhamille

**Comment by mikeedwards83** [comment]
I think we would have to introduce a flag to indicate this to support backward compatibility.

**Comment by mikeedwards83** [comment]
This has been already released without the flag
