### ISSUE TITLE
Save() hangs when class contains property of type Stream

### ISSUE THREAD

**Issue by drachele** [mikeedwards83/Glass.Mapper#148]
This is my glass mapped class (taken from this example of saving media items http://www.glass.lu/Blog/SitecoreCopyImages):

```
[SitecoreType(AutoMap = true, TemplateId = Constants.Templates.IdStrings.MediaItemFile)]
public class MediaItemFile
    {
        [SitecoreField("Mime Type")]
        public virtual string MimeType { get; set; }

        [SitecoreField("__Icon")]
        public virtual string Icon { get; set; }

        public virtual Stream Blob { get; set; }
        public virtual string Extension { get; set; }
        public virtual long Size { get; set; }
    }
```

_Blob_ maps to the blob field on a media item.

The template this is using inherits from the unversioned Zip template in Sitecore.

I am able to create an item using the _SitecoreService.Create()_ method, but if I get the object using _SitecoreService.GetItem()_ and try to update it by setting its Blob property to the new attachment stream and then calling _SitecoreService.Save()_, the code hangs. Indefinitely. I need to kill the worker process to get my application running again. It also managed to kill our database server once - I had to restart it!

Any idea why this might be happening?

I'm using the latest version of Glass.Mapper.Sc (4.0.1.8).

Thanks,
Dan.

**Comment by mikeedwards83** [comment]
Dan

Can you send me the code you are executing to make the save?

Mike

**Comment by drachele** [comment]
```
using (new SecurityDisabler())
            {
                Package package;
                var isNewPackage = false;

                var folderItem = sitecoreContext.GetItem<PackageFolder>(Constants.Content.Ids.Packages);

                if (edition.Package != null)
                {
                    package = sitecoreContext.GetItem<Package>(edition.Package.Id);
                }
                else
                {
                    package = new Package();
                    isNewPackage = true;
                }

                package.Blob = memoryStream;
                package.Size = memoryStream.Length;
                package.Extension = ".zip";
                package.MimeType = "application/zip";
                package.Name = edition.Name;

                memoryStream.Seek(0, SeekOrigin.Begin);

                if (isNewPackage)
                {
                    sitecoreContext.Create(folderItem, package);
                    edition.Package = package;
                    sitecoreContext.Save(edition);
                }
                else
                {
                    sitecoreContext.Save(package);
                }
            }
```

_MemoryStream_ is created previous to this code block.

I've done more digging, and worked out that if I detach then re-attach the ZIP file in the Sitecore admin interface on the item, then the update works.

As a workaround I am reverting to the _File_ type on my domain object and using native Sitecore API calls to create and update the MediaItem,

Let me know if you need more information.

Thanks,
Dan.

**Comment by mikeedwards83** [comment]
Where does the memoryStream come from?

**Comment by mikeedwards83** [comment]
I have tested with this code:

        void button_Click(object sender, EventArgs e)
        {
            var master = new SitecoreService("master");

            var mediaItem =master.GetItem<MediaItemFile>(id);
            mediaItem.Blob = file.FileContent;
            mediaItem.Size = file.FileContent.Length;

            using (new SecurityDisabler())
            {
                master.Save(mediaItem);
            }

        }


And this worked fine for me.

**Comment by drachele** [comment]
The MemoryStream is generated on-the-fly - it's basically a ZIP file which is generated and attached to the Sitecore MediaItem.

I even tried saving the stream to a temporary file and then attaching but still had the same issue.

After more digging I found that if I created the item using Sitecore's MediaCreator, then subsequently updated the item using Glass Mapper, then the update succeeded. This leads me to think it has something to do with the way Glass is creating the item?

**Comment by mikeedwards83** [comment]
Hi

I have tested with a create and not had a problem:

            var folderId = new Guid("{15451229-7534-44EF-815D-D93D6170BFCB}");

            var master = new SitecoreService("master");

            var folder = master.GetItem<Folder>(folderId);
            var mediaItem = new MediaItemFile();
            mediaItem.Blob = file.FileContent;
            mediaItem.Size = file.FileContent.Length;
            mediaItem.Name = "Test Filed" + DateTime.Now.ToString("ddMMMyyyyhhmmss");
            mediaItem.Extension = file.FileName.Split('.').Last();
            mediaItem.MimeType = "application/zip";
            using (new SecurityDisabler())
            {
                master.Create(folder, mediaItem);
            }


Do you have any custom events?

Mike

**Comment by drachele** [comment]
Hey Mike,

After you created the item in this way, did you then attempt to update it?

The issue I had was, once creating the item using Glass, trying a subsequent update on that item of the ZIP attachment failed.

Cheers,
Dan.

**Comment by mikeedwards83** [comment]
Hi Dan

Sorry for the slow reply. My latest test is this:

            var master = new SitecoreService("master");

            var folder = master.GetItem<Folder>(id);

            var mediaItem = new MediaItemFile();
            mediaItem.Name = "Test";
            mediaItem.Blob = new MemoryStream();
            using (new SecurityDisabler())
            {
                master.Create(folder, mediaItem);
            }

            mediaItem.Blob = file.FileContent;
            mediaItem.Size = file.FileContent.Length;
            mediaItem.Extension = file.FileName.Split('.').Last();
            mediaItem.MimeType = "application/zip";

            using (new SecurityDisabler())
            {
                master.Save(mediaItem);
            }

            mediaItem.Name = "Modified";
            using (new SecurityDisabler())
            {
                master.Save(mediaItem);
            }

This executed without a problem, do you have any more details?

Mike

**Comment by smithc** [comment]
Hey Mike,

I ran across similar issues in the past when using glass models that have a mapped 'Stream' property.  I eventually discovered that Glass eagerly maps (and accesses) the stream when the glass model is created, which leads to the stream never being disposed (especially in the case where the glass model in question lives for a long period of time).

This caused problems down the line, because we would run out of SQL connections (as each stream instance was backed by an open SQL stream).

The solution I eventually came up with was to build a custom Stream mapper that would force the stream to be loaded lazily when the property was first accessed.  It would then be up to caller to ensure that the stream was disposed (if it was ever accessed).  

I'm not a fan of this solution, but it provides a passable workaround to the problem.  Hopefully you find this helpful, and can come up with a better one.

**Comment by mikeedwards83** [comment]
@smithc I have updated the mapper to copy the data to an in memory stream and close the original stream, see commit https://github.com/mikeedwards83/Glass.Mapper/commit/fed6b8dfb9fee9e8d39316405e7bd0d0e70dd93f


I might investigate making a lazy handler as well.
