### ISSUE TITLE
EditFrame removes backslashes

### ISSUE THREAD

**Issue by jclementson** [mikeedwards83/Glass.Mapper#151]
Hi,

I noticed this problem using a field of the type "Sitecore User" but in fact it applies to any text field.

I'm not yet certain if it's a Glass issue or a Sitecore issue.

Here's my example:

    [SitecoreType(TemplateId = "{A3A6DEA5-096D-44B5-8DC2-FEAEFC73CA1D}", AutoMap = true)]
    public interface IBasePageInfo : IBase
    {
        bool DisplayAuthor { get; set; }
        string Author { get; set; }
    }

where author is a "Sitecore User" field.

and the razor view:

    @using (Html.Glass().BeginEditFrame(Model, "Edit page info", x => x.DisplayAuthor, x => x.Author))
    {
        ... 
    }

Using the edit frame to alter the Author field, I find that the backslash has been removed, so e.g. "sitecore\admin" becomes "sitecoreadmin". I can see this by opening the edit frame a second time without saving the item, i.e. between the two screenshots all I have done is close the edit frame and re-open it, without saving the item.

As I say, this applies to any text field, not just "Sitecore User" fields.

With a bit of trial and error I've found that if a field contains _four_ backslashes, they are not removed completely, but replaced with a single backslash. So it looks like something to do with JSON encoding in the postback when the edit frame is closed.

I don't know Sitecore well enough to know if this is a Sitecore issue or specific to Glass, but I'd like to know. If it is a Sitecore issue, how could I reproduce it without using Glass in order to report it to Sitecore support?

Cheers
![backslash1](https://cloud.githubusercontent.com/assets/1948832/8333959/446d755e-1a8d-11e5-958e-66d8d8b8be67.png)
![backslash2](https://cloud.githubusercontent.com/assets/1948832/8333961/46a57f2e-1a8d-11e5-9a38-505ff691d544.png)

**Comment by jclementson** [comment]
Ok, I've reproduced this without Glass using the sample code at http://sitecoreexperiences.blogspot.co.uk/2013/05/sitecore-66-mvc-editframe-helper.html

Seems it is a bug in Sitecore's own EditFrame class.

Thanks Mike for being on hand anyway!

**Comment by mikeedwards83** [comment]
Thanks for letting me know.
