### ISSUE TITLE
Public generics on GlassContoller doesn't allow attribute routing.

### ISSUE THREAD

**Issue by mikeedwards83** [mikeedwards83/Glass.Mapper#153]
Hi,

I'm experiencing a similar problem with both 3.3.1.48 and 4.0.0.4

Cannot call action method 'T GetContextItemT' on controller 'Glass.Mapper.Sc.Web.Mvc.GlassController' because the action method is a generic method.

It seems that:
GetContextItem
GetDataSourceItem
GetLayoutItem
are public which means that the above issue with attribute routing has returned.

Can these also be made protected?
Thanks :)

**Comment by mikeedwards83** [comment]
Fixed in develop

**Comment by mikematthes** [comment]
GetContextItem is still public in Glass.Mapper.Sc.Web.Mvc.GlassController in version 4.0.1.8

**Comment by mikeedwards83** [comment]
I mark things as ready once they are in the nightly build that is available from the Glass build server. Once I push it out into the main release on Nuget I will close the issue. 

See the downloads page on the Glass site for information of how to download this from the build server.

Thanks

Mike

**Comment by mikeedwards83** [comment]
Fixed in 4.0.2

**Comment by jballe** [comment]
I just updated to 4.0.3.50 and got a similar error, but for the method:
```c#
public virtual T GetRenderingParameters<T>() where T : class
```

The complete stacktrace is:
```
[ArgumentException: Cannot call action method 'T GetRenderingParameters[T]()' on controller 'Glass.Mapper.Sc.Web.Mvc.GlassController' because the action method is a generic method.
Parameter name: methodInfo]
   System.Web.Mvc.ReflectedActionDescriptor..ctor(MethodInfo methodInfo, String actionName, ControllerDescriptor controllerDescriptor, Boolean validateMethod) +306
   System.Web.Mvc.Async.<>c__DisplayClass4.<GetActionDescriptorDelegate>b__2(String actionName, ControllerDescriptor controllerDescriptor) +36
   System.Web.Mvc.Routing.AttributeRoutingMapper.GetActionDescriptors(ReflectedAsyncControllerDescriptor controller) +107
   System.Web.Mvc.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, IEnumerable`1 controllerTypes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +82
   System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IEnumerable`1 controllerTypes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +84
   System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider) +151
   System.Web.Mvc.Routing.AttributeRoutingMapper.MapAttributeRoutes(RouteCollection routes, IInlineConstraintResolver constraintResolver) +37
   System.Web.Mvc.RouteCollectionAttributeRoutingExtensions.MapMvcAttributeRoutes(RouteCollection routes) +46
```

Any thoughts on this? Is it related or something else?

Thanks!

**Comment by mikeedwards83** [comment]
@jballe  Thanks for the update, we have just pushed a hotfix for this 4.0.3.51

**Comment by jballe** [comment]
Perfect, it works
