### ISSUE TITLE
Glass not initialized properly on some occasions

### ISSUE THREAD

**Issue by robmaas** [mikeedwards83/Glass.Mapper#154]
Hello Mike,

We're using SC8 (update 3) and Glass 4.0.1.28 beta, initializing using the pipeline. We're using attribute configuration (no fluent config).

On some occasions it seems like glass is not initializing correctly, most field will NOT map except for some basic stuff like ID's. Also the `.Map<T>()` function will not load extra fields.

This seems to happen at random occasions, like once every 4 builds/recycles.
Whenever Glass has loaded correctly, it will keep working correctly during the pool's active time. Vice versa if it won't.

I've scanned through the known issues, but none of them seem to be anything like the behavior we're experiencing.

I am considering downgrading to 3.x, but might as well try this first :)

Thanks and keep up the good work!

Rob

**Comment by mikeedwards83** [comment]
Rob

Can you give me an example of a model not initialising correctly? And more details over what you mean by extra fields in the .Map<T>?

Thanks

Mike

**Comment by robmaas** [comment]
Mike

This a one of the models we're using.

    [SitecoreType(TemplateId = AppConstants.NewsArticleTemplateID)]
    public class NewsArticle : BaseItem, IContent, IMeta, ITagging, INavigation, ILikes
    {
        [SitecoreField]
        public virtual string Title { get; set; }

        [SitecoreField]
        public virtual string Summary { get; set; }

        [SitecoreField(FieldType = SitecoreFieldType.RichText, Setting = SitecoreFieldSettings.RichTextRaw)]
        public virtual string Content { get; set; }

        [SitecoreField("Important news")]
        [IndexField("important_news")]
        public virtual bool ImportantNews { get; set; }

        [SitecoreField("Display in menu")]
        public virtual bool DisplayInMenu { get; set; }

        [SitecoreField("Title in menu")]
        public virtual string MenuTitle { get; set; }

        [SitecoreField("Display in sitemap")]
        public virtual bool DisplayInSitemap { get; set; }

        [SitecoreField("Meta title")]
        public virtual string MetaTitle { get; set; }

        [SitecoreField("Meta keywords")]
        public virtual string MetaKeywords { get; set; }

        [SitecoreField("Meta description")]
        public virtual string MetaDescription { get; set; }
        
        [IndexField("tags")]
        public virtual IEnumerable<Guid> TagIDs { get; set; }

        [UIHint("Tags")]
        [SitecoreField(FieldName = "Tags", Setting = SitecoreFieldSettings.DontLoadLazily)]
        public virtual IEnumerable<Tag> Tags {get; set;}
    }

As you can see it inerhits from `BaseItem` which looks like this:

    public class BaseItem : IStatistics
    {
        [SitecoreId]
        [IndexField("_group")]
        public virtual Guid ID { get; set; }

        [IndexField("_template")]
        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateID { get; set; }

        [IndexField("_templatename")]
        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        public virtual String TemplateName { get; set; }

        [IndexField("_name")]
        [SitecoreInfo(SitecoreInfoType.Name)]
        public virtual String Name { get; set; }

        [IndexField("_fullpath")]
        [SitecoreInfo(SitecoreInfoType.Path)]
        public virtual String Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        [IndexField("_language")]
        public virtual string Language { get; set; }

        [TypeConverter(typeof(IndexFieldItemUriValueConverter))]
        [XmlIgnore]
        [IndexField("_uniqueid")]
        public virtual ItemUri Uri { get; set; }

        [SitecoreInfo(SitecoreInfoType.Url, UrlOptions = SitecoreInfoUrlOptions.LanguageEmbeddingNever)]
        public virtual string Url { get; set; }

        [SitecoreField("__Created")]
        [IndexField("__smallcreateddate")]
        public virtual DateTime CreatedDate { get; set; }

        [SitecoreField("__Created by")]
        [IndexField("parsedcreatedby")]
        public virtual string CreatedBy { get; set; }

        [SitecoreField("__Updated")]
        [IndexField("__smallupdateddate")]
        public virtual DateTime Updated { get; set; }

        [SitecoreField("__Updated by")]
        [IndexField("parsedupdatedby")]
        public virtual string UpdatedBy { get; set; }

        [SitecoreField("Show statistics")]
        public virtual bool ShowStatistics { get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version
        {
            get
            {
                return Uri == null ? 0 : Uri.Version.Number;
            }
        }
    }

As far as I have noticed two problems arise when the main issue arises:
1) When creating items using `masterService.Create<T>` Glass throws an Error (`Failed to create SitecoreContext`) and after: `ERROR Type .... does not have a Template ID or Branch ID`.
2) When using these models in combination with `ContentSearch` (`BaseItem` does not inherit `SearchResultItem`) we use the `.Map<T>` function to fill the model. This seems to work for fields which are inherited from `BaseItem`, but none of the additional fields are mapped/filled. No errors/warnings etc are logged. The search provider is generic (`where T : BaseItem`).

So far we tried downgrading to 3.x and upgrading to 4.0.8 but the issue remains.

I hope this gives a more clear understanding of our problem.

Thanks
Rob

**Comment by robmaas** [comment]
Mike,

Some additional info my colleague found out by taking Glass's source:
The `TypeConfigurations` does not include the specific Model, but it does include the `BaseItem`, which is returned instead of loading the Model OnDemand.

We have tried including the Namespace in the GlassLoaders in App_Start (AttributesConfigurationLoader), but this made no change either.

Rob

**Comment by robmaas** [comment]
Hey Mike,

Do you have any idea how to solve this issue?

Rob

**Comment by mikeedwards83** [comment]
Sorry rob, thanks for the nudge. I am taking a look now.

**Comment by mikeedwards83** [comment]
Ok Rob I think I see the potential problem. When you do the create I suspect that this is the first time that Glass has seen the NewsArticle class, this means that when you call create it is hitting this part of the code:


            var config = TypeConfigurations.ContainsKey(type) ? TypeConfigurations[type] : null;

            if (config != null) return config as T;

            if (checkBase && type.BaseType != null)
            {
                //check base type encase of proxy
                config = TypeConfigurations.ContainsKey(type.BaseType) ? TypeConfigurations[type.BaseType] : null;
            }


Which is causing Glass to check for the base type which is BaseItem.

The reason this is happening intermittently  is because some times NewsArticle is loaded into the config.

Can you send me the code you used to setup the AttributeConfigurationLoader because that should have solved the problem.

In the Glass.Mapper.Sc.Custom.cs file it should look like this:

		public static IConfigurationLoader[] GlassLoaders(){			
                        var loader = new AttributeConfigurationLoader("Assembly.Name");
			return new IConfigurationLoader[]{loader};
		}

Mike

**Comment by robmaas** [comment]
Hi Mike,

Our config looks like this:

    public static IConfigurationLoader[] GlassLoaders(){			
        var core = new AttributeConfigurationLoader("xx.xxxxxx.xxxxxx.Core");
        var web = new AttributeConfigurationLoader("xx.xxxxxx.xxxxxx.Web");

        return new IConfigurationLoader[] { core, web };
    }

We also have a glass model for `SearchResult`, which can be of type `NewsArticle`, `Page` or a couple others.
This `SearchResult` model inherits from `BaseItem` but does not have the `SitecoreType` attribute because it doesn't have a explicit TemplateID.

**Comment by mikeedwards83** [comment]
Hum, I am at a loss. Would it be possible to do a screenshare? Maybe tomorrow morning?

**Comment by robmaas** [comment]
Hey Mike,
You are free to take a look at our config/code, but we do NOT have steps to reproduce.
As said before, it seems to happen at very rare occasions, which makes debugging and testing even harder.
So I'm not really sure if a screenshare is going to help.
