### ISSUE TITLE
Null Reference while retrieving the children of an item.

### ISSUE THREAD

**Issue by ecx-florianscholz** [mikeedwards83/Glass.Mapper#156]
Hi Mike, 

I'm experiencing a strange problem while getting an item and it's children. I'm using GlassMapper v4 (NuGet) and Sitecore 8.

1. http://pastebin.com/RxK5wv40 (Retrieval Code. Retrieving the Item without my GetDataSource extension by QuerySingle produces the same error.)
2. http://pastebin.com/xAWGyTpD (TdsClasses.cs)
3. http://pastebin.com/yCNGzuBu (Add Children Property to Tab_Module)

Item Tree:

![item tree](https://cloud.githubusercontent.com/assets/9606237/8717680/e96329ac-2b9d-11e5-8860-23212a35a4f0.png)

![item tree 2](https://cloud.githubusercontent.com/assets/9606237/8717684/ee330254-2b9d-11e5-8c61-a55182d80da0.png)

Error Message:

![stack trace](https://cloud.githubusercontent.com/assets/9606237/8717785/d19339ce-2b9e-11e5-938f-9b3e4c9b5c36.png)

**Comment by mikeedwards83** [comment]
Hi

We load children lazy, i.e. at the point at which the code tries to enumerate the list. To do this a reference to the service that created the parent item is held and used to evaluate the children. 

This creates a problem for the way you have written your code. You are disposing of the SitecoreContext before the enumeration happens:

            using (SitecoreContext ctx = new SitecoreContext())
            {
                Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
                tabs = datasource.Children;
            }
 
            int bla = tabs.Count();

In your code the call to enumerate the children won't occur until the tabs.Count() is called, by this time you have disposed of the actual SitecoreContext that it would use to do this.

The solution is to either do this:

            using (SitecoreContext ctx = new SitecoreContext())
            {
                Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
                tabs = datasource.Children.ToArray();  // force the enumeration to happen here
            }
 
            int bla = tabs.Count();

Or:

            using (SitecoreContext ctx = new SitecoreContext())
            {
                Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
                tabs = datasource.Children;
                int bla = tabs.Count(); //force the enumeration here.
            }

**Comment by ecx-florianscholz** [comment]
After enumeration, can I return the tabs safely?

2015-07-16 15:15 GMT+02:00 Mike Edwards <notifications@github.com>:

> Hi
>
> We load children lazy, i.e. at the point at which the code tries to
> enumerate the list. To do this a reference to the service that created the
> parent item is held and used to evaluate the children.
>
> This creates a problem for the way you have written your code. You are
> disposing of the SitecoreContext before the enumeration happens:
>
>         using (SitecoreContext ctx = new SitecoreContext())
>         {
>             Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
>             tabs = datasource.Children;
>         }
>
>         int bla = tabs.Count();
>
> In your code the call to enumerate the children won't occur until the
> tabs.Count() is called, by this time you have disposed of the actual
> SitecoreContext that it would use to do this.
>
> The solution is to either do this:
>
>         using (SitecoreContext ctx = new SitecoreContext())
>         {
>             Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
>             tabs = datasource.Children.ToArray();  // force the enumeration to happen here
>         }
>
>         int bla = tabs.Count();
>
> Or:
>
>         using (SitecoreContext ctx = new SitecoreContext())
>         {
>             Tab_Module datasource = ctx.GetDataSource<Tab_Module>();
>             tabs = datasource.Children;
>             int bla = tabs.Count(); //force the enumeration here.
>         }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeedwards83/Glass.Mapper/issues/156#issuecomment-121952634>
> .
>



-- 

Florian Scholz

Sitecore Developer (Student)

ecx.io | creating digital success
Bracknell – Dusseldorf – Munich – Vienna – Wels – Zurich

ecx.io | facebook.com/ecxio | twitter.com/ecxio

ecx.io germany GmbH | Plange Mühle 1 | 40221 Düsseldorf
t. +49 211 4174320 | f. +49 211 41743220
Handelsregister Düsseldorf HRB 65041 | Geschäftsführer: Christoph Mause,
Jochen Sperber, Markus Dietrich

ecx international AG | Terminalstrasse Mitte 18 | 85356 München
Handelsregister München HRB 196211
Vorstand: Gerald Lanzerits, Christoph Mause, Helmut Nachbauer, Jochen
Sperber
Aufsichtsrat: Dr. Michael Cohen (Vorsitzender), Dipl.-Kfm. Ralph-Uwe
Johann, Dr. Georg Unger
