### ISSUE TITLE
GetModel load order

### ISSUE THREAD

**Issue by codywatkins** [mikeedwards83/Glass.Mapper#157]
Hi,

Just wanted to let you know of something we ran into with Glass.Mapper.Sc.

In Sitecore 8, we load all our customized (non-Out of the box) config files in through a folder called "Xtras". We do this to ensure all of our custom configs run last (Sitecore loads in .config files in alpha order). Thus if we're overriding any app settings or what not using custom configs, the Xtras folder ensures they load at the very end (due to the X in the name) -- I guess we could have used Z, but Xtras was what we went with). I can't remember if this tip came from John West or some other blog.

Anyway, when we put our Glass.Mapper.Sc.config into our Xtras folder, we get a weird issue in which the View Model isn't loaded with the data when using an View rendering using GlassView (the model exists but everything is null). But yet we could get the populated model if we did SitecoreContext.GetCurrentItem<ModelName>().

After some digging with dotPeek, I've determined that the GlassMapper getModel pipelines were running too late. If we weren't using the Xtras folder, by default they would run first because "Glass.Mapper.Sc.config" comes before "Sitecore.Mvc.config" in alpha order. But using our Xtras folder, we buggered this up and they ended up running after the other Sitecore.Mvc.getModel pipelines. (this was confirmed using ShowConfig.aspx, and reviewing the order of the processors).

Thus the GlassMapper getModel was always exiting out on the first line when it hit this piece of code:
if (args.Result != null)
        return;

Because one of the Sitecore processors was populating args.Result.

We made the following changes and it seems to have fixed the issue. Not sure if this kind of approach should be added into the source. It seems like the getChromeData processor was patched in a specific order, yet the getModel processors weren't.

<mvc.getModel>
        <processor patch:before="*[@type='Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc']" type="Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc"/>
        <processor patch:before="*[@type='Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc']" type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc"/>
      </mvc.getModel>

**Comment by mikeedwards83** [comment]
Hi 

I am not sure what change you made?

Mike

**Comment by codywatkins** [comment]
In Glass.Mapper.Sc.config we changed:

<mvc.getModel>
        <processor type="Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc"/>
        <processor type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc"/>
      </mvc.getModel>

To:

<mvc.getModel>
        <processor patch:before="*[@type='Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc']" type="Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc"/>
        <processor patch:before="*[@type='Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc']" type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc"/>
      </mvc.getModel>

(Alternatively we could have used this instead: patch:before="processor[1]".)

Reason being, on our Site, because we force custom configurations to load last (as described in my initial comment), the default Glass.Mapper.Sc.config would include the custom pipeline processors at the end of <mvc.getModel> which causes it not to work. We needed to forced them load before the "GetFromItem" processor.

**Comment by mikeedwards83** [comment]
Thanks for the suggestion, I have pushed this into the develop branch ready for the next release.

**Comment by mikeedwards83** [comment]
This issue has been fixed in release 4.0.3.50
