### ISSUE TITLE
Issue with Sitecore events being raised when creating a fake item

### ISSUE THREAD

**Issue by seankearney** [mikeedwards83/Glass.Mapper#158]
This was created as a result of the bug found [here](https://github.com/HedgehogDevelopment/sitecore-field-fallback/issues/18) in the Field Fallback module.

Glass code goes and creates an in-memory Sitecore item via [this](https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source%2FGlass.Mapper.Sc%2FGlassHtml.cs#L242) and [this](https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source%2FGlass.Mapper.Sc%2FUtilities.cs#L86)

Basically – Glass goes and creates a fake, in memory, Sitecore item. This triggers events to be fired in Sitecore. Specifically it triggers the `AddingVersion` and `SavingItem` events. It should also trigger the `AddedVersion` and `SavedItem` events; it does not fire the last two. 

I’ve registered a bug with Sitecore #442839. Here is a [simple script to duplicate Sitecore bug](https://gist.github.com/seankearney/1b6df5acf16b7f4cabe0)

Sitecore's response thus far is:

> The `AddedVersion` and `SavedItem` events are database specific. Because of the creating the item in memory without parent item, it does not appears in the database. That’s why you cannot see these events. If you want to see them, you have to create item with the parent

Being we aren't *really* creating an item I'm not sure we want events to be raised at all.

**Comment by mikeedwards83** [comment]
This has been fixed in https://github.com/mikeedwards83/Glass.Mapper/pull/159
