### ISSUE TITLE
Problem with Glass V4 using it with WebForms project

### ISSUE THREAD

**Issue by Bilyukov** [mikeedwards83/Glass.Mapper#160]
Installed Glass V4 with nuget on SC 8 web forms solution.

When I try to hit any sitecore page I get:

"Could not resolve type name: Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc (method: Sitecore.Configuration.Factory.CreateType(XmlNode configNode, String[] parameters, Boolean assert))."

I noticed that Glass.Mapper.Sc.Mvc is not referenced in the web project. 

I possible reason for this problem is that the .Net Mvc assemblies are not referenced and Glass can not determine which version of Glass.Mapper.Sc.Mvc to include

**Comment by mikeedwards83** [comment]
Not going to fix this, I think it may cause problems for existing glass users. Also playing around with how we might do this in the install.ps is causing all sorts of problems. 

Since MVC is now on by default I think we will leave this as is.
