### ISSUE TITLE
Sitecore 8 and Solr

### ISSUE THREAD

**Issue by a3code** [mikeedwards83/Glass.Mapper#161]
I have switched my Sitecore 8 solution to use Solr.
Would galas mapper user this index for search ?
And more important question 
Is is possible to achieve use some Solr Api with Glass Mapper ? for example, build Solr faceting based on Glass.Mapper

**Comment by mikeedwards83** [comment]
If you have used the method described in  [Tutorial 25]http://www.glass.lu/Mapper/Sc/Tutorials/Tutorial25) then you shouldn't have any problems. 

The Map method will look at your model and try to find either an ItemUri property or separate Item Id, language and version properties. Using either of these methods it will then find the appropriate item in Sitecore to map you Solr. Therefore you need to ensure that the results returned by Solr contain either an ItemUri property or all of other three.
