### ISSUE TITLE
<mvc.getModel> added in config when Glass.Mapper.Sc.Mvc isn't installed

### ISSUE THREAD

**Issue by SaintSkeeta** [mikeedwards83/Glass.Mapper#162]
Hey guys,
Is it possible to only include the <mvc.getModel> config node when the Glass.Mapper.Sc.Mvc.DLL is installed from the Glass Nuget package?
I have a pure WebForms project, so no System.Web.Mvc reference. Therefore Glass.Mapper.Sc.Mvc.DLL doesn't get added as a reference.
This is fine, but the Glass.Mapper.Sc.config file contains a reference to the Glass.Mappers.Sc.Mvc.DLL in the <mvc.getModel> pipeline.
This gets triggered in Sitecore 8 when loading the sitecore admin panel (while loading SpeakLayout.cshtml), and an exception is thrown.

For now, I can just remove the config, or reference the DLL manually, but I figure it might need to work in tandem with the DLL.

Thanks,
Sean

**Comment by mikeedwards83** [comment]
Hi

I experimented with this yesterday and it was throwing up all sorts of side
issues. I would assume that most people are making mvc applications these
days so hopefully it wouldn't affect to many people.

Mike

**Comment by mikeedwards83** [comment]
Closing based on previous comment.
