### ISSUE TITLE
EnforceTemplate.TemplateAndBase doesn't recursively check the base templates of base templates.

### ISSUE THREAD

**Issue by DrewMadsen** [mikeedwards83/Glass.Mapper#164]
We've run into an issue were we have a "Homepage" Item that inherits from a "Page" Item via base templates. The "Page" Item in turn inherits a number of templates via base templates. We are using EnforceTemplates to help make certain that the correct items are being cast to the correct models. The issue arises when we try to cast a model that is a base templates of the "Page" item against the "Homepage" item. With enforce templates set to "TemplateAndBase" it returns null as though the model can't be cast to the "Home" page item even though the "Homepage" item.

We're wondering if the EnforceTemplates functionality was never intended to recursively compare base templates, or if this is perhaps a an issue/bug with glass.mapper.

**Comment by mikeedwards83** [comment]
Hi

It should recursively check and I am wondering if this therefore a logic issue. Looking at the source code it should. I am wondering if there is a problem with the caching.

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/Pipelines/ObjectConstruction/EnforcedTemplateCheck.cs#L31

**Comment by DrewMadsen** [comment]
I suspect the issue is the if tree starting on line 42. It checks the base templates of the context, but not the base templates of those base templates. This is causing it to return false on templates that inherit target template 2 levels or deeper.

I created a solution for this locally, I added a method to be called recursively to check for a matches.

![glassrecrusivebasetemplatecheck](https://cloud.githubusercontent.com/assets/13018870/9472741/c580a5de-4b1c-11e5-828e-124f5de47d0d.jpg)

Then I added another option to the if tree for recursive, as well as adding the option to the enumerable.

![glassrecrusivebasetemplatecheck2](https://cloud.githubusercontent.com/assets/13018870/9472770/e4729376-4b1c-11e5-9ded-1441b172557e.jpg)

**Comment by mikeedwards83** [comment]
Thanks,

I have added the recursive check and decide not to add the additional enum value.

Mike

**Comment by mikeedwards83** [comment]
This has been pushed to develop ready for the next release.

**Comment by mikeedwards83** [comment]
This issue has been fixed in release 4.0.3.50
