### ISSUE TITLE
GlassController not handling when Sitecore MVC RenderingContext uninitialized

### ISSUE THREAD

**Issue by halovanic** [mikeedwards83/Glass.Mapper#165]
In a number of places, GlassController is attempting a null check of RenderingContext:
`Sitecore.Mvc.Presentation.RenderingContext.Current == null`

However, if the RenderingContext is not initialized, Sitecore's ContextService (at least in 7.2) throws an InvalidOperationException: a null value **is** properly returned with `Sitecore.Mvc.Presentation.RenderingContext.CurrentOrNull`, which I think was the intent of these checks.

In my case this is affecting using GlassController v4 in unit tests where SitecoreContext would be replaced with a mock.  Glass v3.2 seemed to have the same issue with the null checks, but was catching the resulting InvalidOperationException before calling SitecoreContext again so it wasn't noticeable.

**Comment by mikeedwards83** [comment]
I have pushed a commit to develop that should address this issue.

**Comment by halovanic** [comment]
Thanks, this fixed the issue for me.
