### ISSUE TITLE
Cannot mock the LayoutItem<> in GlassController with out a wrapper

### ISSUE THREAD

**Issue by charlesafford** [mikeedwards83/Glass.Mapper#167]
Please can we have the ability to mock the LayoutItem<> on a GlassController with out having to use a wrapper.  This would be really useful for unit testing .  Thanks,

**Comment by mikeedwards83** [comment]
We have started to mock this up here https://github.com/mikeedwards83/Glass.Mapper/tree/feature/renderingContext

**Comment by charlesafford** [comment]
Thanks Mike, Will take a look :)

**Comment by mikeedwards83** [comment]
This issue has been fixed in release 4.0.3.50
