### ISSUE TITLE
When Caching is enabled, _configurationResolver sometimes will be null in AbstractService

### ISSUE THREAD

**Issue by KKings** [mikeedwards83/Glass.Mapper#169]
Hey Mike --

I've been able to debug this a little and the root cause is the _configurationResolver is null after an item is cached; seems to occur with the LazyObjectInterceptor and the LazyItemEnumerable. Clearing the cache resolves the issue for that item.

Turning the caching off, problem goes away.

It seems that when caching an item with a Property that is a Proxy, the LazyObjectInterceptor holds a reference to the args that has long been disposed, which causes the_configurationResolver (and others) to be null.

Relevant stack trace for the LazyItemEnumerable:

> [NullReferenceException: Object reference not set to an instance of an object.]
   Glass.Mapper.AbstractService.RunConfigurationPipeline(AbstractTypeCreationContext abstractTypeCreationContext) +221
   Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) +81
   Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) +615
   Glass.Mapper.Sc.<ProcessItems>d__2.MoveNext() +993
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +451
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +69
   Glass.Mapper.Sc.LazyItemEnumerable`1.<.ctor>b__0() +155
   System.Lazy`1.CreateValue() +709
   System.Lazy`1.LazyInitValue() +467
   Glass.Mapper.Sc.LazyItemEnumerable`1.GetEnumerator()

A little more information, I run a crawl of the site in order to populate every occurrence of the model.

Let me know if you need more information.

**Comment by mikeedwards83** [comment]
Hi

I would generally recommend that for items that are being cached that lazy loading is turned off. 

@cardinal252  do you think we should do something to explicitly avoid caching with lazy objects? This could be too complicated to track.

**Comment by mikeedwards83** [comment]
We need to document this recommendation.

**Comment by KKings** [comment]
Thanks Mike, I second the recommendation.

However, would it be better to handle caching of objects that have not been fully instantiated, either proxy or lazy loaded? Seems like it wouldn't be too much work to rewrite the tasks to use the current context service from the http request, instead of from the args passed in. Thoughts?

**Comment by mikeedwards83** [comment]
The problem with lazy loading a cached object is that we can't be certain of the state of the system when it tries to load the object. We also need to maintain references to a lot of objects when lazy loading. These objects are released one the lazy loading has occurred but you wouldn't want these hanging around in a cache waiting to be used.

We also have to use the value from the args because the object could be populated by a background process that isn't a page request. For example it could be a scheduled task.

**Comment by mikeedwards83** [comment]
Closing based on previous answer

**Comment by ssartell** [comment]
I seem to be having the same issue but, instead of lazy loading, I'm using an interface for a field type. It's the same exception but the call stack goes through the InterfacePropertyInterceptor. Is this a known issue?
