### ISSUE TITLE
Subclasses that are lazy loaded is not resolved and mapped correctly

### ISSUE THREAD

**Issue by lasserasch** [mikeedwards83/Glass.Mapper#170]
In the following example, the reference from SomeItem to OtherItem is not corretly resolved, when both classes are automapped and the Sitecore Item for SomeItem has a Guid Link to a subitem in a field called "OtherItem".

The Other Item will be resolved at as a CastleProxyItem and field values are not set for that proxy item.

This happens only if a concrete class is resolved. If an Interface is used it works as expected.
this can be fixed quickly, by changing the "CreateConcreteTask" pipeline, and removing the "if(args.AbstractTypeCreationContext.IsLazy )" statement.

The following will not work
        

        public void Execute(ObjectConstructionArgs args)
        {
            if (args.Result != null 
                || args.Configuration == null 
                || args.Configuration.Type.IsInterface
		        || args.Configuration.Type.IsSealed)
                return;

            if(args.AbstractTypeCreationContext.IsLazy )
            {
                //here we create a lazy loaded version of the class
                args.Result = CreateLazyObject(args);
               // args.AbortPipeline();

            }
            else
            {
                //here we create a concrete version of the class
                args.Result = CreateObject(args);
                //args.AbortPipeline();
            }
        }

Example of a class setup that will cause this issue :

    public class SomeItem : Page
    {
        public string Title { get; set; }
        public string NavigationText { get; set; }
        public string Body { get; set; }
        public virtual OtherItem Other { get; set; }
    }

    public class OtherItem
    {
        public virtual string Title { get; set; }
    }

The following will fix it :

        public void Execute(ObjectConstructionArgs args)
        {
            if (args.Result != null 
                || args.Configuration == null 
                || args.Configuration.Type.IsInterface
		        || args.Configuration.Type.IsSealed)
                return;

       
                //here we create a concrete version of the class
                args.Result = CreateObject(args);
                //args.AbortPipeline();
        
        }

**Comment by jballe** [comment]
This looks more as it will disable lazy load completely?I think we could get the same behavior if you disable lazy load on the relevant properties. Are you certain that it doesn't work? It is just Castle.Core, but it probably requires that the properties of the lazy class are virtual. 
Otherwise, I think this should be implemented in a custom CreateConcreateTask implementation if possible.

**Comment by lasserasch** [comment]
Jesper, i am not saying the fix is the right fix. I will let other people decide what is the correct fix, as long as it gets fixed. I have not added any pull requests either. 

I have build a custom Glass binary for the project where i am using it :-) 

In regards to virtual properties on the lazy loaded object. That is what i have on the example code above, please correct me if i misunderstand what you mean.

The above fix, does not disable lazy loading on collections, interfaces etc. I does however disable lazy loading in this specific scenario yes.

Best Regards
Lasse

**Comment by mikeedwards83** [comment]
I tried your example but wasn't able to replicate the issue. 

As @jballe  said we can't make this change because lazy loading would be disabled and this would cause major problems for a Sitecore solution. Especially in the scenario where items reference each other in a loop.

Do you have any other examples you could share that exhibit the problem?

Thanks

Mike
