### ISSUE TITLE
Property "Parent" can not be of type Guid. If it is, the automap will fail

### ISSUE THREAD

**Issue by lasserasch** [mikeedwards83/Glass.Mapper#171]
If you create a class with the reserved property name "Parent" and make that property of type 'Guid' glassmapper will fail to automap an item to that class.

However it throws a very misleading exception : Only supports constructors with a maximum of 10 parameters

Seems like the property 'Parent' can only be of type 'Item'. That is of cause fine, even though i would have assumed that 'Guid' would also be a valid value and mapped to the ID of the Parent Item.

But the Exception needs to be better. This has nothing to do with to many parameters in a constructor.

**Comment by cardinal252** [comment]
The correct type for a Parent should be a type - such as IMyModel as far as I am aware.

Did you specify a mapping for the property or were you relying on auto mapping ?

**Comment by isurufonseka** [comment]
The parent can actually be any model that has an ID property, for example 

public class YourCustomSitecoreBaseClass
{
    [SitecoreId]
    Guid Id { get; set; }
}

Then in your class where you want to access the parent you could do the following

  [SitecoreParent]
  YourCustomSitecoreBaseClass Parent { get; set; }

Based on the above, sounds like the error message you are seeing is correct.

**Comment by mikeedwards83** [comment]
I have looked into this and I don't think we can improve the error messaging. Glass will try to construct an object based on the type requested (in this case Guid). It then failed because it couldn't find an appropriate constructor. 

To achieve the ability to map an ID as a parent property you will need to implement a custom data mapper.
