### ISSUE TITLE
Using RenderLink with a collection (v4)

### ISSUE THREAD

**Issue by samick6** [mikeedwards83/Glass.Mapper#174]
I am having problem iterating through Glass properties that are collections and using the RenderLink method.  This work in older versions of Glass, but the implementation seems to have changed.  Wondering if anyone has come across this.  Thanks

******* Rendering ********
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<SomeCompositeTemplate>

...

                    @foreach (CatalogueTerms cTerm in Model.CasualtyCatalogueTerms)
                    {
                                    @RenderLink(x => cTerm.ProductNamePDF)
                    } 

*****************************

    [SitecoreType(TemplateId = "272E8203-93B7-4B87-8A38-39209FA28993")]
    public class CatalogueTerms: GlassBase
    {
        [SitecoreField("CatalogueTerms_ProductName")]
        public virtual Link ProductNamePDF { get; set; }
    }

   [SitecoreType(TemplateId = "3AE21659-523B-4997-BD85-3D5954C4397E")]
    public class SomeCompositeTemplate : GlassBase
    {
        [SitecoreQuery("CatalogueTerms//Casualty//*[@@templateId = '{272E8203-93B7-4B87-8A38-39209FA28993}']", IsLazy = false, IsRelative = true)]
        public virtual IEnumerable<CatalogueTerms> _CasualtyCatalogueTerms { get; set; }

        public virtual List<CatalogueTerms> CasualtyCatalogueTerms
        {
            get
            {
                if (_CasualtyCatalogueTerms != null)
                    return _CasualtyCatalogueTerms.ToList();
                else
                    return new List<CatalogueTerms>();
            }
        }
}

**Comment by mikeedwards83** [comment]
Hi 

We made a change in an earlier version of Glass.Mapper.Sc to improve the performance of rendering by caching lambda expressions using with Editable, RenderLink and RenderImage

Therefore you need to update your RenderLink to the following to avoid the incorrect data being rendered:

@foreach (CatalogueTerms cTerm in Model.CasualtyCatalogueTerms)
                {
                                @RenderLink(cTerm, x => x.ProductNamePDF)
                } 

Ensure that your lambda expression references the lambda variable name and not the instance variable name.
