### ISSUE TITLE
Support Experience editor for Children items

### ISSUE THREAD

**Issue by a3codeDA** [mikeedwards83/Glass.Mapper#175]
I have small misunderstanding how to set up correctly Experience editor option for children items without placeholder. I need to have option to remove it but it is possible for placeholder datasource only 
```c#
 public interface IBase
    {
        [SitecoreId]
        Guid Id { get; set; }
   [SitecoreInfo(SitecoreInfoType.FullPath)]
        string FullPath { get; set; }
}
 public interface IRootCollection : IBase
    {
        [SitecoreChildren]
        IEnumerable<ICModel> Children { get; set; }
    }

   [SitecoreType(TemplateId = "{someid}", AutoMap = true)]
    public interface ICModel : IBase
    {

        Image Image { get; set; }

        string Title { get; set; }

        string Description { get; set; }
    }

@foreach (var item in Model.Children) { using (BeginEditFrame(item.Path)) { <div class="col-lg-3"> @RenderImage(item, m => m.Image, isEditable: true) <h2>@Editable(item, m => m.Title)</h2> </a> <div>@Editable(item, m => m.Description)</div> </div> } } 
```

What would be the best case for set up it correlty ?
and that if I need the same logic for children items for  ICModel  ?

I asked it on stackoverflow as well
http://stackoverflow.com/questions/32847774/glass-mapper-support-experience-editor-for-child-items?noredirect=1#comment53552897_32847774

**Comment by cardinal252** [comment]
I am not sure this is directly a Glass Mapper question. It looks like a question on how to use custom experience buttons to make child items editable in Sitecore.
