### ISSUE TITLE
Rendering parameters null reference error with upgrade

### ISSUE THREAD

**Issue by hiraldesai** [mikeedwards83/Glass.Mapper#176]
Hi guys,

I found a following issue when trying to upgrade from v4.0.1.5 to v4.0.3.51. Can someone please confirm if this is expected or accidental breakage?

I have a user control with following declaration:
`public partial class MyControl : GlassUserControl<ISitecoreTemplate>`

It throws null reference error when it's trying to access a property inside it that internally calls something like this this:
```
        public IRenderingParameter MyProperty
        {
            get { return GetRenderingParameters<IRenderingParameter>(); }
        }
```

The error happens because underlying `WebUtil.ParseUrlParameters(parameters)` in `GlassHtml.cs` throws error when parameters is null.

As a temp fix - I had to subclass `GlassUserControl` into `MyGlassUserControl` and add something like this to it.

```
        public override string RenderingParameters
        {
            get { return base.RenderingParameters ?? ""; }
        }
```

I have also noticed the same issue in MVC view renderings with direct calls inside views similar to following.

`var parameters = GetRenderingParameters<IRenderingParameter>();`

**Comment by cardinal252** [comment]
It looks like its just uncovered a case in GlassHtml that is uncaught, I have added appropriate checks to prevent this on feature/issue176 @mikeedwards83 will have to confirm and push a dev release.

**Comment by hiraldesai** [comment]
Thanks @cardinal252.

On a separate note can you point me to a doco for a local setup of this solution if I wanted to look around the project and/or contribute in future?

**Comment by mikeedwards83** [comment]
This fix is in the latest nightly build. @hiraldesai  Could you check to see if this fixes your issue?

**Comment by hiraldesai** [comment]
Thanks @mikeedwards83 - sorry haven't had a chance to verify this because of un-related issues. I will try and do it ASAP.

**Comment by mikeedwards83** [comment]
@hiraldesai  Any news?

**Comment by hiraldesai** [comment]
Hi @mikeedwards83 - sorry for the delay. Yes - it's fixed~!

**Comment by hiraldesai** [comment]
Actually - it fixes the null reference error but introduces a new error. `default(T)` returns null when your rendering parameter type is in interface. I'm pretty sure previous versions returned a proxy class to the type instead. Is it something that's changed - or I'm missing something in my configuration?

**Comment by mikeedwards83** [comment]
@hiraldesai Can you post your model and code?

**Comment by hiraldesai** [comment]
Hi @mikeedwards83 - no worries. Just created a simple new Sitecore sublayout to demonstrate - we have 100s of similar sublayouts with rather complex models across our solution using similar code. 

This line throws null reference exception:
```
<%# GlassTestRenderingParameters.Title %>
```

In previous versions of Glass mapper, `IGlassTestRenderingParameters` would return a non-null proxy class regardless of whether there are any rendering parameters defined for the sublayout or not.

*User Control - GlassTest.ascx*
```
<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="GlassTest.ascx.cs" Inherits="Website.Components.Glass.GlassTest" %>
<h1>
    <%# GlassTestModel.Title %>
</h1>
<h2>
    <%# GlassTestRenderingParameters.Title %>
</h2>
```
*User Control Code Behind - GlassTest.ascx.cs*
```
namespace Website.Components.Glass
{
    public partial class GlassTest : GlassUserControl<IGlassTestModel>
    {
        public IGlassTestModel GlassTestModel => Model;

        protected IGlassTestRenderingParameters GlassTestRenderingParameters => GetRenderingParameters<IGlassTestRenderingParameters>();
    }

    [SitecoreType(TemplateId = "{D6757932-F495-481D-9592-455E603A8329}", AutoMap = true)]
    public interface IGlassTestModel
    {
        [SitecoreField("GlassTestModel_Title")]
        string Title { get; set; }
    }

    [SitecoreType(TemplateId = "{527FF0F8-E793-4B35-B604-573ED0583097}", AutoMap = true)]
    public interface IGlassTestRenderingParameters
    {
        [SitecoreField("GlassTestRenderingParameters_Title")]
        string Title { get; set; }
    }
}
```

**Comment by hiraldesai** [comment]
UPDATE: 
So there are 2 issues here:

1. Issue with no proxy class created when an interface is used as sublayout parameters model and the parameters template is not defined (rare but possible - and users can make Sitecore do this easily!)
2. Issue with `GetRenderingParametersInternal` method of `RenderingContextUserControlWrapper` returning null/empty string due to a bug

https://github.com/mikeedwards83/Glass.Mapper/commit/6d782995c4336aa76f727262c6c846f76711e775#diff-437e5926ad20a130282de8cec826a1fdR45

Line 45 needs to change from
`var sublayout = _control as Sublayout;`
to
`var sublayout = control as Sublayout;`

I have temporarily done the following changes as workaround in my code. Sorry, ideally I'd create a PR but I need to move onto something else ASAP. 

1. Defaulting the parameters string to `"fakeparam=fakevalue"` takes care of first issue for me. It's just a hack fix for now. Ideally - I'd like Glass mapper to handle it for me (even if it's using a global default setting that you can turn on or off depending on the needs)
2. `GetSublayoutParameters` method below takes care of issue 2 - it's basically a different way to write `GetRenderingParametersInternal`. Hopefully you'll be able to get this in a production release soon.

```
        private string _renderingParameters;
        public override string RenderingParameters
        {
            get
            {
                if (_renderingParameters != null)
                    return _renderingParameters;

                // CODE: TEMP FIX TO GET AROUND THE ISSUE WHERE Rendering Parameters are not populated correctly
                //var userSpecifiedParameters = RenderingContext.GetRenderingParameters(); <- This returns nothing!
                var userSpecifiedParameters = GetSublayoutParameters(this);
                _renderingParameters = !string.IsNullOrWhiteSpace(userSpecifiedParameters) ? userSpecifiedParameters : "fakeparam=fakevalue";
                return _renderingParameters;
            }
        }

        private static string GetSublayoutParameters(Control control)
        {
            while (true)
            {
                if (control == null)
                    return null;
                var sublayout = control as Sublayout;
                if (sublayout != null)
                    return sublayout.Parameters;
                control = control.Parent;
            }
        }
```

**Comment by jeroendegroot** [comment]
Is this going to be in the next release and if so when is this release? Will need to have my custom build until then

**Comment by mikeedwards83** [comment]
I think what we are doing is correct. If Sitecore does not contain a value for rendering parameters then the returned value should be null. If we return an empty object I think that is misleading. 

For example there might be times when you want to do something like this in your code:

    var parameters = GetRenderingParameters<MyModel>();
    if(parameters == null){
       //do something
    }

I think a better solution for individual projects would be to add an extension method that for your particular scenario:


    public static T GetRenderingParameters<T>(this AbstractGlassUserControl control, Func<T> default)    
    {
         var model = control.GetRenderingParameters<T>();
         return model ?? default();
    }
 

Then in your code:

        var parameters = GetRenderingParameters<MyModel>(()=>new MyModel());

This allows you to be more explicit about handling null situations.

Issue 200 has been merged.
