### ISSUE TITLE
Set Buttons and Frame Title for expirence editor

### ISSUE THREAD

**Issue by a3codeDA** [mikeedwards83/Glass.Mapper#178]
I would like setup a title for frame and my custom buttons with BeginEditFrame, but I can't set it up in last method

   public GlassEditFrame BeginEditFrame();
    public GlassEditFrame BeginEditFrame(string dataSource);
    public GlassEditFrame BeginEditFrame(string buttons, string dataSource);
    public GlassEditFrame BeginEditFrame<T>(T model, string title = null, params Expression<Func<T, object>>[] fields) where T : class;

Is it any other way to set edit frame title ?

**Comment by mikeedwards83** [comment]
Hi 

How are you doing this? You should be able to do:

    @using (BeginEditFrame(Model, "Select Image", x => x.Image)){

    }

Thanks

Mike

**Comment by a3codeDA** [comment]
yes but this method not allow to add some action buttons, for example remove or sort...

**Comment by mikeedwards83** [comment]
The BeginEditFrame support isn't intended to support those features. It is only designed to give a quick  way to create edit frames for editing fields. For more advanced features you need to use the standard Sitecore method of creating edit frames.

**Comment by KayeeNL** [comment]
He @mikeedwards83 @cardinal252  couldn't you add the following solution to Glass: http://stackoverflow.com/questions/32950471/glass-mapper-set-buttons-and-frame-title-for-expirence-editor 

If we have multiple buttons (that's were EditFrames are for), we need to be able to set the title to a custom one as well, instead of the ugly default 'Page Area' one

Looking forward hearing from you (on Slack)

Robbert

**Comment by mikeedwards83** [comment]
@KayeeNL  Thanks for the link, I have made these changes and pushed them into the develop branch.

**Comment by KayeeNL** [comment]
@mikeedwards83 Thanks! 

Call can be done like this in the future?

@using (BeginEditFrame(Model, "PATH TO THE EDITFRAME BUTTONS ", "TITLE NAME"))

regards

Robbert

**Comment by mikeedwards83** [comment]
Yar!

**Comment by a3codeDA** [comment]
nice !

**Comment by KayeeNL** [comment]
@mikeedwards83 Aaaarr!

**Comment by mikeedwards83** [comment]
This has been released in 4.0.6.55

**Comment by mikeedwards83** [comment]
Hi

What do mean by can't invoke? Is it a compile time or runtime issue?

Thanks

Mike
