### ISSUE TITLE
Potential issue with Language Mapping

### ISSUE THREAD

**Issue by cardinal252** [mikeedwards83/Glass.Mapper#179]
public interface ILanguageNavItem
{
    string Title { get; set; }
   
    Sitecore.Globalization.Language Language {get; set;}
}
 
The language is pointing to the guid of the language item so we need ot load the lang.
 
    public class LanguageNavItemMap : SitecoreGlassMap<ILanguageNavItem>
    {
 
        public override void Configure()
        {
            Map(x =>
            {
                x.Info(y => y.Language).InfoType(Glass.Mapper.Sc.Configuration.SitecoreInfoType.Language);
                x.AutoMap();
            });
        }
 
Its giving the following error on the y.language
 
Error  1      Cannot convert lambda expression to type 'System.Action<Glass.Mapper.Sc.Configuration.Fluent.SitecoreType<xxx.ViewModels.Navigation.ILanguageNavItem>>[]' because it is not a delegate type       C:\Projects\yyy\www.site.com\Main\Source\xxx.Web\xxx.Mapping\PureAutoMaps.cs       16     17     xxx.Mapping
Error  2      Cannot implicitly convert type 'Sitecore.Globalization.Language' to 'object'       C:\Projects\yyy\www.site.com\Main\Source\xxx.Web\xxx.Mapping\PureAutoMaps.cs       18     29     xxx.Mapping
Error  3      Cannot convert lambda expression to delegate type 'System.Func<xxx.Models.ViewModels.Navigation.ILanguageNavItem,object>' because some of the return types in the block are not implicitly convertible to the delegate return type       C:\Projects\yyy\www.site.com\Main\Source\xxx.Web\xxx.Mapping\PureAutoMaps.cs       18     29     xxx.Mapping

**Comment by cardinal252** [comment]
Currently cannot replicate....

**Comment by mikeedwards83** [comment]
I can't replicate either. Closing, if you are able to provide more information please reopen.
