### ISSUE TITLE
RenderImage / Editable not rendering when in edit mode

### ISSUE THREAD

**Issue by jwsadler** [mikeedwards83/Glass.Mapper#182]
Hi Mike,

We are using 4.0.1.8 (but I have tried with the latest version and the same issue exists).

everything was working fine until I added some new fields to my model and now Links and Images will not render in edit mode.

E.G. 

When I use the following in my view: @RenderImage(Model, m => m.ImageLarge, isEditable: true) - the image does not render.

When I use the following in view: @RenderImage(Model, m => m.ImageLarge, isEditable: false) - the image renders.

The same happens for RenderLink.

Please advise.

Thanks,

James.

**Comment by mikeedwards83** [comment]
James

I have just tested with 4.0.3 and it works fine for me. Was this the version you tried with? Do you have a copy of the CSHTML and model?

Thanks

Mike

**Comment by jwsadler** [comment]
Hi Mike,

Thanks for the email.  I’m using 4.0.1.8

The odd thing is if I set RenderImage - IsEditable = false it renders.  Is there anything I should check?  Logs?

Here’s the model:

using System;
using System.Collections.Generic;
using System.Linq;
using Deltekcom.Sc.Domain.UserDefined.DeltekEnterprise.DeltekCorporate.Deltek.Components;
using Deltekcom.Sc.Domain.UserDefined.DeltekEnterprise.DeltekCorporate.Deltek.Objects;
using Deltekcom.Sc.Domain.UserDefined.DeltekEnterprise.DeltekCorporate.Deltek.RenderingParameters;
using Deltekcom.Sc.Domain.UserDefined.DeltekEnterprise.EnterpriseBase.BaseObjects;
using Deltekcom.Sc.WebSite.Models.Base;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data.Items;

namespace Deltekcom.Sc.WebSite.Models.Components
{
    public class ProductCategoryModel : SiteBaseModel
    {
        private const string BACK_GROUND_COLOR = "left";
        private const string ALIGNMENT = "white";

        public ProductCategoryModel()
        {
            DatasourceItem = DeltekcomContext.GetDataSourceItem<Item>();
            Pages = new List<IProductCategory>();
            BackGroundColor = BACK_GROUND_COLOR;
            Alignment = ALIGNMENT;
            SetContent();
            SetRendering();
        }

        public Guid Id { get; set; }
        public string Title { get; set; }
        public string BackGroundColor { get; set; }
        public string Alignment { get; set; }
        public Image ImageSmall { get; set; }
        public Image ImageLarge { get; set; }
        public List<IProductCategory> Pages { get; set; }

        public Link ButtonLink { get; set; }
        public bool ShowButton { get; set; }

        public Item DatasourceItem { get; set; }

        private void SetContent()
        {
            var content = DeltekcomContext.GetDataSourceItem<IProductCategoryContent>();
            if (content == null) return;
            Id = content.Id;
            Title = content.Title;
            ImageSmall = content.ImageSmall;
            ImageLarge = content.ImageLarge;

            ButtonLink = content.ButtonLink;
            ShowButton = content.ShowButton;
            //Always take a maximum of 8
            foreach (
                var item in
                    content.Pages.Take(8)
                        .Select(theChild => DeltekcomContext.GetItem<IProductCategory>(theChild))
                        .Where(item => item != null))
            {
                Pages.Add(item);
            }
        }


        private void SetRendering()
        {
            var rendering = DeltekcomContext.GetRenderingItem<IProductCategoryRendering>();
            if (rendering == null) return;
            BackGroundColor = DeltekcomContext.GetItem<ISimpleText>(rendering.BackgroundColor).Code;
            Alignment = DeltekcomContext.GetItem<ISimpleText>(rendering.ImageAlignment).Code;
        }
    }
}

Here’s the main rendering (I’ve set them all to IsEditable=false to get them to show):

@using Sitecore.Links
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<Deltekcom.Sc.WebSite.Models.Components.ProductCategoryModel>

@if (Model.DatasourceItem == null)
{
    <h1>[Datasource not set]</h1>
    return;
}

<div class="section @(Model.BackGroundColor == "grey" ? "" : Model.BackGroundColor)" data-title="@(Model.Title)" id="@(Model.Title)">
    <div class="container">
        <div class="call-out-content">
                <h2>@Editable(Model, m => m.Title)</h2>
        </div>
        <div class="row">
            @if (Model.Alignment == "left")
            {
               @Html.Partial("~/Views/Deltek Enterprise/Deltek Corporate/Deltek/Renderings/Content/_ProductCategoryImages.cshtml", Model)
            }
            <div class="col-sm-4">
                @if (Model.Pages.Count > 0)
                {
                    for (var i = 0; i <= Model.Pages.Count - 1; i++)
                    {
                        var item = Model.Pages[i];
                        <a href="@LinkManager.GetItemUrl(SitecoreContext.Database.GetItem(new Sitecore.Data.ID(item.Id)))"><h4>@Editable(item, x => x.ProductCategoryTitle)</h4></a>
                        <p>@Editable(item, x => x.ProductCategoryAbstract)</p>
                        if (i == 3)
                        {
                            @:</div>
                            @:<div class='col-sm-4'>
                        }
                    }
                }
               </div>
            @if (Model.Alignment == "right")
            {
                @Html.Partial("~/Views/Deltek Enterprise/Deltek Corporate/Deltek/Renderings/Content/_ProductCategoryImages.cshtml", Model)
            }
        </div>



        @if ((Model.ShowButton && Model.ButtonLink != null))
        {
            <div class="call-out-content">@RenderLink(Model, m => m.ButtonLink, new { @class = "btn", @role = "button" },isEditable:false)</div>
        }
    </div>
</div>

Here’s the image rendering:

@using Sitecore.Links
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<Deltekcom.Sc.WebSite.Models.Components.ProductCategoryModel>

<div class="col-sm-4 visible-xs hidden-md hidden-sm">
    @RenderImage(Model, m => m.ImageSmall, isEditable: false)
</div>

<div class='@(Model.Pages.Count <= 4 ? "col-sm-8" : "col-sm-4") hidden-xs'>
    @if (Model.Pages.Count <= 4)
    {
        @RenderImage(Model, m => m.ImageLarge, isEditable: false)
    }
    else
    {
        @RenderImage(Model, m => m.ImageSmall, isEditable: false)
    }
</div>

All the text-based fields render as editable.

Thanks,

James.

James West-Sadler
Technical Architect & Certified Sitecore Developer

[cid:2047E2CA-ED25-4C77-8F1F-A5D3189C53A9@jwsadler.local]


P: 604.947.9497
M: 778.837.8159
S: +1 315 675 4317
W: www.jwsadler.com<http://www.jwsadler.com>
W: james.westsadler.com<http://james.westsadler.com>
E: james@jwsadler.com<mailto:james@jwsadler.com>

Linked-In Profile: http://www.linkedin.com/in/jwsadler
Skype: james@jwsadler.com<mailto:james@jwsadler.com>




On Oct 22, 2015, at 3:26 AM, Mike Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:


James

I have just tested with 4.0.3 and it works fine for me. Was this the version you tried with? Do you have a copy of the CSHTML and model?

Thanks

Mike

—
Reply to this email directly or view it on GitHub<https://github.com/mikeedwards83/Glass.Mapper/issues/182#issuecomment-150172761>.

_______________________________________________________________________
This email has been scanned for viruses by J.W. Sadler Ltd's
Email Security System.

We endeavour to ensure that all emails sent through our system are
virus-free but we accept no responsibility. Please ensure you have
anti-virus protection.

_______________________________________________________________________


________________________________
This email has been scanned for viruses by our Email Security System. We endeavour to ensure that all emails sent through our system are virus-free but we accept no responsibility. Please ensure you have anti-virus protection. This e-mail, any associated files and the information contained in them are confidential and is intended for the addressee(s) only. If you have received this message in error please notify the originator and delete the email immediately. The unauthorised use, disclosure, copying or alteration of this message is strictly forbidden. E-mails to and from the company are monitored for operational reasons and in accordance with lawful business practices. Any opinions expressed are those of the individual and do not necessarily represent the views of the company. The company does not conclude contracts by email and all negotiations are subject to contract. We make every effort to maintain our network free from computer viruses but accept no responsibility for any viruses which might be transferred by this e-mail.

**Comment by jwsadler** [comment]
BTW: If I use Sitecore's Html.Sitecore().Field instead to render it works fine.

**Comment by mikeedwards83** [comment]
I assume your other fields are editable

**Comment by jwsadler** [comment]
Yes


________________________________
This email has been scanned for viruses by our Email Security System. We endeavour to ensure that all emails sent through our system are virus-free but we accept no responsibility. Please ensure you have anti-virus protection. This e-mail, any associated files and the information contained in them are confidential and is intended for the addressee(s) only. If you have received this message in error please notify the originator and delete the email immediately. The unauthorised use, disclosure, copying or alteration of this message is strictly forbidden. E-mails to and from the company are monitored for operational reasons and in accordance with lawful business practices. Any opinions expressed are those of the individual and do not necessarily represent the views of the company. The company does not conclude contracts by email and all negotiations are subject to contract. We make every effort to maintain our network free from computer viruses but accept no responsibility for any viruses which might be transferred by this e-mail.

**Comment by mikeedwards83** [comment]
If you try

    @Editable(item, x => x.ImageSmall) 

does it work?

**Comment by jwsadler** [comment]
Hi Mike,

No that doesn’t work either.

Thanks,

James.

________________________________
This email has been scanned for viruses by our Email Security System. We endeavour to ensure that all emails sent through our system are virus-free but we accept no responsibility. Please ensure you have anti-virus protection. This e-mail, any associated files and the information contained in them are confidential and is intended for the addressee(s) only. If you have received this message in error please notify the originator and delete the email immediately. The unauthorised use, disclosure, copying or alteration of this message is strictly forbidden. E-mails to and from the company are monitored for operational reasons and in accordance with lawful business practices. Any opinions expressed are those of the individual and do not necessarily represent the views of the company. The company does not conclude contracts by email and all negotiations are subject to contract. We make every effort to maintain our network free from computer viruses but accept no responsibility for any viruses which might be transferred by this e-mail.

**Comment by mikeedwards83** [comment]
I have tested locally again 4.0.1.8 and don't have a problem. I think at this time without seeing your solution I can't help any more. I think with an hour of consultancy we could find the solution.

**Comment by mikeedwards83** [comment]
Closed due to no response
