### ISSUE TITLE
Show which class caused "You cannot save a class that does not contain a property that represents the item ID" error

### ISSUE THREAD

**Issue by sonic1981** [mikeedwards83/Glass.Mapper#186]
Could we please have a more constructive error message for this please? I've just wasted half a day trying to figure out why my object wasn't getting cast when it was actually a child object. Simply naming the class in the error message would of made this much more straight forward.

Details here:

http://stackoverflow.com/questions/33479973/you-cannot-save-a-class-that-does-not-contain-a-property-that-represents-the-it?noredirect=1#comment54748158_33479973

Cheers

**Comment by mikeedwards83** [comment]
Glass already outputs this information:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/Configuration/SitecoreTypeConfiguration.cs#L208

**Comment by sonic1981** [comment]
At some level I seem to of missed this. Couldn't the error message be tweaked slightly something along the lines of:

"Failed to resolve an item of type {0}.  - You cannot save a class that does not contain a property that represents the item ID. Ensure that at least one property of the type {0} has been marked to contain the Sitecore ID."

I feel this would be more intuitive and a very simple change?
