### ISSUE TITLE
RenderLink ExperienceEditor double output

### ISSUE THREAD

**Issue by KayeeNL** [mikeedwards83/Glass.Mapper#191]
He @mikeedwards83 @cardinal252 ,

When in Sitecore 8.1, when I use @RenderLink(m => m.MyLink, isEditable:true) it outputs fine in the Experience Editor, the text from the General Links description field is used, and displayed, if no text has been set, it displays the default [No text in field]

But: when I use @RenderLink(m => m.MyLink, isEditable:true, contents:"default text") it outputs the following in the Experience Editor <span class="scTextWrapper scEnabledChrome" sc-part-of="field">[No text in field]</span>Default Text

When I then fill in the text "Text" in the Description field (for and external or internal General Link field), it outputs like the following <a class="button scEnabledChrome" href="http://www.google.com" sc-part-of="field" style="word-wrap: break-word;">textdefault text</a>

In Preview mode it outputs <a href="http://www.google.com" class="button" style="word-wrap: break-word;">default text</a> which is okay.

So when adding a fixed contents: text, in the Experience editor it outputs both the contents value and the description value.

Any idea of this is a Glass problem or a Sitecore problem?

regards

Robbert

**Comment by mikeedwards83** [comment]
A fix for this has been pushed to develop.

**Comment by KayeeNL** [comment]
@mikeedwards83  wooottttttt! Arrrrrrrr! Good job! Thanks

**Comment by mikeedwards83** [comment]
This has been released in 4.0.6.55
