### ISSUE TITLE
Html.Glass().Editable Error

### ISSUE THREAD

**Issue by chitrangShah** [mikeedwards83/Glass.Mapper#192]
Hi @mikeedwards83 ,
I am facing the below issue in page editor mode. I am using Glass Mapper v4.0.1.8.

    Failed item resolve - You cannot save a class that does not contain a property that represents the          item ID. Ensure that at least one property has been marked to contain the Sitecore ID. Type:         Models.TextContainer 
    at Glass.Mapper.Sc.Configuration.SitecoreTypeConfiguration.ResolveItem(Object target, Database database) at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T model, Object parameters, Context context, Database database, TextWriter writer)

View:

    @model Models.TextContainer
    @if (!Model.Headline.IsNullOrWhiteSpace())
    {
    <h1>
        @Html.Glass().Editable(x => x.Headline)
    </h1>
    }

Model:

    public class TextContainer
    {
        public virtual string Headline { get; set; }
        public virtual string MainContent { get; set; }
    }

GlassMap Config:

    public class TextContainerConfig : SitecoreGlassMap<TextContainer>
    {
        public override void Configure()
        {
            Map(
                x => x.AutoMap(),
                x => x.Field(y => y.Headline).FieldName(IBase_PageConstants.Headline),
                x => x.Field(y => y.MainContent).FieldName(IBase_PageConstants.Content)
                );
        }
    }

I am resolving the Glass maps via Windsor. Based on what I understand, it needs an ID of the item to map it correctly. The ID is being added by the code gen file class as seen.

Generated Code file:

    public static partial class IBase_PageConstants{

			public const string TemplateIdString = "f1344e19-d979-4ddc-9dce-58005f9a2880";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Page";

					
			
			
					
			public static readonly ID HeadlineFieldId = new ID("3c6ae1cc-ce0c-42fc-8af7-399cd72bb6c9");
			public const string HeadlineFieldName = "Headline";
			
					
			public static readonly ID ContentFieldId = new ID("d8699145-35a5-4f99-8074-b624c23941dd");
			public const string ContentFieldName = "Content";
    }

Do I need to provide the ID explicitly in someway? I will try to debug this more and see if I find anything else.

**Comment by mikeedwards83** [comment]
Hi 
Sorry for the delay, this issue here is that your TextContainer class does not inherit the  IBase_PageConstants class therefore class can't find the ID property defined on the class.

Mike
