### ISSUE TITLE
VersionCountDisabler and lazy loaded properties

### ISSUE THREAD

**Issue by jballe** [mikeedwards83/Glass.Mapper#193]
Hi

We have a scenario where we want to avoid creating multiple language versions for some (setup) items, which only have shared fields. We load those items with a VersionCountDisabler around it, which is working nicely.
However one of the setup items are now referencing another item, so with the usual SitecoreFieldTypeMapper the properties are lazy loaded - so when the properties are accessed (outside of the VersionCountDisabler), the item is lazy loaded and returns null when there is no version on that particular language.

Can we in any way make it possible to disable the version count check for an item including its references (and preferable without disable lazy load)?

I was considering if a way was to set the current state of the VersionCountDisabler on the ObjectConstructionArgs so that the LazyObjectInterceptor could reactive this if needed?
Would it make sense in Glass.Mapper as a general feature or should we rather try swapping out the SitecoreFieldTypeMapper, CreateConcreteTask and LazyObjectInterceptor classes with a custom implementation?

**Comment by mikeedwards83** [comment]
@jballe  The simplest solution would be to set lazy loading to false on these models. However you need to be aware of how much data is being loaded if you do this.

I have looked into the possibility of implementing your suggestion but it looks like it is going to require too much of a change to the code base. The main problem being how we can pass down the value the object graph. For example we have a recursive model. 

There are also issues where some of the code that needs to change lives in the Glass.Mapper assembly but we can't push the VersionDisabler into this assembly.

For now I am going to close this issue.
