### ISSUE TITLE
MapperException : Failed to map properties on... need IIS reset

### ISSUE THREAD

**Issue by daveylad** [mikeedwards83/Glass.Mapper#194]
With resepct to this report on https://community.sitecore.net/developers/f/8/p/2047/6239#6239

Has their been any update on this problem... we are experiencing the exact same thing.

Lots of exceptions for Failed to map properties on /sitecore/content/XXX

We've never seen this locally during development, or on our QA servers... as soon as we've put this live onto our prod servers it keeps blowing up every so often.  

I can't say that it's definately traffic related as we've seen it on low loads - there doesn't seem to be any familiar pattern to things tbh.  This is a worrying development for us

**Comment by daveylad** [comment]
Just looking thru our event logs, we think it's related to SitecoreContext.GetItem<T> calls

**Comment by mikeedwards83** [comment]
Dave 

I haven't had any response to the questions I asked. Can you tell me if you are using an IOC container, what lifestyle are you using for SitecoreContext and SitecoreService and is it under load?

**Comment by daveylad** [comment]
Mike,

no IOC, and not sure what you mean by "lifestyle" for SitecoreContext etc?

We're now thinking it's related to this problem btw: https://github.com/mikeedwards83/Glass.Mapper/issues/137

FYI.. we're using Glass Mapper 4.0.0.4

**Comment by mikeedwards83** [comment]
Are you able to update and see if this fixes it? Do you have a stack trace?

**Comment by daveylad** [comment]
The stack traces are virtually identical to the ones in #137 

We're going to look at upgrading as a matter fo urgency now and schedule a push to production.  It's a difficult problem to replicate locally and during test - as you've seen yourself.

In the meantime we've disabled App Pool recycling entirely - hopefully this will get us through to the next deployment.

**Comment by mikeedwards83** [comment]
Dave

I will close this now since it looks like it is related to #137. Please reopen if upgrading doesn't work.

Thanks
