### ISSUE TITLE
View Rendering with broken links

### ISSUE THREAD

**Issue by Sitecoreclimber** [mikeedwards83/Glass.Mapper#198]
Hi Michael,
I have a view rendering with a datasource item. 
My viewrendenring doesn't have a model assign in Model sitecore field. 
If the datasource is a broken link is throwing next error: The model item passed into the dictionary is of type 'Sitecore.Mvc.Presentation.RenderingModel', but this dictionary requires a model item of type 'Project.Web.ViewModels.Components.Banners.ImageBannerViewModel'. I fix the problem modifying your pipeline Glass.Mapper.Sc.Pipelines.Response.GetModelFromView 

    if (renderingItem.DataSource.HasValue())
            {
                Item item = scContext.Database.GetItem(renderingItem.DataSource);
                if(item == null)
                {
                    model = (renderingItem.Item == null ? scContext.GetCurrentItem(modelType, false, false) : scContext.CreateType(modelType, renderingItem.Item, false, false, null, new object[0]));
                }
                else
                {
                    model = scContext.CreateType(modelType, item, false, false, null, new object[0]);
                }
                
            }

    I'm checking if model is null then I create a default model. Can you introduce in a new release this fix?

**Comment by hiraldesai** [comment]
Hi @Sitecoreclimber,

Please have a look at this issue.
https://github.com/mikeedwards83/Glass.Mapper/issues/163

Looks like you're facing the same problem as me. I'm afraid it's a Sitecore bug as Glass is doing the right thing by creating a null model for you. But Sitecore creates a default model for you resulting in this error. I logged this bug with Sitecore, they acknowledged it but from their point of view, using GlassView<Model> is resulting in this error. Using the Sitecore's recommended MVC view rendering pattern won't result in this error. So basically, adding a rendering patch as mentioned in that post is the only way to get around this issue.

If you have any other workarounds, let us know.

Kind regards,
Hiral

**Comment by Sitecoreclimber** [comment]
@hiraldesai  I modify this class : GetModelFromView from GlassMapper and is working fine. 
I just to check if we can have it on a next release because I don't want to patch it.

**Comment by mikeedwards83** [comment]
I have added the code from @hiraldesai to the code base with an additional config (z.Glass.Mapper.Sc.ViewRender.config.exclude).

**Comment by mikeedwards83** [comment]
This has been released in 4.0.6.55

**Comment by alangallauresi** [comment]
We are seeing this issue - getting a default RenderingModel when no model is explicitly set in the view rendering - in 8.1 (rev. 151207) even after applying the config change in a multi-lingual site.  The issue for us seems to be that the RenderingItem is not null but does not have a valid version for the current language.  I've modified our overridden version of GetViewRendererWithItemValidation to handle this by checking with the ItemManager for the count of versions in the language:

            // Override renderer to null when there is an unpublished item refererenced by underlying view
            return viewRenderer.Rendering.Item != null && viewRenderer.Rendering.RenderingItem.ValueOrDefault(i => i.InnerItem) != null
                && ItemManager.GetVersions(viewRenderer.Rendering.Item, viewRenderer.Rendering.Item.Language).Count() > 0
                ? viewRenderer
                : null;
