### ISSUE TITLE
Why are the random utility extension methods publicly exposed?

### ISSUE THREAD

**Issue by stijnherreman** [mikeedwards83/Glass.Mapper#199]
The extension methods in [Glass.Mapper/ExtensionMethods.cs](Source/Glass.Mapper/ExtensionMethods.cs) are publicly exposed. What's the reason for this?
Inattentive developers can introduce an unnecessary dependency on Glass.Mapper like this, e.g. by trying to use [List<T>.ForEach](https://msdn.microsoft.com/en-us/library/bwabdf9z.aspx) on an `IEnumerable` and having a code refactoring tool suggest that they add `using Glass.Mapper;`
In addition, you now also need to be careful of introducing breaking changes in these methods.

**Comment by cardinal252** [comment]
The extensions are often used in multiple assemblies within Glass, this prevents them being anything else I think.

**Comment by mikeedwards83** [comment]
As @cardinal252 this methods need to be exposed across assemblies. It is up to individual developers to check they are using the correct extension methods.
