### ISSUE TITLE
Sitecore 8.1 Update-1 analytics graphs break using Glass.Mapper.Sc v 3.2.1.42

### ISSUE THREAD

**Issue by jrodsmitty** [mikeedwards83/Glass.Mapper#202]
**Problem:**
We upgraded to Sitecore 8.1 Update-1, and are porting our codebase from 7.5 (latest revision) and noticed the analytics graphs in the admin Dashboard are broken.  If I delete the "Glass.Mapper.Sc.Mvc.Config" file, then they work again.  We're using v 3.2.1.42 of Glass.  Are there known incompatibilities with the latest version of Sitecore, and that version of Glass?

![pasted image at 2016_01_21 11_11 am](https://cloud.githubusercontent.com/assets/4333492/12553713/8e42b680-c33e-11e5-8759-2baf7f1f569e.png)

**Solution:**
We upgraded to Glass.Mapper.Sc v4, and the issue went away.  So there appears to be an incompatibility between v3.2.1.42 and Sitecore 8.1 Update-1.

![sitecore-analytics-graph](https://cloud.githubusercontent.com/assets/4333492/12553723/a16692d6-c33e-11e5-87b4-0ef28bbbc6a5.JPG)

**Comment by mikeedwards83** [comment]
Since this is a v3 issue which is solved by upgrading I will close this issue.
