### ISSUE TITLE
GlassMapperSc.cs and .config in consuming project

### ISSUE THREAD

**Issue by jballe** [mikeedwards83/Glass.Mapper#205]
I understand that those files and config are conceptually needed, you should create your application in a way so that you do the required initialization and initialize pipeline is an obvious place for this.
However, I often find it a bit annoying that those files are automatically created as we might have implemented this in another way, another class library with the required configuration or similar. We can easily delete the files when installing yes, but they are readded on each update and this adds to the "stack" of knowledge required for working on a certain project that you should when updating the package either not overwrite those files (when customizing in the project) or delete the added files (when implementing this in another way).

The other configuration files make good sense as they can remain untouched in the project and give the required functionality (for caching, views, etc.)

Could we consider a way to avoid include those content files in the nuget package, it could also be a Glass.Mapper.Sc.Core package without those?

**Comment by mikeedwards83** [comment]
In version 4.2 we have separated the Glass nuget into Glass.Mapper.Sc and Glass.Mapper.Sc.Core. The core assembly contains only the assemblies required by Glass.

**Comment by mikeedwards83** [comment]
Release in 4.2.0

**Comment by jballe** [comment]
So cool, thank you!
