### ISSUE TITLE
Issues with InferType

### ISSUE THREAD

**Issue by jcore** [mikeedwards83/Glass.Mapper#209]
Hi Mike,

I'm running into an issue with InferType. Sometimes a collection gets returned as a collection of a real types (MyProj.DomainObjects.NavigationCategory), other times it comes back as Castle.Proxies.INavigationItemProxy. I don't see any consistency in how this issue surfaces.

Model class has the following:

public partial class NavigationCategory 
{
        [SitecoreChildren(InferType = true)]
        public virtual IEnumerable<INavigationItem> NavigationItems { get; set; }
}

In GlassLoaders method of GlassMapperScCustom I have:

var attributes = new AttributeConfigurationLoader("MyProj.DomainObjects");
return new IConfigurationLoader[] { attributes };

I am running the latest version of Glass Mapper. Let me know if you need more info on this issue.

Thank you.
Best Regards,
Julia

**Comment by cardinal252** [comment]
Can you add the NavigationItem class please ?

**Comment by jcore** [comment]
Here it is. It is a base class for different flavors on NavigationItems that all inherit INavigationItem interface.
 
NavigationItem:
```
       [SitecoreType (TemplateId = SitecoreItemTemplateId, AutoMap = true)]
        public partial class NavigationItem : GlassBase, INavigationItem
	{
		public const string SitecoreItemTemplateId = "sitecore-template-id";

		public const string CssClassFieldId = "css-field-id";

		public const string CssClassFieldName = "Css Class";

		[SitecoreField (CssClassFieldName)]
		public virtual string CssClass {
			get;
			set;
		}
	}
```

INavigationItem:

```
[SitecoreType (TemplateId = NavigationItem.SitecoreItemTemplateId, AutoMap = true)]
	public partial interface INavigationItem : IGlassBase
	{
		[SitecoreField (NavigationItem.CssClassFieldName)]
		string CssClass {
			get;
			set;
		}
	}
```

One of the classes that inherit INavigationItem interface:
```

[SitecoreType (TemplateId = SitecoreItemTemplateId, AutoMap = true)]
	public partial class NavigationCategory : GlassBase, INavigationCategory
	{

		public const string SitecoreItemTemplateId = "sitecore-template-id";

		public const string NavigationTextFieldId = "sitecore-field-id";

		public const string NavigationTextFieldName = "Navigation Text";

		public const string NavigationLinkFieldId = "sitecore-field-id";

		public const string NavigationLinkFieldName = "Navigation Link";

		public const string CssClassFieldId = "sitecore-field-id";

		public const string CssClassFieldName = "Css Class";

		[SitecoreField (NavigationTextFieldName)]
		public virtual string NavigationText {
			get;
			set;
		}

		[SitecoreField (NavigationLinkFieldName)]
		public virtual Glass.Mapper.Sc.Fields.Link NavigationLink {
			get;
			set;
		}

		[SitecoreField (CssClassFieldName)]
		public virtual string CssClass {
			get;
			set;
		}
	}

```

These are items for the navigation tree with 3-4 levels.

-Main Menu Group
-- First Category
--- Link 1
--- Link 2
--- Link with Icon
--- Link with Callout

Partial classes have the following:

```
public partial class NavigationCategory 
    {
        [SitecoreChildren(InferType = true, IsLazy = false)]
        public virtual IEnumerable<INavigationItem> NavigationItems { get; set; }

    }
```

While debugging I sometimes see read types loaded in NavigationItems collection, sometimes all of them are proxies, and sometimes it is a mix of proxied and unproxied objects.

Thank you.
Julia

**Comment by mikeedwards83** [comment]
I notice that the property of the NavigationCategory class in your first message is type Ienumerable and not the generic type of Ienumerable<T>. 

Is this correct? Should you be using the type Ienumerable<INavigationItem>?

**Comment by cardinal252** [comment]
The templateid used on INavigationItem and NavigationItem are the same - Glass can only have 1 type that has a particular template id as it stands - remove the template id from one of them and you should get consistent results on your inferred types (I think)

**Comment by jcore** [comment]
Thank you Nathanael . Let me try that.

**Comment by jcore** [comment]
Bingo! that was it. Thank you SO much Nathanael !!!

**Comment by cardinal252** [comment]
Great :D

**Comment by SaintSkeeta** [comment]
Is this also the case if I wanted to have 2 models (concrete, not interfaces) for the same template (say two View Models for different renderings but the same template)?
I guess then I shouldn't ever use InferType for them, as Glass might Infer the other type?

**Comment by RyanTuckNZ** [comment]
Hey guys, I'm running into this same issue. We are using TDS Classic for CodeGen, and have a property named TemplateId on the IGlassBase interface, and in turn the GlassBase class. T4 templates by default also add SitecoreType to all interfaces and associated classes.

I have a CustomFormSection template that loads children as a base interface that FormFields inherit, via SitecoreChildren

`public partial class CustomFormSection
    {
        [SitecoreChildren(InferType = true, IsLazy = false)]
        public virtual IEnumerable<IFormFieldBase> FormFields { get; set; }
    }

    public partial interface ICustomFormSection
    {
        [SitecoreChildren(InferType = true, IsLazy = false)]
        IEnumerable<IFormFieldBase> FormFields { get; set; }
    }`

And in turn a FormFieldBase and IFormFieldBase class and interface that loads IFieldValidators via SitecoreChildren:

`    public partial interface IFormFieldBase
    {
        [SitecoreChildren(InferType = true, IsLazy = false)]
        IEnumerable<IFieldValidator> Validators { get; set; }
    }

    public partial class FormFieldBase
    {
        [SitecoreChildren(InferType = true, IsLazy = false)]
        public virtual IEnumerable<IFieldValidator> Validators { get; set; }
    }`

The problem is that the validators aren't being inferred consistently. Some builds they'll work correctly, other builds they won't.

If I remove the TemplateId property from the IGlassBase interface, then any `GetItem<>` calls using the interface don't have the TemplateId.

Any ideas on the best way I can solve this? Will I have to rollout my own hand written models for these three base Templates and inherited types?
