### ISSUE TITLE
InferType for children - casting issue

### ISSUE THREAD

**Issue by molntamas** [mikeedwards83/Glass.Mapper#211]
Hi!

Inferring type for Children doesn't seem to work correctly. 

When using I'm using the SitecoreChildren attribute with InferType, like described in this tutorial http://www.glass.lu/mapper/sc/tutorials/tutorial17, it doesn't resolve the subtype for the objects. The children will contain objects with the base class, instead of the subtype as I would expect.

I'm using this attribute:
`[SitecoreChildren(InferType = true, IsLazy = true)]
`

Please see detailed description of the issue in this StackOverflow question, which I've found: http://stackoverflow.com/questions/32638505/glass-mapper-v4-infertype-cast-issue

You can also see a workaround for the issue in the answer.

I'm using 4.0.9.60 version of Glass.Mapper.Sc nuget package.

Please tell me if you need any more details.

**Comment by cardinal252** [comment]
Have you loaded the configuration up front (GlassScCustom) ?

**Comment by molntamas** [comment]
No? How should I do that? 
Otherwise my configurations are applied correctly, so I didn't assume I have to make some of them work explicitly.

I saw somebody wrote this should be done:
`return new IConfigurationLoader[]{ new AttributeConfigurationLoader("[YOUR ASSEMBLY NAME"), };`

**Comment by molntamas** [comment]
I'm using AutoMap = true in my classes.

**Comment by cardinal252** [comment]
yes - you need to pre-load your types using a line like the one you posted 

return new IConfigurationLoader[]{ new AttributeConfigurationLoader("[YOUR ASSEMBLY NAME"), };

if you don't - Glass will map on demand - it will be likely that all the required types are not known otherwise.

**Comment by molntamas** [comment]
Thanks a lot for the quick help, it works fine now.

I  think it would be worth mentioning this in the tutorials, e.g. here http://www.glass.lu/mapper/sc/tutorials/tutorial17. Since it looks like it worked differently in V3 and also some other people stumbled upon this, according to stackoverflow.

Cheers

**Comment by molntamas** [comment]
Is this a bug, that AutoMap=true class property doesn't load the types? 
Or is this expected behavior that loading has to be done explicitly for this use case?

**Comment by cardinal252** [comment]
Automap simple tells Glass to automatically map .net properties with matching sitecore field names (as well as certain key reserved names such as Id and Url). It has nothing to do with inferred types.

Yes - it might be reasonable to add the loading into the tutorial - it is definitely covered in the Glass training, which I highly recommend.
