### ISSUE TITLE
'Page editing error. Could not find property on type System.Object' after upgrading to Glass mapper v.4.0.9.60

### ISSUE THREAD

**Issue by duggu2105** [mikeedwards83/Glass.Mapper#212]
Hi Mike, 
I'm reopening the old issue 'Edit Mode Not Binding Properties #144' through this issue. We have recently upgraded our application from Glass mapper v3 to v.4.0.9.60 and facing this error 'Page editing error. Could not find property <Property name> on type System.Object' on all properties in Edit mode. It works fine in live mode or preview mode.
Here are the details of our Glass mapper implementation:

Domain classes:

[SitecoreType(TemplateId = "{XXXXX}", AutoMap = true)]
    public interface CompanyInformationPage : BasePage
    {
          string CompanyName { get; set; }
    }

[SitecoreType(TemplateId = "{XXXXX}", AutoMap = true)]
    public interface BasePage : ISitecoreItem
    {
        string Title { get; set; }
        string Description { get; set; }
        string Summary { get; set; }
        Image Image { get; set; }
    }

View:

@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<CompanyInformationPage>
<div>
    <h1>@Editable(Model, x=>x.Title)</h1>
    @Html.Raw(@Editable(Model, x => x.Description))
</div>

We have tried removing GlassView as mentioned under http://glass.lu/Blog/GlassV4 (MVC Improvements) section but it didn't fix this issue.
We have also tried enabling z.Glass.Mapper.Sc.ViewRender.config.exclude file as per https://github.com/mikeedwards83/Glass.Mapper/issues/198 but this also didn't work. We just renamed this file and removed '.exclude' extension and didn't make any changes in GlassMapperScCustom.cs file. Are we missing anything here?

Please advise.

Thank you!

**Comment by marcioduarte89** [comment]
Has anyone had any luck with this issue yet? We are experiencing the exact same error..

Best Regards,

**Comment by duggu2105** [comment]
Hi Marcio, the only workaround I found is to convert the existing interfaces as models to classes. This supports Page editing and doesn't throw this exception. I'll be looking for customization with Glass mapper to support 'Interfaces as models' feature of version-3.

**Comment by mikeedwards83** [comment]
I think we have solved this issue in a later hotfix.

See Issue 227
