### ISSUE TITLE
In image tag 'h' and 'w' appended in source URL.

### ISSUE THREAD

**Issue by SummiJ** [mikeedwards83/Glass.Mapper#213]
We upgraded glass mapper to v.4.0.9.60 from v 3.2.1.42. after upgrading URLs are being appended by h and w as height and width which is resulting into some improper image rendering. In previous version it was working fine.
If we remove h and w query strings from URL or replace  with width and  height, it renders fine, provided outputHeightWidth for image should be true.

It should be as - 
![image](https://cloud.githubusercontent.com/assets/17777765/13695289/24cf5d7a-e783-11e5-8ff1-9ac7e63a129a.png)

 But displaying as - 
 ![image](https://cloud.githubusercontent.com/assets/17777765/13695277/f7e4a9b4-e782-11e5-9df0-e67ba81c18ae.png)

Everytime image source is as follows
 "<  img src="imgsrc.jpg?h=47&amp;w=70"  >"

Can you please provide some solution. how can we remove this from URL?

**Comment by mikeedwards83** [comment]
The W & H values are rendered when the W & H values are greater than 0. 

You can override this by passing in parameters to the RenderImage method using an anonymous type or you could create a custom data mapper that replaces the standard SitecoreFileImageMapper and sets the W & H values to -1.

If you need help with this implementation with can provide consultancy.
