### ISSUE TITLE
Ampersand (&amp;) in General Link Text breaks in Experience Editor

### ISSUE THREAD

**Issue by Rogerstigers** [mikeedwards83/Glass.Mapper#215]
When using GlassHtml.Editable to create the HtmlString for the Experience Editor, if there is an `&amp;` in the link text, any changes to content in the experience editor, whether the link is touched directly or not, causes the encoding of the `&amp;` to be converted to a simple &.

Example:
In Raw Values mode, the link originally looks like this:
`<link text="Product Documentation &amp; Uninstall" linktype="internal" class="" title="" target="" querystring="" id="{CD323969-F6D0-495F-9512-5F902AF7FED3}" />`

But once that link appears in Experience Editor and the page is saved, it now shows like this in Raw Values mode:

`<link text="Product Documentation & Uninstall" linktype="internal" class="" title="" target="" querystring="" id="{CD323969-F6D0-495F-9512-5F902AF7FED3}" />`

Obviously, a raw  in an attribute is bad XML.   

Once this issue has happened, the General Link editor will break when editing the link and the content for the link will also not be rendered.  The only way to correct the link at that point is to go into Sitecore's Content Editor and fix the value in Raw Values mode.

We are running version 4.0.10.61.  

Can anyone advise?

**Comment by mikeedwards83** [comment]
Hi

Which version of Sitecore are you using?

Can you test this against the standard Sitecore methods of making a field page editable. It might be that this a Sitecore issue. In the Page Editor Glass hands control over to Sitecore.

I have tested this with Sitecore 8.1 and I don't have the issue.

Mike

**Comment by mikeedwards83** [comment]
Closed due to lack of information.

**Comment by mikeedwards83** [comment]
This seems to be a bug in SC which seems to be fixed in SC8.2
