### ISSUE TITLE
Rich Text Field - Percent Sign Causes Error in Experience Editor

### ISSUE THREAD

**Issue by kmac23va** [mikeedwards83/Glass.Mapper#216]
When placing an @Editable field for a rich text field on a page, if I enter a % character in the text and try to save in Experience Editor, I'm unable to save the page. Looking at the Chrome developer tools, it shows an error of "Uncaught URIError: URI malformed" in "-speak/v1/ExperienceEditor/ExperienceEditor.js:510". I've tried other special characters on the keyboard successfully; it appears to be isolated to the % sign only. This is in 4.0.10.61 and the version before. Thanks.

**Comment by mikeedwards83** [comment]
Have you tried using the standard Sitecore methods of making the field
editable and seeing if this problem is a standard sitecore problem or a
Glass specific issue.

**Comment by kmac23va** [comment]
Good point, I hadn't done that...I'm still newish to Sitecore and found Glass Mapper early on, so I've used it pretty exclusively. I disabled the Glass Mapper stuff for the rendering and put in an @Html.Sitecore().Field() call for the rich text field, and the same error occurs. I'll register it with Sitecore. Thanks, Mike.

**Comment by kmac23va** [comment]
If anyone is on 8.1 Update 1, this was a known Sitecore bug. Support sent me the fix, which is included in 8.1 Update 2, and attached here.
[ExperienceEditor.zip](https://github.com/mikeedwards83/Glass.Mapper/files/234576/ExperienceEditor.zip)
