### ISSUE TITLE
Issues with relative view paths in GetModelFromView.cs

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#221]
Hi Mike,

I heard at SUGCON that we can add relative paths into view rendering definition items. So if a Razor view is put into the folder `/Views/Sitecore/MyView.cshtml` (important is the `Sitecore` folder as they use the `SitecoreController`), then you can simply put `MyView` in the field `Path` of the definition item.

But this results in an error in `GetModelFromView` at the following line:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc.Mvc/Pipelines/Response/GetModelFromView.cs#L136

I've tried to override the `GetViewPath()` method and add the full path manually, but it's private ;-)

Maybe you have a better way of fixing this than change the path manually?

Cheers,
Kevin

**Comment by mikeedwards83** [comment]
We have made the method protected virtual. We have also modified many of the other methods to make them modifiable

**Comment by mikeedwards83** [comment]
Release in 4.2.0
