### ISSUE TITLE
Querystring with url encoded querystrings do not output correctly.

### ISSUE THREAD

**Issue by cardinal252** [mikeedwards83/Glass.Mapper#222]
If the querystrings passed into the Link class contain %3D in their content (seems to be the case for the current client - Sitecore 8.1) then the querystring does not get output correctly through RenderLink.

Steps to recreate:
1. Create a link in sitecore with a querystring of fred=george
2. Check the saved content (contains %3D in the current implementation)
3. Save the link
4. Output the link to screen using Render link

**Comment by cardinal252** [comment]
Potential fix pushed to feature/issue-222

**Comment by mikeedwards83** [comment]
Release in 4.2.0

**Comment by mikeedwards83** [comment]
This fix breaks external links that might legitimately  contain %3d in the URL

**Comment by mikeedwards83** [comment]
@cardinal252 Please review the following commit https://github.com/mikeedwards83/Glass.Mapper/commit/001fb39bebf475cf9da35fe589fa4db9f6279d14

**Comment by cardinal252** [comment]
Looks good to me :+1:

**Comment by mikeedwards83** [comment]
Fixed in Release 4.3

**Comment by maximem-dlw** [comment]
I don't think this 'fix' is still necessary - I'm currently working in Sitecore 9.0.2 in combination with Glass 4.4 (I know, I should switch to 4.5 or even to 5), but Glass is actually breaking my querystring by decoding it. For example, I'm entering `q=key1%3Dvalue1%26key2%3Dvalue2` in the _general link field_'s internal link, and my link is referencing `targetpage?key2=value2`.

As I understand, this encoding by Sitecore was a specific ~~problem~~ behaviour change in late 7.2 and early 8.0 versions, but has been long time resolved/rolled back. And I can't validate this statement. What I can say is my value (above) is stored _untouched_ in the field's raw value. This contradicts earlier reports.
```xml
<link id="x" text="y" linktype="internal" querystring="q=key1%3Dvalue1%26key2%3Dvalue2" />
```

Of course, I understand that changing this behavior in Glass could be breaking for other people - although I have my doubts on whether it is still accurate. Regardless, I have found a workaround where I'm patching in a custom mapper as a replacement to  `SitecoreFieldLinkMapper`. This is OK for now, but I'd like to hear other people's opinion on this.
```csharp
dataMapperConfigFactory.Replace<SitecoreFieldLinkMapper, SitecoreFieldLinkMapperCustom>(
    () => new SitecoreFieldLinkMapperCustom());
```
Implementation:
```csharp
public class SitecoreFieldLinkMapperCustom : SitecoreFieldLinkMapper
{
    public override object GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
    {
        var stdValue = base.GetField(field, config, context);

        if (stdValue != null && stdValue is Link link)
        {
            var linkField = new LinkField(field);
            link.Query = linkField.QueryString;
        }

        return stdValue;
    }

    public override void SetField(Field field, object value, SitecoreFieldConfiguration config, SitecoreDataMappingContext context)
    {
        base.SetField(field, value, config, context);
        
        var link = value as Link;
        if (field == null) return;

        var linkField = new LinkField(field);
        if (link == null || link.Type == LinkType.NotSet) return;

        if (!link.Query.IsNullOrEmpty())
            linkField.QueryString = link.Query;
    }
}
```

**Comment by mikeedwards83** [comment]
@maximem-dlw I have moved this to a new ticket to better track it. https://github.com/mikeedwards83/Glass.Mapper/issues/362
