### ISSUE TITLE
Redirect with query string

### ISSUE THREAD

**Issue by abhishekkherde** [mikeedwards83/Glass.Mapper#225]
I have creted the custom http handler but when I tried to register it in sitecore.config it throws an error. I had read many blogs and found that castle windsor breaks it.

Is there any way to register custom http handler??

**Comment by mikeedwards83** [comment]
Hi, I this is a specific issue with Castle Windsor you will need to request instance from the Castle Windsor project. 

We have deprecated the use of Castle Windsor in V4.
