### ISSUE TITLE
Version count check not being evaluated before call to get version count in CreateType

### ISSUE THREAD

**Issue by jamesbwiseman** [mikeedwards83/Glass.Mapper#226]
In SitecoreService, the method:

**object CreateType(Type type, Item item, bool isLazy, bool inferType, Dictionary<string, object> parameters, params object[] constructorParameters)**

Calls item.Versions.Count before it checks to see whether version count has been disabled. This short circuit should be switched around for VersionCountDisabler to work properly.

**Comment by cardinal252** [comment]
This is now in the develop branch and will be released in the next version of Glass

**Comment by mikeedwards83** [comment]
Release in 4.2.0
