### ISSUE TITLE
Glass.Mapper stops working randomly

### ISSUE THREAD

**Issue by danjelv** [mikeedwards83/Glass.Mapper#227]
hey guys - using Glass with 8.1 here. occassionaly and randomly glass would stop mapping all properties and stop working until i restart the site. just happend and looking through the log file for any indiication of what the issue is but all i have are the below error. It happens randomly and there isn't a pattern - only a restart solves the issue it. not on the same page but once it happens on one nothing works anymore. 

On this particular environment no development changes have been done but content owners have been using it to populate the site.

Thanks
Dan

> Message: Page editting error. Could not find property Summary on type System.Object Source: Glass.Mapper at Glass.Mapper.Utilities.GetGlassProperty[T,K](Expression`1 field, Context context, T model) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Utilities.cs:line 471 at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T model, Object parameters, Context context, Database database, TextWriter writer) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\GlassHtml.cs:line 569 5240 14:12:36 ERROR Failed to render field Exception: Glass.Mapper.MapperException

**Comment by jvtroyen** [comment]
Same problem here. 
I use Glass.Mapper.Sc.4.0.11.63 and all my Sitecore-components are working, until suddenly "Could not find property Data1 on type System.Object". Recycling the apppool makes it work again. 
Repeating the exact same steps does not crash GlassMapper, until random hours, minutes or days later.
I can access Model.Data1, so it's not like the Model is empty or the wrong interface.

**Comment by cardinal252** [comment]
Are you guys using caching?

Do all glass mapped properties then fail or just the one ??

**Comment by danjelv** [comment]
I'm not using any caching at the moment - once it starts erroring all properties and models fail

**Comment by mikeedwards83** [comment]
Can you add the line of CSHTML that you are calling to make it editable?

**Comment by mikeedwards83** [comment]
Does it also always crash on the same call? Or do other Editable calls cause an issue?

**Comment by mikeedwards83** [comment]
Sorry for these questions being a bit all over the place but I am just brain dumping. 

Does this iss

**Comment by danjelv** [comment]
most of the time it's pretty straight forward such as: 

>                         @Html.Glass().Editable(Model, x => x.Quote)

we've got a few editable forms and they error in the same way

**Comment by mikeedwards83** [comment]
and there is nothing else to indicate a common reason? It seems like with the Glass Context is be dropped for some reason, or somehow the wrong model is being passed by the Razor view. Can you provide the full stack to the razor view?

**Comment by danjelv** [comment]
[OneColomnQuote.txt](https://github.com/mikeedwards83/Glass.Mapper/files/304840/OneColomnQuote.txt)

**Comment by mikeedwards83** [comment]
Can you send the models as well?

I want to see what properties are on the top level interface vs the inherited interfaces.

**Comment by danjelv** [comment]
sure:

>    
[SitecoreType(AutoMap = true, TemplateId = "")]
public interface    IOneColomnQuote : IBaseComponent
    {
        string Quote { get; set; }
        string QuoteColor { get; set; }
        string QuoteBy { get; set; }
        string QuoteByColor { get; set; }
        string Alignment { get; set; }
    }

The IBaseComponent is just a base class i'm using for all components build:
>     
[SitecoreType(AutoMap = true, TemplateId = "")]
    public interface IBaseComponent : ISitecoreItem
    {
        string AnchorName { get; set; }
        Image ComponentBackgroundImage { get; set; }
        string ComponentBackgroundColor { get; set; }
    }

**Comment by mikeedwards83** [comment]
thanks

**Comment by mikeedwards83** [comment]
Do you have any models with a property of type System.Object?

**Comment by mikeedwards83** [comment]
This route of the problem seems to be that System.Object gets mapped by Glass. This then mess up how Glass resolves proxy objects in the Page Editor. I suspect that this probably because somewhere there is a property that is of type object that is being auto-mapped.

I have made a fix that means that System.Object can not be loaded into a Glass Context.  This has been pushed as hot fix 4.1.1.

**Comment by jvtroyen** [comment]
I am now confronted with the following message. is this what was added in the hotfix?

Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object

Situation : 
- A controller that does NOT inherit from GlassController. 
- A view that does NOT specify a @model

I get the error above.

If I add @model Sitecore.Mvc.Presentation.RenderingModel, it does not complain about it, but I get errors further down the line.

**Comment by mikeedwards83** [comment]
@jvtroyen can you open these issues in a new issue and provide a example classes/views?

**Comment by argha007** [comment]
Hi Mike getting the issue with latest glass mapper update:
Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object   Glass.Mapper.Sc 4.3.4.197...

Please suggest... what I figure out is thast the field in the model is "object" type

**Comment by pberglund** [comment]
@argha007, i am as well, did you ever find a work around? I downgraded to Glass.Mapper.Sc 4.3.4.196 which is working in another project but not in my current one

**Comment by vrkmajeti** [comment]
Hi Mike, I am getting the same error with both versions 4.3.4.196 and 197. Can you please suggest the glass version that may not have this issue? Thanks
