### ISSUE TITLE
General Link field breaks code when contains %20s

### ISSUE THREAD

**Issue by woodsy1** [mikeedwards83/Glass.Mapper#230]
Hi,

I have encountered a problem with GlassMapper when using General Link fields.
If I use the "Email" of a general link field and then put a space in the "Subject" field of the email Sitecore generates a %20 to replace the space when generating the field value
The following would be generated if I was to put a space in the subject field...
`mailto:daniel.wood@rxpservices.com?subject=cool%20story`
This causes the component to break because the field returns null.

Now the interesting this is if I manually remove this %20 the page renders fine...
`mailto:daniel.wood@rxpservices.com?subject=cool story`

Also when I debug the code the model seems to return null when there is the %20 in the field. but the correct link without the %20.

I am using the following...	
Sitecore 8.1 initial release. Glass 4.0.5.54 

Any thoughts?

**Comment by mikeedwards83** [comment]
Hi

I don't understand the issue.

In my testing with the following field data:

    <link text='this is a test' linktype='mailto' style='' url='mailto:mike@test.com?subject=some%20subject'  title='' />

The following HTML is generated:

    <a href="mailto:mike@test.com?subject=some%20subject">this is a test</a>

This is what we would expect to be outputted. 

We also have an object when checking in debug mode. I don't think there is a problem with the mapper. I would check that your properties contain the virtual keyword.

Mike

**Comment by woodsy1** [comment]
Hey thanks for reply.
I am not quite sure what you mean by the properties contain the virtual keyword?

```
[SitecoreField("Link", FieldId = "916c157a-dfc4-4fd3-973f-9bfca003fd01", IsShared = false,IsUnversioned =false, UrlOptions = SitecoreInfoUrlOptions.Default | SitecoreInfoUrlOptions.SiteResolving )]
		global::Glass.Mapper.Sc.Fields.Link Link  {get; set;}
```

That is the Sitecore field in question
I get the output as you described but only once removing the %20 until then the code has a null in the Link field.

**Comment by woodsy1** [comment]
Can you please elaborate?

**Comment by woodsy1** [comment]
The link is stored in rendering params we are wondering if it is something to do with getRenderingParameters that is causing the issue?

**Comment by mikeedwards83** [comment]
Rendering parameters are stored by Sitecore as a query string in the Renderings field. This is the default behaviour of Sitecore. If you wanted to change this behaviour you can create a custom SitecoreFieldLinkMapper that strips out the %20 from the subject.
