### ISSUE TITLE
Enhancement suggestion: Config files in folder

### ISSUE THREAD

**Issue by kmac23va** [mikeedwards83/Glass.Mapper#231]
From a cleanup/maintenance standpoint, is there any thought to putting the Glass config files in App_Config/Include/Glass by default?

**Comment by cardinal252** [comment]
I think its more than likely only an issue of previous versions in the wild. If we did this now, then developers would have to clean up the old ones manually.

**Comment by mikeedwards83** [comment]
This would be my concern, those using older versions will need to update their config location, we also have to support back to 7.2 and I can't remember how folders are handled in that version.

**Comment by mikeedwards83** [comment]
Closing for  now but we will keep this in mind for a future release.
