### ISSUE TITLE
WFFM System.String[] as values

### ISSUE THREAD

**Issue by mluker** [mikeedwards83/Glass.Mapper#234]
Environment:
- Sitecore 8.0 Rev 3
- WFFM 2.4
- Glass.Mapper 4.0.11.63

I am having an issue with the above configuration. When I submit a WFFM form the data that is being saved is coming across as "System.String[]" rather than the actual text value. I opened a Sitecore ticket and they found it was because of Glass Mapper. If I disable glass (Glass.Mapper.Sc.config and Glass.Mapper.Sc.Start.config) the forms submit the correct values.

As a side note, I did apply the Sitecore patch which address this issue for collection types but that has nothing to do with Glass.

**Comment by mikeedwards83** [comment]
This was not a Glass issue but related to the WFFM model binder not being registered with the default MVC dependency resolver due to a conflict between the project IOC container and the one that WFFM tries to use.
