### ISSUE TITLE
Edit Mode Not Binding Properties

### ISSUE THREAD

**Issue by NickiSibbern** [mikeedwards83/Glass.Mapper#235]
Hi this issue relates to https://github.com/mikeedwards83/Glass.Mapper/issues/144 we are opening a new one as the old has not been reopened.

our setups is the following.
_TDS Generates some models to us that we use on a custom viewmodel. we are not using glassviews_

We are facing the same issue and what we have identified so far is the following:

- it only happens when using interfaces
- it only happens on non-debug configuration
- it only happens in page edit mode, not preview or normal mode.

**Stack trace**
`9304 11:51:12 ERROR Failed to render field
Exception: Glass.Mapper.MapperException
Message: Page editting error. Could not find property ListCategoryHeading on type System.Object
Source: Glass.Mapper
   at Glass.Mapper.Utilities.GetGlassProperty[T,K](Expression`1 field, Context context, T model)
   at Glass.Mapper.Sc.GlassHtml.MakeEditable[T](Expression`1 field, Expression`1 standardOutput, T model, Object parameters, Context context, Database database, TextWriter writer)`

**Comment by mikeedwards83** [comment]
Which version are you using and is the model an interface?

We released a hotfix recently that blocked System.Object being mapped as Glass type:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper/Context.cs#L173

We found that this sometimes caused problems when analysing proxy objects.

**Comment by NickiSibbern** [comment]
Hi, we are using 4.1.0.64 and yes the model is an interface

**Comment by mikeedwards83** [comment]
You will need to find properties that have the type Object and mark them with the SitecoreIgnore attribute.

**Comment by NickiSibbern** [comment]
Thanks, I will look into it, and report back

**Comment by mikeedwards83** [comment]
Please reopen if you still have an issue
