### ISSUE TITLE
Custom Field Mapper Issue

### ISSUE THREAD

**Issue by jthai-absolute** [mikeedwards83/Glass.Mapper#238]
Hi,

We recently added a new linkfield type that contains two new fields.  This new type is used by the sitecore internal link type.  

 public class LinkEx : Link
    {
        public string DataScrollTo { get; set; }
        public string DataOffset { get; set; }
    }

To make this new link type work with glassmapper we extended off AbstractSitecoreFieldMapper and I created a new SitecoreFieldLinkExMapper class.  This class will help map the old link field to the new linkex type.

Currently, this works great but on Sitecore 7.2 and glassmapper version 4.0.3.5.1.  However, we're in the process of upgrading to Sitecore 8.1 using glassmapper binaries version 4.1.0.64 and the field mapper class no longer works.  

It looks like SitecoreFieldLinkExMapper.GetField and SitecoreFieldLinkExMapper.SetField functions aren't being called after the upgrade.

Here is a link I used to write this new mapper class.
 - https://sitecorejunkie.com/2015/10/17/one-approach-to-rendering-a-custom-general-link-field-attribute-in-a-sitecore-mvc-view-rendering-via-glass-mapper/

[glassmapper-files.zip](https://github.com/mikeedwards83/Glass.Mapper/files/372295/glassmapper-files.zip)

Any ideas?

**Comment by mikeedwards83** [comment]
Hi 

Your data mapper is being added as the last data mapper in the collection:

    dependencyResolver.DataMapperFactory
        .Insert(dependencyResolver.DataMapperFactory.GetItems().Count()-1, () => new SitecoreFieldLinkExMapper());

You need to insert it as the first:
  dependencyResolver.DataMapperFactory .First(() => new SitecoreFieldLinkExMapper());

Mike
