### ISSUE TITLE
BeginEditFrame causes error with multi-language content

### ISSUE THREAD

**Issue by kmac23va** [mikeedwards83/Glass.Mapper#243]
We are using v4.2.0.184 on Sitecore 8.1 update 2. We are working on implementing multi-language support, but we are hitting an error on pages using BeginEditFrame on a view rendering with GlassView. The English version of the page is fine, and if we manually type in a culture that doesn't match one in the list, that works as well (it defaults to English - we thought at first one scenario was working but another wasn't). 

If we go to another language, however, the page throws an "object reference not set to an instance of an object" message. This doesn't happen on pages without an edit frame, and it happens whether the language is explicitly set on an item with a version or whether it is using language fallback. We're trying to look at the non-Glass way of doing this to see if it's a possible Sitecore bug, but amusingly the first article on edit frames says to use Glass.

Thanks for any help.

**Comment by kmac23va** [comment]
I don't think this is a Glass issue after all but an issue with data being null, after looking closer into it.

**Comment by mikeedwards83** [comment]
Do you have the stack trace? Maybe we can handle more gracefully

**Comment by kmac23va** [comment]
I don't think it's really a systemic issue. Our German item, for example, had a link field using the Glass Link type, but in German it was left empty (I think the fallback wasn't fully enabled through site config either). So when it hit item.Link.Url, item.Link being null threw the error. It wasn't tied to the edit frame...the error showing was odd because it highlighted an open brace on the using BeginEditFrame, and not on the line itself.

I dumped the existing German items so fallback would take over and it worked fine. If the field was filed in, I'm pretty sure we wouldn't have seen an issue at all. I'd tried it in another project with an edit frame that was fine.

Probably the only way to add graceful handling in our case would be if a Link field was null (or an Image field), and you directly call item.Link.Url, the Url field returns an empty string instead of the whole thing being null. Not sure if that's possible though.

Thanks, Mike!
