### ISSUE TITLE
Could not resolve type name: Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc

### ISSUE THREAD

**Issue by Secuda** [mikeedwards83/Glass.Mapper#244]
Latest Glass.Mapper.Sc installed via NuGet (4.2.1.88).
Latest Glass.Mapper.Sc.Mvc installed via NuGet (3.3.1.48)

The attached YSOD is displayed after installation.

![image](https://cloud.githubusercontent.com/assets/3658456/18664269/c6464d48-7f19-11e6-829f-07af4a39120f.png)

**Comment by mikeedwards83** [comment]
Hi 

You should not have the Glass.Mapper.Sc.Mvc nuget installed. The MVC assembly is now shipped with Glass.Mapper.Sc V4 in a single nuget package.

The V3 MVC assembly is still listed to support some third party solutions that use this particular assembly.

See the tutorial 1.

http://www.glass.lu/Mapper/Sc/Tutorials/Tutorial1


Thanks

Mike
