### ISSUE TITLE
Erorrs on Sitecore 8.2

### ISSUE THREAD

**Issue by adriancosma** [mikeedwards83/Glass.Mapper#245]
I am getting strange errors after installing it from nuget on a Sitecore 8.2 solution. Checked assemblies to be latest version and everything seems to be fine, except I can't get into sitecore at all as Glass is crashing.

http://sitecore.stackexchange.com/questions/125/glass-mapper-error-on-sitecore-8-2

Packages:
 < package id="Glass.Mapper.Sc" version="4.2.1.188" targetFramework="net452" / >
  < package id="Glass.Mapper.Sc.Core" version="4.2.1.188" targetFramework="net452" / >
  < package id="Glass.Mapper.Sc.Mvc-5" version="3.3.1.48" targetFramework="net452" / >

**Comment by mikeedwards83** [comment]
Hi 

Please see this issue, I think you have the same problem:

https://github.com/mikeedwards83/Glass.Mapper/issues/244

Mike
