### ISSUE TITLE
MethodAccessException with SC v8.2 and GlassMapper v4.2.1.188

### ISSUE THREAD

**Issue by clbowens** [mikeedwards83/Glass.Mapper#246]
This is the whole stack trace from the yellow screen of death.  This happens when I log into the SC launchpad, and also on the Page Editor.

[MethodAccessException: Attempt by method 'Glass.Mapper.Sc.Utilities.get_IsPageEditor()' to access method 'Sitecore.Context+PageMode.get_IsPageEditor()' failed.]
   Glass.Mapper.Sc.SitecoreService.Initiate(IDependencyResolver resolver) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:111
   Glass.Mapper.Sc.IoC.SitecoreContextFactory.GetSitecoreContext(Context context) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\IoC\SitecoreContextFactory.cs:63
   Glass.Mapper.Sc.Pipelines.Response.GetModelFromView.Process(GetModelArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc.Mvc\Pipelines\Response\GetModelFromView.cs:67
   (Object , Object[] ) +74
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +193
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args, Func`2 resultGetter) +161
   Sitecore.Mvc.Presentation.Rendering.GetModel() +275
   Sitecore.Mvc.Presentation.Rendering.get_Model() +30
   Sitecore.Mvc.Extensions.ObjectExtensions.ValueOrDefault(T source, Func`2 resultGetter) +57
   Sitecore.Mvc.Presentation.ViewRenderer.get_Model() +144
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +255

[InvalidOperationException: Error while rendering view: '/sitecore/shell/client/Speak/Layouts/Layouts/Speak-Layout.cshtml'.
]
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +826
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) +30
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) +75
   (Object , Object[] ) +74
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +193
   Sitecore.Mvc.Presentation.RenderingView.Render(ViewContext viewContext, TextWriter writer) +302
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +90
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +833
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +37

**Comment by adriancosma** [comment]
Can you try to delete your packages entries, dlls, configs, and reinstall from nuget the Glass.Mapper.SC (without any Glass.Mapper.SC.Mvc). I had the same problem after I did an upgrade from 8.1 to 8.2 and the dlls weren't updated correctly. After I clean installed Glass again it worked fine and didn't get any more errors.

**Comment by clbowens** [comment]
I already tried that with the same results.

**Comment by mikeedwards83** [comment]
Can you tell me all the nuget packages you have installed?

Also check that your VS projects are referencing the Glass.Mapper.Sc and Glass.Mapper.Sc.Mvc DLLs in the  100 directory.

**Comment by clbowens** [comment]
Glass.Mapper.Sc is from the 100 directory.  Glass.Mapper.Sc.Mvc is from the Mvc52 directory.  Glass.Mapper is from the net45 directory.

Here are all my packages installed:

<packages>
  <package id="Castle.Core" version="3.3.3" targetFramework="net452" />
  <package id="Glass.Mapper.Sc" version="4.2.1.188" targetFramework="net452" />
  <package id="Glass.Mapper.Sc.Core" version="4.2.1.188" targetFramework="net452" />
  <package id="HtmlAgilityPack" version="1.4.6" targetFramework="net452" />
  <package id="Lucene.Net" version="3.0.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.Net.Compilers" version="1.3.2" targetFramework="net452" developmentDependency="true" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net452" />
  <package id="RazorGenerator.Mvc" version="2.4.2" targetFramework="net452" />
  <package id="SharpZipLib" version="0.86.0" targetFramework="net452" />
  <package id="Sitecore.Kernel" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="Sitecore.Logging" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="Sitecore.Logging.Client" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="Sitecore.Mvc" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="Sitecore.NVelocity" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="Sitecore.Zip" version="8.2.160729" targetFramework="net452" developmentDependency="true" />
  <package id="System.Collections" version="4.0.11" targetFramework="net452" />
  <package id="System.Collections.Concurrent" version="4.0.12" targetFramework="net452" />
  <package id="System.ComponentModel" version="4.0.1" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net452" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net452" />
  <package id="System.Linq" version="4.1.0" targetFramework="net452" />
  <package id="System.Linq.Expressions" version="4.1.0" targetFramework="net452" />
  <package id="System.Reflection" version="4.1.0" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net452" />
  <package id="System.Threading" version="4.0.11" targetFramework="net452" />
  <package id="System.Threading.Tasks" version="4.0.11" targetFramework="net452" />
  <package id="WebActivatorEx" version="2.0.3" targetFramework="net452" />
</packages>

**Comment by clbowens** [comment]
Also to note, a coworker has this same project deployed locally on his machine and it works fine.

**Comment by mikeedwards83** [comment]
Can you verify the Glass assemblies that are getting deployed to your website bin folder. It could be that the updated Glass.Mapper.Sc.Mvc DLL is not being copied.

Try manually copying these from the packages folder to the bin folder.

**Comment by clbowens** [comment]
I manually copied the corresponding DLLs.  Same error.

**Comment by mikeedwards83** [comment]
This is a long shot, but also clear you temporary internet files, it could also be cached there.

**Comment by clbowens** [comment]
I finally resolved my issue.  I installed .NET 4.6.2 and that seems to have fixed it.

Thanks anyway for all the feedback.
