### ISSUE TITLE
Language Fallback issue with Linked Properties

### ISSUE THREAD

**Issue by aiswebmaster** [mikeedwards83/Glass.Mapper#252]
I first wrote about this issue here: http://sitecore.stackexchange.com/questions/2139/language-fallback-with-glass-mapper

Essentially when I have a Property, instead of using the Context.Language, it's using the Item Language for the item the model represents.

**Comment by mikeedwards83** [comment]
Hi

I have tested in 8.1 using item level fallback and it works as expected. 

This is my test:

        public string Index()
        {

            ISitecoreContext context =new SitecoreContext();

            var languageFr = Language.Parse("fr-FR");
            var languageEn = Language.Parse("en");

            var parent = context.GetItem<Stub>("/sitecore/content/Home/Base", languageFr);

            var related = parent.MultiList.First();

            if (parent.Language != languageFr)
            {
                throw new Exception("Wrong parent language");
            }
            if (parent.OriginalLanguage != languageEn)
            {
                throw new Exception("Wrong parent original language");
            }

            if (related.Language != languageFr)
            {
                throw new Exception("Wrong related language");
            }
            if (related.OriginalLanguage != languageFr)
            {
                throw new Exception("Wrong related original language");
            }

            return parent.Title + related.Title;
        }
