### ISSUE TITLE
Performance during ribbon build Glass.Mapper.Sc.Pipelines.Response.GetModelFromView

### ISSUE THREAD

**Issue by a3codeDA** [mikeedwards83/Glass.Mapper#253]
Hi,
 We have some performance issues during Experience Editor loading on Sitecore 8.1
 I asked about possible issue sitecore support and I got answer. that possible problem is Glass.Mapper.Sc.Pipelines.Response.GetModelFromView:
 

> The ribbon controls should be rendered in the context of "shell" site, and basically, your custom processors should not be involved into the rendering of the ribbon. As far as I understand the method GetModelFromView.IsValidForProcessing is designed to determine whether a particular rendering shoudl be handled by the processor. From this point, I'd suggest you extending the method with one more additional check to filter out any "shell" requests, for example:

`protected virtual bool IsValidForProcessing(GetModelArgs args)
        {
            if (Sitecore.Context.Site.Name == "shell")
            {
                return false;
            }
            if (args.Result != null)
            {
                return false;
            }
            if (!String.IsNullOrEmpty(args.Rendering.RenderingItem.InnerItem["Model"]))
            {
                return false;
            }
            return args.Rendering.RenderingType == "Layout" ||
                   args.Rendering.RenderingType == "View" ||
                   args.Rendering.RenderingType == "r" ||
                   args.Rendering.RenderingType == String.Empty;
        }`
originally
` if (Sitecore.Context.Site.Name == "shell")
            {
                return false;
            }`
is missed at Glass 
Could it be a real problem ?

**Comment by mikeedwards83** [comment]
This is something new and we aren't aware of an issue. 

What sort of impact is it having on the page load speed?

**Comment by mikeedwards83** [comment]
I confirm that there seems to be an issue and I am investigating a fix.

**Comment by mikeedwards83** [comment]
Detailed fix in Release 4.3 http://www.glass.lu/Blog/Release4-3

**Comment by a3codeDA** [comment]
Thanks @mikeedwards83 good job !
