### ISSUE TITLE
Glassmapper breaking on EXM 3.4 install due to precompiled views

### ISSUE THREAD

**Issue by trowpa** [mikeedwards83/Glass.Mapper#255]
Hello - 

Installed EXM 3.4 - and received errors indicating Sitecore was unable to find a cshtml for EXM dashboard.  Turns out, contrary to 3.3 EXM no longer includes phsyical views in the package - they are now compiled.

Found that glassmapper's pipeline for mvc.getModel has code to handle precompiled views with  BuildManager.GetCompiledType(path);  which throws an exception.  

Workaround for now to bypass this error is to override this with my own getModel method which checks for physical file.  But a better solution should be put in place that handles EXMs precompiled views so glass mapper can be used with them and extract the model from them.

 protected override Type GetModel(GetModelArgs args, string path)
        {
            if (File.Exists(path))
            {
                return base.GetModel(args, path);
            }
            else
            {
                  return typeof(NullModel);
            }
        }

**Comment by mikeedwards83** [comment]
@trowpa  I will release a hotfix with this change as a temporary fix while we look into a more permanent solution.

**Comment by mikeedwards83** [comment]
Pushed: https://github.com/mikeedwards83/Glass.Mapper/commit/42f5624780abc4fc33897cceffea932d86c0a4e4

**Comment by mikeedwards83** [comment]
https://www.nuget.org/packages/Glass.Mapper.Sc/4.2.1.190

**Comment by trowpa** [comment]
Thanks! I've replaced my patch with your hotfix and it seems to be working fine.

**Comment by mikeedwards83** [comment]
Ready in 4.3, added compiled view support as well if required http://www.glass.lu/Blog/Release4-3
