### ISSUE TITLE
SitecoreContext.Map<T>(model) does not resolve complex types in 4.2 same way it did in 4.0

### ISSUE THREAD

**Issue by TimEllison** [mikeedwards83/Glass.Mapper#259]
We use an abstract search repository<T> to perform location-specific searches. The model is as follows:

```
[SitecoreType(TemplateId="...")]
public class Blah : ItemBase
 {
        [SitecoreField("Year")]
        public virtual string Year { get; set; }

        [SitecoreField("Vehicle Make")]
        public virtual VehicleMake Make {get;set;}


        [IndexField("m_code")]
        [SitecoreField("M Code")]
        public virtual int Mcode { get; set; }
}

```
We only store the mcode field in the custom index and rely on Map() to map the other fields.   Item base has an ItemURI defined.  Sitecore ContentSearch returns the correct item however, since upgrading to 4.2 we are not seeing "VehicleMake" class get mapped.

Is this known issue or a breaking change and if so, what steps are needed to resolve?

It might help if I actually posted our abstract search repository code... :)

```
public T GetItem(Expression<Func<T, bool>> expression)
        {
            var tType = typeof (T).FullName;
            using (var context = GetSearchContext())
            {
                var model = context.GetQueryable<T>().Where(expression).FirstOrDefault();
                if (model != null)
                {
                    SitecoreContext.Map(model);
                }
                return model;
            }
        }


```
Thanks!

**Comment by mikeedwards83** [comment]
Hi Tim

I have created the following unit test and it  succeeds https://github.com/mikeedwards83/Glass.Mapper/commit/822deb48bf5dfbee8de5ba05ca0c500b16c6e11d 

Could it be a problem with the ItemBase class?

**Comment by TimEllison** [comment]
I doubt the item base is the issue only because this base class has been in operation for over a year without the issue I reported.

I'm wondering if it's possible that the manner in which I'm constructing the context might be the culprit.  Our abstract repository news up a Sitecore context (transient) using the database overloaded constructor.  Let me test that and I'll get back to you.  Thank you for looking into this.

**Comment by TimEllison** [comment]
@mikeedwards83 - you can close this one.  Following your unit test (using SitecoreService instead of SitecoreContext) and adjusting the load lazy settings on the complex type resolved the issue.

**Comment by TimEllison** [comment]
@mikeedwards83 - you can close this one.  I switched to SitecoreService as in the unit test and items are mapping now.
