### ISSUE TITLE
InferType not working?

### ISSUE THREAD

**Issue by nbenninghoff** [mikeedwards83/Glass.Mapper#260]
https://github.com/mikeedwards83/Glass.Mapper/issues/209

Having the same issue as above.  I cant seem to get this to work correctly.

The type coming back is a proxy item for the base class.  I am loading the types correctly on startup.  I tried AttributeConfigurationLoader first and made sure there was only one type per template ID.
I also tried manually loading just the types i want like the end of this example http://blog.krusen.dk/using-infertype-with-glass-mapper-for-sitecore/

No luck

**Comment by mikeedwards83** [comment]
Can you provide more information, including your models and IDs

**Comment by nbenninghoff** [comment]
Yes one moment thanks

**Comment by nbenninghoff** [comment]
Im using tds codegen, here is the basic sructure.

`[SitecoreType(TemplateId=ILocationConstants.TemplateIdString, Cachable=false)] 
public partial class Location  : GlassBase, ILocation 
{
	[SitecoreField(FieldName = ILocationConstants.StructuresFieldName, Setting =  SitecoreFieldSettings.InferType)]
	public virtual IEnumerable<GlassModels.GlassBase> Structures  {get; set;}
}



[SitecoreType(TemplateId=IATMConstants.TemplateIdString, Cachable=false)] 
public partial class ATM  : GlassBase, IATM 
{
	properties...
}


[SitecoreType(TemplateId=IBranchConstants.TemplateIdString, Cachable=false)] 
public partial class Branch  : GlassBase, IBranch 
{
	properties...
}`

I'm going to attempt to create some simple models manually to test

**Comment by nbenninghoff** [comment]
I tried with some simpler (non tds generated) classes that I created manually, still not working quite right.

The Structures field is a collection of Proxy items, proxy atm and proxy branch

```
    public class MyLocation
    {
        public virtual Guid Id { get; set; }
        public virtual string Url { get; set; }

        [SitecoreField(FieldName = MBFinancial.Website.Web.GlassModels.sitecore.templates.User_Defined.Main.Locations.ILocationConstants.StructuresFieldName, Setting =  SitecoreFieldSettings.InferType)]
		public IEnumerable<MyStructure> Structures  {get; set;}
    }

    public class MyStructure
    {
        public virtual Guid Id { get; set; }
        public virtual string Url { get; set; }
    }
    
    [SitecoreType(TemplateId = "{7b85d4b1-f9d2-4e44-87f9-bc69cfaf485e}", AutoMap = true)]
    public class MyBranch : MyStructure
    {

    }
    
    [SitecoreType(TemplateId = "{9c424c81-e791-4a34-a9dd-c62c82624bf8}", AutoMap = true)]
    public class MyAtm : MyStructure
    {

    }
```

**Comment by nbenninghoff** [comment]
I believe im calling GetItem correctly to infer types
sitecoreContext.GetItem<MyLocation>(someId, someLanguage, inferType:true)

**Comment by nbenninghoff** [comment]
Am I confused, is it expected behavior that the collection of Inferred Types is made up of proxy items?
My issue is that when I serialize these to Json, the serialized proxy items are not what I expect.

**Comment by Glass-Build-Github** [comment]
Proxies are used for lazy loading. Set lazy loading to false to get non
proxies.

**Comment by nbenninghoff** [comment]
Yes! this is what I was missing.  Thanks you!
