### ISSUE TITLE
“The method or operation is not implemented” error on SitecoreIgnore

### ISSUE THREAD

**Issue by jawahar-r** [mikeedwards83/Glass.Mapper#261]
I recently upgraded Sitecore from 8.1. to 8.2.1. The project uses TDS - the models are generated using the code generation template. A few of the properties are marked as SitecoreIgnore.

As part of the upgrade, I had to update the Glass Mapper from 4.1.1.66 to 4.2.1.190 version.

When I launched the website after upgrade, I am getting this error:

**[NotImplementedException: The method or operation is not implemented.]** Glass.Mapper.Sc.DataMappers.SitecoreIgnoreMapper.MapToProperty(AbstractDataMappingContext mappingContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\SitecoreIgnoreMapper.cs:70 Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.LoadValue(AbstractPropertyConfiguration propertyConfiguration) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateInterface\InterfacePropertyInterceptor.cs:128 Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor.LoadAllValues() in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateInterface\InterfacePropertyInterceptor.cs:141 Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.InterfacePropertyInterceptor..ctor(ObjectConstructionArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateInterface\InterfacePropertyInterceptor.cs:63 Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.CreateInterfaceTask.Execute(ObjectConstructionArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateInterface\CreateInterfaceTask.cs:54 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:77 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.Pipelines.<>c__DisplayClass3.b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:82 Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\AbstractService.cs:139 Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary 2 parameters, Object[] constructorParameters) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\SitecoreService.cs:506 Glass.Mapper.Sc.Pipelines.Response.GetModelFromView.Process(GetModelArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc.Mvc\Pipelines\Response\GetModelFromView.cs:89 (Object , Object[] ) +74 Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484 Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22 Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +193 Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args, Func`2 resultGetter) +161 Sitecore.Mvc.Presentation.Rendering.GetModel() +275 Sitecore.Mvc.Presentation.Rendering.get_Model() +30 Sitecore.Mvc.Extensions.ObjectExtensions.ValueOrDefault(T source, Func 2 resultGetter) +57 Sitecore.Mvc.Presentation.ViewRenderer.get_Model() +144 Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +255

I looked at the source of the glass mapper; it showed that there are some recent changes to constructor of **InterfacePropertyInterceptor** class in the namespace Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateInterface.

```
//if lazy loading diabled load all values now
            if (!args.AbstractTypeCreationContext.IsLazy)
            {
                LoadAllValues();
            }
```
Inside this class, eventually MapToProperty method is called for glass mapper attribute classes. For SitecoreIgnore attribute, the corresponding class is **SitecoreIgnoreMapper** which throws not implemented exception in MapToProperty method.

As a workaround, I have removed the SitecoreIgnore attribute on the properties. Is there something I am missing?

**Comment by mikeedwards83** [comment]
Fixed ready in 4.3
