### ISSUE TITLE
I am trying to upgrade to the latest GlassMapper and having issues.

### ISSUE THREAD

**Issue by eat-sleep-code** [mikeedwards83/Glass.Mapper#263]
I read a note that CastleWindsor was eventually being deprecated.   

I removed it from my project and upgraded to the latest GlassMapper prerelease assemblies.   

Now I get the following errors:

- The type or namespace name 'Mvc' does not exist in the namespace 'Glass.Mapper.Sc.Web' (are you missing an assembly reference?)   _(this occurs on my **using Glass.Mapper.Sc.Web.Mvc;**)_
- The type or namespace name 'GlassController' could not be found (are you missing a using directive or an assembly reference?) _(this occurs on my **public class SearchController : GlassController**)_

**Comment by eat-sleep-code** [comment]
Nevermind, somehow the Glass.Mapper.Sc.Mvc-5 package had also gotten uninstalled.

**Comment by eat-sleep-code** [comment]
I attempted to install Glass.Mapper.Sc.Mvc-5 which resolved the above two issues, but then I get:

Could not resolve type name: Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc (method: Sitecore.Configuration.DefaultFactory.CreateFromTypeName(XmlNode configNode, String[] parameters, Boolean assert)).

**Comment by eat-sleep-code** [comment]
It is a View Rendering.

**Comment by TimEllison** [comment]
Just eliminating the obvious...

If you run /sitecore/admin/showconfig.aspx, look for mvc.getModel pipeline.  You should see GetModel and GetModelFromView preceding Sitecore's GetFromItem pipeline processor.  If they aren't there it could explain why you're getting a "broken links" equivalent exception assuming you've verified that you published the data source item.  One other thing, does your view directive indicate @inherits GlassView<YourModel>  ?

**Comment by eat-sleep-code** [comment]
This is what my showconfig says, doesn't appear it has GetModel or GetModelFromView.   

```
<mvc.getModel patch:source="Glass.Mapper.Sc.config">
<processor type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc"/>
<processor type="Glass.Mapper.Sc.Pipelines.Response.GetModel, Glass.Mapper.Sc.Mvc" patch:source="Glass.Mapper.Sc.Mvc.Config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.GetFromProperty, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.GetFromLayout, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.GetFromRenderingItem, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.CreateDefaultRenderingModel, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
<processor type="Sitecore.Mvc.Pipelines.Response.GetModel.InitializeModel, Sitecore.Mvc" patch:source="Sitecore.Mvc.config"/>
</mvc.getModel>
```

**Comment by TimEllison** [comment]
The first 2 pipeline processors are what I expect to see as they are both Glass' processors.  What version did you upgrade to?

**Comment by mikeedwards83** [comment]
This is normally the result of the data source item missing or not available in the requested language. Normally Glass returns null in this scenario however Sitecore returns a model regardless.
