### ISSUE TITLE
The type Sitecore.Collections.ChildList does not contain any generic arguments

### ISSUE THREAD

**Issue by shindai** [mikeedwards83/Glass.Mapper#264]
Hi,

I updated my 8.2u1 Sitecore Application to the newest stable version (Glass.Mapper.Sc 4.2.1.190) and now I always get the following error when I try to insert a model with an item as parent
(_sitecoreContext.Create(parent, toInsert, updateStatistics, silent); //reproducable call at the bottom):

The type Sitecore.Collections.ChildList does not contain any generic arguments

`[MapperException: The type Sitecore.Collections.ChildList does not contain any generic arguments]
   Glass.Mapper.Utilities.GetGenericArgument(Type type) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Utilities.cs:284
   Glass.Mapper.Sc.DataMappers.SitecoreChildrenMapper.Setup(DataMapperResolverArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\SitecoreChildrenMapper.cs:96
   Glass.Mapper.Pipelines.DataMapperResolver.Tasks.DataMapperStandardResolverTask.Execute(DataMapperResolverArgs args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\DataMapperResolver\Tasks\DataMapperStandardResolverTask.cs:44
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Pipelines\AbstractPipelineRunner.cs:77
   Glass.Mapper.Context.ProcessProperties(IEnumerable1 properties) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Context.cs:213
   Glass.Mapper.Context.Load(IConfigurationLoader[] loaders) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Context.cs:184
   Glass.Mapper.Context.GetTypeConfigurationFromType(Type type, Boolean doNotLoad, Boolean checkBase) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper\Context.cs:273
   ASP.layouts_sample_layout_aspx.__Rendermainform(HtmlTextWriter __w, Control parameterContainer) +248
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +263
   System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) +11828389
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +47
   Sitecore.Web.FormAdapter.Render(HtmlTextWriter writer) +76
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +116
   System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) +50
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +160
   System.Web.UI.Page.Render(HtmlTextWriter writer) +39
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +80
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +8921`

and it seems that the following commit:
https://github.com/mikeedwards83/Glass.Mapper/commit/42dfd249373d25c00bdfa484a96cfcc9a7afeada#diff-034eed7d2a29625b423c0fb5a59bd211
and the change to SitecoreChildrenMapper causes the error.

Its reproduceable in a new installed sitecore instance installed with sim tool (Sitecore 8.1, because of the old glass version which works) with GlassMapper.Sc 4.1.0.64 (4.1.0.63 works) with the following line in the code before of Sample Layout.aspx:
`<%
 var test = new Glass.Mapper.Sc.SitecoreContext().GlassContext.GetTypeConfiguration<Glass.Mapper.Sc.Configuration.SitecoreTypeConfiguration>(Sitecore.Context.Item);   
%>`

I don't know the reason, why the SitecoreChildrenMapper wants to get generic parameters of a non generic Type (Childlist). Maybe somebody know how to fix that correctly.

**Comment by mikeedwards83** [comment]
Glass does not support the ChildList type out of the box. You can support it by create a custom data mapper.

**Comment by shindai** [comment]
```
**Sitecore.Data.Items.Item parent;** //in my code it is a bucket folder, therefore there is no model for it
**SomeModel newItem;**
[public T Create<T, TK>(**TK parent**, **T newItem**, bool updateStatistics = true, bool silent = false)](https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/SitecoreService.cs#L176)
```

This code **works** until GlassMapper.Sc 4.1.0.63. But after that the error above is thrown.
I saw in the code, that there is a mapping configuration for Sitecore.Data.Items.Item,
and that the code wants to map some properties [(also "children")](https://github.com/mikeedwards83/Glass.Mapper/blob/8f4506a14b7c1cd3f9179ed6459741c73fa7ea1a/Source/Glass.Mapper.Sc/Configuration/SitecoreTypeConfiguration.cs#L325), but that fails now.

I dont want the children to be mapped correctly, i just want to insert an model below with a sitecore item as parent.

There is a bug in the class SitecoreChildrenMapper, which should obviously map the Children-Property of Sitecore.Data.Items.Item. Because it fails to handle it correctly now.
The class SitecoreChildrenMapper would work with a generic property (ex IEnumerable<SomeModel>) but not with item.Children. But the glassmapper mapping-workflow adds the "SitecoreChildrenConfiguration" for the ChildList Type and SitecoreChildrenMapper starts to map this.
Maybe thats the problem ... I don't know.
