### ISSUE TITLE
IObjectConstructionTask in GlassMapper 4.3.0.280?

### ISSUE THREAD

**Issue by eat-sleep-code** [mikeedwards83/Glass.Mapper#267]
In Sitecore 8.1 with an older version of GlassMapper, I had implemented the following code to implement Patial Language Fallback:

https://community.sitecore.net/technical_blogs/b/elizabeth_spranzani/posts/partial-language-fallback-and-glass-mapper-v3

Since upgrading to Sitecore 8.2 Update 1 and GlassMapper 4.3.0.280, I get _The type or namespace name 'IObjectConstructionTask' could not be found (are you missing a using directive or an assembly reference?)_	

Question 1: Is partial language fallback now supported out of the box?
Question 2: If not, what code would replace the IObjectConstructionTask

**Comment by Glass-Build-Github** [comment]
Please see 4.3 release notes. We have had a major refactor of how we use
pipelines. You will need to modify any custom pipeline tasks to work with
the new style.

**Comment by eat-sleep-code** [comment]
Where do I find these release notes?

**Comment by cardinal252** [comment]
All release notes are found here:

http://www.glass.lu/Mapper/Sc/Releases

**Comment by eat-sleep-code** [comment]
Thanks!   Quick question, before we had some logic similar to the following: 

```
if (scContext.Item == null)
{
	args.AbortPipeline();
	return;
}
```

It appears that AbortPipeline is no longer available.   Is it no longer needed due to the change in the way pipelines are handled or is there another method.

**Comment by jwsadler** [comment]
@cardinal252 any chance you could publish the notes here.  I'm getting an error when trying to view.

**Comment by eat-sleep-code** [comment]
@jwsadler Seems their website is having a few days off: http://www.glass.lu/

Here is the StackExchange thread that seems to have answered my questions: http://sitecore.stackexchange.com/questions/3568/abortpipeline-in-glassmapper-4-3-0-280

**Comment by samirindusa** [comment]
In Sitecore 8.1 we have used glass mapper 3.0.10 version and now we have upgraded sitecore 8.2 version and also we have upgraded glass mapper version 4.3.2 latest but we have getting error below error in solution. so please suggest how to modify our code for **GlassMapperScRazor.cs** file.

![image](https://cloud.githubusercontent.com/assets/24971972/21740311/8bbf3d4c-d4dc-11e6-89ba-5c6bc906fd67.png)

We read article of glass mapper latest version of 8.2 and we know that castle Windsor and razor are removed from glass mapper so please suggest changes as per glass mapper latest version.

**Comment by Glass-Build-Github** [comment]
You do not need this file. It can be deleted if you are using standard MVC
razor views.

**Comment by samirindusa** [comment]
We have deleted GlassMapperScRazor.cs file and build solution successfully but we have getting below error.
![1-7-2017 3-45-43 pm](https://cloud.githubusercontent.com/assets/24971972/21741045/f87039e6-d4f0-11e6-867c-a37fa72ba18d.png)
 
please help to resolve this issue.

**Comment by Glass-Build-Github** [comment]
Have to deleted all the old files associated to the Glass razor nuget?

**Comment by samirindusa** [comment]
Yes, we have deleted all the old files which are associated to Glass razor. Please refer attached log file.
[log.20170107.155814.txt](https://github.com/mikeedwards83/Glass.Mapper/files/691426/log.20170107.155814.txt)

**Comment by mikeedwards83** [comment]
Without seeing your code base I don't think we can help. We offer consultancy to help with this type of issue.

**Comment by samirindusa** [comment]
Mike,

Please let us know the consultancy fees and details regarding below email issue.

Thanks,
Samir Parmar
Software Engineer
