### ISSUE TITLE
Saving object with property of type Item throws exception in Sitecore 8.2

### ISSUE THREAD

**Issue by Krusen** [mikeedwards83/Glass.Mapper#270]
Sitecore 8.2 has made some changes to the `Item` class which causes errors when saving an object with a property of type `Item`.

```
The type Sitecore.Collections.ChildList does not contain any generic arguments.
```

I believe this happens because `SitecoreFieldTypeMapper` is being used for the property and `Item.Children` is now `virtual` and is being auto-mapped.

**Comment by mikeedwards83** [comment]
Can you give me an example model?

**Comment by Krusen** [comment]
I'm not sure what you are asking for?

This happen when mapping a reference field to a property of type `Sitecore.Data.Items.Item`. And it is fixed by implementing a custom field mapper as I've done in PR #271.

**Comment by JuanPabloAlbuja** [comment]
Hi guys, I am experimenting the same issue using with Sitecore 8.2 and GlassMapper 4.3.4.196. Is there a fix for this?

**Comment by mikeedwards83** [comment]
@JuanPabloAlbuja  can you provide any more info? it should be fixed in that release.

**Comment by vrkmajeti** [comment]
Hi, I am experimenting the same issue using with Sitecore 8.2 update 5 and GlassMapper (4.4.0.199 or latest 4.4.1.331-beta). Is there a fix for this? Dependency resolver used is the sitecore 8.2 default DI (i.e. microsoft DI)

**Comment by ravikhapate** [comment]
Hello,
I am facing the same issue. Getting the exception as "Failed to find configuration for parent item type Sitecore.Data.Items.Item". Is there a beta release solution for the same?

**Comment by Antonytm** [comment]
Same issue with Sitecore 7.2 with 4.4.0.199
