### ISSUE TITLE
Utilities.ConvertAttributes fails if an attribute values contains curly brackets

### ISSUE THREAD

**Issue by yannisgu** [mikeedwards83/Glass.Mapper#272]
Calling `Utilities.ConvertAttributes(new Dictionary<string, string>() { {"test", test {hello}" }}, "'") `  will throw a FormatException:

```
[FormatException: Input string was not in a correct format.]
   System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) +13747547
   System.Text.StringBuilder.AppendFormat(String format, Object[] args) +116
   Glass.Mapper.Sc.Utilities.ConvertAttributes(SafeDictionary`1 attributes, String quotationMark) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\Utilities.cs:97
```

The problem is that Utilities.ConvertAttributes is calling twice string.Format. Once with the `Formatted` extension method and then with ` AppendFormat`. In my opinion `stringBuilder.Append` would be enough.

**Comment by mikeedwards83** [comment]
Which version of Glass are you using? V4 uses a NameValueCollection and not a Dictionary.

**Comment by mikeedwards83** [comment]
This has been released
