### ISSUE TITLE
External Link lost in Experience Editor if it has special chars

### ISSUE THREAD

**Issue by jgsousa** [mikeedwards83/Glass.Mapper#273]
Hello, 

I'm running Glass Mapper SC 4.1.1.66 (and Sitecore 8.1-3) and whenever I use the experience editor to change something on a given page, if that page has a link with external url and query string parameters, when I save, the external link is cleared ( I go to content editor, and the field is blank).

The link is being generated using Html.Glass().Editable(x => x.CTA) where CTA is of type "Link". If the link doesn't have special chars it doesn't get deleted. 

Is this a known issue? Thank you

**Comment by cardinal252** [comment]
Is the link cleared in the Sitecore Dialog or just the generated one on the front end ?

**Comment by jgsousa** [comment]
I don't know if I understand correctly but the process to replicate the issue is: 
- I go to the Content Editor, go to the item, click "External link", and past the large Url with the query string
- I go to Experience Editor, navigate to a page that shows that link and I change some other field of the item (I don't touch the link), and save. 
- If I go to Content Editor, the link field is now blank. 

If I now click "External Link" I get a exception: 

[ArgumentNullException: Value cannot be null.
Parameter name: value]
   Sitecore.Diagnostics.Error.AssertString(String argument, String name, Boolean allowEmpty) +82
   Sitecore.Web.UI.Sheer.SheerResponse.SetAttribute(String id, String name, String value) +67
   Sitecore.Web.UI.HtmlControls.Edit.set_Value(String value) +135
   Sitecore.Shell.Applications.Dialogs.ExternalLink.ExternalLinkForm.OnLoad(EventArgs e) +481

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +76
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   Sitecore.Web.UI.Sheer.ClientPage.OnLoad(EventArgs e) +337
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

I have to clear the field for the error to go away.

**Comment by cardinal252** [comment]
You haven't changed any object / saved anything with Glass though ? If not, it sounds like a Sitecore bug?

**Comment by jgsousa** [comment]
No, I just use @Html.Glass().Editable(x => x.CTA) to generate the link. Nothing more. 
I'll report this to Sitecore then.

**Comment by cardinal252** [comment]
Ok, @mikeedwards83 - can you close this and re-raise if it is proven to be a Glass Mapper issue
