### ISSUE TITLE
Line of code that appears to do nothing: Database.GetItem("/parent",Language.Parse("fr-FR"));

### ISSUE THREAD

**Issue by deeja** [mikeedwards83/Glass.Mapper#274]
https://github.com/mikeedwards83/Glass.Mapper/blob/5136ac34f2159d57966e6a499b3318ff3020bb55/Source/Glass.Mapper.Sc/SitecoreService.cs#L325

`Database.GetItem("/parent",Language.Parse("fr-FR"));`

Probably shouldn't be there

**Comment by mikeedwards83** [comment]
In release 4.4.0
