### ISSUE TITLE
Add RenderText extension with parameter wether to make the text editable or not

### ISSUE THREAD

**Issue by SNiels** [mikeedwards83/Glass.Mapper#278]
`@Html.Glass().Editable(model=>model.Text, isEditable = model.DayOfTheWeek == "Wednesday")`
That would do the same as
```
@if(model.DayOfTheWeek == "Wednesday"){
    @Html.Glass().Editable(model=>model.Text)
}
else{
 @Model.Text
}
```
(this code example comes from slack, written by @mikeedwards83)
In the sample it says `.Editable`, though I'd call it RenderText to be consistent with RenderImage and to not have a confusing name.

**Comment by mikeedwards83** [comment]
This has been added to the develop branch and will be in the next nightly build.

**Comment by mikeedwards83** [comment]
In release 4.4.0
