### ISSUE TITLE
MediaRequestProtection: An invalid/missing hash value was encountered for Images

### ISSUE THREAD

**Issue by ashugoyal220** [mikeedwards83/Glass.Mapper#289]
Hi,

I am on Sitecore 8.1 and Glass.mapper.sc version is 4.0.11.63. 

Html.Glass().RenderImage gives me error in my logs "MediaRequestProtection: An invalid/missing hash value was encountered. The expected hash value: "xxxxxx....."

I've gone through with this blog and implemented the same solution
http://sitecore.stackexchange.com/questions/249/mediarequestprotection-an-invalid-missing-hash-value-was-encountered

Added a patch setting **Media.RequestProtection.SharedSecret**  in config.

Can anyone please help to resolve it?

Thank you in advance!.

**Comment by mikeedwards83** [comment]
Hi
We do add the MediaHash to images, this can be seen in the GlassHtml class. 

Can you provide me with any more information on your problem?

**Comment by mikeedwards83** [comment]
Closed due to lack of activity.
