### ISSUE TITLE
Editable cannot render linebreaks in multiline fields

### ISSUE THREAD

**Issue by PaulLoe** [mikeedwards83/Glass.Mapper#292]
If I have linebreaks in a multiline field, the Editable methode  can only render them in the Edit mode. But in preview and live the linebreaks got cut out.
I found this solution
https://blog.krusen.dk/glass-mapper-line-breaks-multi-line-fields/
but it turns the problem around. Now preview and live is working, but some fields in the Edit mode are not.

**Comment by cardinal252** [comment]
You could potentially output using a simple extension method that replaces out the line break only in edit mode as a quick fix, will try to look into it a bit more shortly.

**Comment by cardinal252** [comment]
Thinking on this further, Glass' beheviour is probably more correct, Multiline text fields may also be used for other purposes, if you were to change this behaviour, GlassHtml would probably be the more correct place to change this? An extension works equally as well.

**Comment by PaulLoe** [comment]
Thanks for the help.
I solved my problem with an extension, which replaces the linebreaks.

**Comment by apoetzsch** [comment]
Hey @cardinal252 ,
I would love to reopen this issue, cause' in my opinion the Editable Helper doesn't work correctly. I'm 100% with you that multiline fields could also be used for other purposes, so I just go with `@Editable(x => x.Headline)` and I'm done. The result in Edit and preview mode is, as expected, a single line string, whether the field is a multiline field or not.
So if I pass the linebreaks param to the helper, like `@Editable(x => x.Headline, new { linebreaks = "<br />" })`, I would also expected that the result is the same in edit and preview / normal mode. Unfortunately this isn't the case at the moment. Am I using the helper the wrong way or is it a misbehaviour?

Thanks a lot for your help.
Axel
