### ISSUE TITLE
Unable to cast object of type 'Glass.Mapper.Sc.Configuration.SitecoreChildrenConfiguration' to type 'Glass.Mapper.Sc.Configuration.SitecoreFieldConfiguration'. 

### ISSUE THREAD

**Issue by a3codeDA** [mikeedwards83/Glass.Mapper#295]
Hi, 

I have strange issue in case when trying to add components that has next HTML and @using _(BeginEditFrame(Model, "Posts", x => x.Elements))_ is present. Without it components possible to add at page via Experience Editor. 
Could you please define what could be an issue ?
Sitecore.NET 8.1 (rev. 160519) and Latest Glass
```
@inherits Glass.Mapper.Sc.Web.Mvc.GlassView<XXX.IIntroText>

<section class="wrapper-mar more-guided-travel">
    <div class="container">
        <header class="section-header">
            <div class="section-title">
                <h3>@Editable(x => x.Caption)</h3>
            </div>
        </header>
        <div class="grid-items">
            @using (BeginEditFrame(Model, "Posts", x => x.Elements))
            {
                foreach (var post in Model.Elements)
                {
                    <div class="grid-item">
                        @using (BeginEditFrame(post.Path))
                        {
                            <div class="item-title">
                                <h3>@Editable(post, x => x.Caption)</h3>
                            </div>
                                        <div class="item-image">
                                            @RenderImage(post, x => x.Image)
                                        </div>
                                        <div class="item-content">
                                            <p>
                                                @Editable(post, x => x.Text)
                                            </p>
                                            @RenderLink(post, x => x.LinkButton, new System.Collections.Specialized.NameValueCollection { { "class", "btn btn-primary btn-block" } })
                                        </div>
                                        <div class="hover-content">
                                            @Editable(post, x => x.ImageHoverText)
                                        </div>
                        }
                    </div>
                }
            }
        </div> <!-- end grid-items -->
    </div> <!-- end container div -->
</section> <!-- end component section -->
```

```
 [SitecoreType(TemplateId = "{1006D9F7-5657-499A-A85E-A0463F859AEF}", AutoMap = true)]
    public interface IIntroText : IGlassItemEx
    {
        [SitecoreField]
        string Caption { get; set; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IIntroTextRowElement> Elements { get; set; }
    }
```

> 13700 10:47:38 ERROR SitecoreHelper - DynamicPlaceholder: Exception Ocurred Error while rendering view: '/Views/IntroText.cshtml' (model: 'Castle.Proxies.IIntroTextProxy, DynamicProxyGenAssembly2').
>    at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)
>    at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args)
>    at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
>    at Sitecore.Mvc.Pipelines.Response.RenderPlaceholder.PerformRendering.Render(String placeholderName, TextWriter writer, RenderPlaceholderArgs args)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
>    at Sitecore.Mvc.Helpers.SitecoreHelper.Placeholder(String placeholderName)
>    at XXX.Library.CustomSitecore.Pipelines.DynamicPlaceholders.SitecoreHelper.DynamicPlaceholder(SitecoreHelper helper, String dynamicKey, Char identifier) in C:\Projects\XXX\CustomSitecore\Pipelines\DynamicPlaceholders\DynamicKeyPlaceholder.cs:line 16
> 13700 10:47:38 ERROR SitecoreHelper - DynamicPlaceholder: Inner Exception: Unable to cast object of type 'Glass.Mapper.Sc.Configuration.SitecoreChildrenConfiguration' to type 'Glass.Mapper.Sc.Configuration.SitecoreFieldConfiguration'.   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.String.Join(String separator, IEnumerable`1 values)
>    at Glass.Mapper.Sc.GlassHtml.EditFrame[T](T model, String title, TextWriter output, Expression`1[] fields) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\GlassHtml.cs:line 170
>    at ASP._XXX_IntroText_cshtml.Execute() in c:\Projects\xxx\IntroText.cshtml:line 11
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>    at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
>    at Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer)

**Comment by mikeedwards83** [comment]
You have created an Edit Frame but passed in a property that is not a field. In this case  you are passing in a list of child items. 

The edit frame will only work with fields so you need to convert the Elements property to a field in Sitecore and then update your mapping.
