### ISSUE TITLE
 Method not found: 'Boolean PageMode.get_IsPageEditor()'.

### ISSUE THREAD

**Issue by kmac23va** [mikeedwards83/Glass.Mapper#297]
I just updated my site to 8.2 Update 3, and when I try to run my site, I get this error pointing to Source\Glass.Mapper.Sc\Utilities.cs:54. This looks like a conditional for #IF SC82 to use IsExperienceEditor, otherwise use IsPageEditor. I downloaded the source code to look at it, and I noticed in the SC82 configuration for Glass.Mapper.Sc, the conditional compilation symbol is set to SC81. I'm guessing IsPageEditor has been finally removed from Sitecore since it was deprecated. Is this something that can fixed up? Thanks much.

**Comment by kmac23va** [comment]
Okay, this is weird. I'm using .NET 4.6.1 and 8.2 Update 3 with the latest Glass Mapper, and the project references say the Glass.Mapper.Sc file is pointing to the NuGet location in the lib/100 folder. When I look in there and use dotPeek on that file, the compiled code is using IsExperienceEditor. However, the version of the file that gets deployed to my website bin folder uses IsPageEditor. I'm not sure why there's this discrepancy...I even deleted the DLLs from the website bin and redeployed, and it's still the wrong version. 

Is there some check that needs to be expanded for Update 3's DLL versions that hasn't been set yet because it's so new? I don't recall having the issue with Update 2 in a recent project.

**Comment by kmac23va** [comment]
I went back to a "reset" version of my solution, removed Glass entirely, upgraded all of the DLLs to 8.2 Update 3, then reinstalled Glass and published to a fresh location. This time, the Glass.Mapper.Sc.dll had the right definition to use IsExperienceEditor. Very weird, but it's working, so I'm closing this.

**Comment by mikeedwards83** [comment]
Hi Ken sorry for not responding sooner. We had a 4 day holiday in the UK. Normally this issue arises because DLLs aren't being copied by VS/TDS after a build. We would normally recommend that you delete the Glass assemblies in the Website bin folder and perform a rebuild. 

Glad you found a solution.

Mike

**Comment by klpatil** [comment]
I also faced same issue. After doing all Research and read, Have been able to find a cause and fix.
- I was working on a Version upgrade project where roughly ~15 Projects in a solution was using Latest Glass DLL [4.4.0.199] when it got added Sitecore Kernel version was 8.1 Update3. And When I updated all proejcts to use 8.2 Update 5 I started getting this error.
- Lot of articles mentioned upgrade Glass Version. But It was already up to date
- Closely looking at GlassMapper.SC Dll it was coming from 
packages\Glass.Mapper.Sc.Core.4.4.0.199\lib\**81**\Glass.Mapper.Sc.dll
- You can unistall and install Glass [OR Downgrade and Upgrade Glass] after making sure each project has Kernel version for 8.2
- And your new references will come from packages\Glass.Mapper.Sc.Core.4.4.0.199\lib\100\Glass.Mapper.Sc.dll
- That's it! Hope it helps you!

![image](https://user-images.githubusercontent.com/3901926/30684891-9c420e42-9ed0-11e7-85e0-5a5f4b20c5b8.png)
