### ISSUE TITLE
SitecoreFieldIdMapper should return null instead of Guid.Empty

### ISSUE THREAD

**Issue by wimmeerschman** [mikeedwards83/Glass.Mapper#302]
When you create a property of type ID for field X, and the Sitecore field X is empty, it throws a cast exception, Unable to cast object of type 'System.Guid' to type 'Sitecore.Data.ID'.

Suggested fix: return null instead of Guid.Empty.

**Comment by mikeedwards83** [comment]
Can you supply an example of the property you were mapping and the stack
trace.

**Comment by wimmeerschman** [comment]
Hello,

The info you asked:

The glass class:
    public class OurConfig : BaseGlassItem
    {
        public const string TemplateIdString = "{13CC91C2-7B8B-4A95-92CF-0CC3B854E6B2}";
        public new static ID TemplateId = ID.Parse(TemplateIdString);

        [SitecoreField("Translation Dictionary")]
        public ID TranslationDictionaryId { get; set; }
    }

It fails on setting the value for property TranslationDictionaryId. You must set the an empty value for this field to have the error.

[InvalidCastException: Unable to cast object of type 'System.Guid' to type 'Sitecore.Data.ID'.]
   lambda_method(Closure , Object , Object ) +72
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +77
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) in c:\TeamCity\buildAgent\work\8567e2ba106d3992\Source\Glass.Mapper.Sc\DataMappers\AbstractSitecoreFieldMapper.cs:66
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +152

[MapperException: Failed to map property TranslationDictionaryId on Dlw.ScBase.Website.Components.TechDemo.Exceptions.ExceptionsConfig]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +401

[MapperException: Failed to map properties on /sitecore/content/TestSites/TechDemo/Home/Exceptions/Page Configuration/Exceptions Config.]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +578
   Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(ObjectConstructionArgs args) +331

[MapperException: Failed to create type OurConfig

**Comment by mikeedwards83** [comment]
I have pushed a fix to the develop branch

**Comment by mikeedwards83** [comment]
In release 4.4.0
