### ISSUE TITLE
Wrong RichText-Fieldvalue Mapping on Items with duplicate Fieldnames

### ISSUE THREAD

**Issue by shindai** [mikeedwards83/Glass.Mapper#311]
Hi,

there is a mapping problem with items, which contains multiple rich text fields with the same name.
Example:
Template: ContactFormMailSettings
External Mail Settings (Section)
- Sender [SingleLineText]
- MailText [RichtText]
Internal Mail Settings (Section)
- Sender [SingleLineText]
- MailText [RichtText]

The problem is that in SitecoreFieldStringMapper the renderField-Pipeline is called to get the richtext-value and in the arguments only the fieldname is set.
If there are multiple richtext-fields with the same name, only the value of the first is served.

This problem occured because the RenderFieldsArgs doesn't contains a FieldId-Property (only FieldName).
Could you please contact sitecore to extend the "api" with an FieldId-Property, which should be used if set, instead of the fieldName? And if they added the property, please adjust the glassMapper-code to this.

I can't create an support ticket for that, because sitecore itself doesn't seems to have a problem with that pipeline (I couldn't find any issue). But this issue results in an bug in glassMapper.

**Comment by mikeedwards83** [comment]
Fix has been pushed to the nightly build. Can you download and see if this fixes your issue? The nuget version should be 4.3.5.295-beta

**Comment by mikeedwards83** [comment]
In release 4.4.0
