### ISSUE TITLE
What is the glass mapper field type that can map sitecore's "Internal Link" fields?

### ISSUE THREAD

**Issue by vrkmajeti** [mikeedwards83/Glass.Mapper#313]
[Continuation for issue #310 ]. Hi Mike, We are using the T4 templates referred in the http://www.glass.lu/Mapper/Sc/Tutorials/Tutorial24 and it is generating property type of 'object' for sitecore 'internal link' field type. We understand that Glass.Mapper.Sc properties of type System.Object are no longer supported as per http://www.glass.lu/Mapper/Sc/Documentation/CommonQuestionsAndProblems/SystemObjectError
What is the new applicable glass mapper property type that can map sitecore's "Internal Link" fields? Please advice.

**Comment by cardinal252** [comment]
I believe 'Link' should behave fine for internal links

**Comment by vrkmajeti** [comment]
Thanks @cardinal252 . That seems to work.

**Comment by vrkmajeti** [comment]
@cardinal252 , Mapping sitecore item's Internal Link field to Glass mapper Link field eliminated the mapping exception, but it wasn't constructing that Link object with all values. This issue was closed, So, we created a new issue #317
