### ISSUE TITLE
GlassHtml.RenderImage ALT attribute is not HTML encoded

### ISSUE THREAD

**Issue by andrey-stepanov** [mikeedwards83/Glass.Mapper#316]
In case ALT text contains quotation mark helper class generates broken HTML code.

**Comment by mikeedwards83** [comment]
Can you give me an example. My testing shows that this works as expected. 

See the following test:
https://github.com/mikeedwards83/Glass.Mapper/commit/adb8a7ae27a8472717918afed32499581fce8064

**Comment by andrey-stepanov** [comment]
Thanks for looking into it! Looks, like it's been resolved now. I had the issue on version 4.3.4.197.

**Comment by mikeedwards83** [comment]
Ok, thanks for the feedback. I will close the issue.
