### ISSUE TITLE
GlassController.GetLayoutItem<T> where T has 'Internal Link' property isn't populating the Glass.Mapper.Sc.Fields.Link object when mapped

### ISSUE THREAD

**Issue by vrkmajeti** [mikeedwards83/Glass.Mapper#317]
As recommended by the fix in issue #313 , we used Glass.Mapper.Sc.Fields.Link to map sitecore item's 'Internal Link' fields. When using GlassController.GetLayoutItem<T>() , where typeof(T) has internal link field property mapped to Link Field, Link object isn't getting built from the raw value in that field. Sample raw value of internal link field - /sitecore/content/Settings/Common Text/Communications/Widgets/Highlights. We are using latest glass.mapper.sc 4.3.4.197. Please advice.

**Comment by mikeedwards83** [comment]
Hi

Thanks for bring this to my attention. I have created a fix which will be available in the nightly build.

**Comment by mikeedwards83** [comment]
Closed in release 4.5.0.202
