### ISSUE TITLE
Internal link empty url property with SitecoreInfoUrlOptions.AlwaysIncludeServerUrl

### ISSUE THREAD

**Issue by qkhaipham** [mikeedwards83/Glass.Mapper#318]
I'm using Sitecore.NET 8.2 (rev. 161221) with GlassMapper ( 4.4.0.199, I was on 4.3.4.197 but upgraded but didn't help ) and I noticed that the URL property is empty when using a General Link pointing to an internal item.  I did use the SitecoreInfoUrlOptions.AlwaysIncludeServerUrl option in the mapping attribute as suggested in https://stackoverflow.com/questions/21218457/get-absolute-url-for-internal-links-with-glass-mapper-for-sitecore . Also did some testing by calling sitecore's LinkManager directly with a sitecore item and with the same kind of UrlOptions to see if i could retrieve the server url, and that still works so I don't think it could be inside Sitecore. Has anyone else had trouble with this? 

using this simple model:
`    [SitecoreType(TemplateId = Templates.Login.Id)]
    public class LoginTest
    {
        [SitecoreId]
        public virtual Guid Id { get; set; }

        [SitecoreField(FieldId = "{B3988BF4-7F5D-4544-9208-0E4C164C3262}", FieldType = SitecoreFieldType.GeneralLink, UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)]
        public virtual Link RedirectUrlAfterLogin { get; set; }
    }`

**Comment by mikeedwards83** [comment]
Hi

I have tested with the following model:

    public class View
    {
        public virtual Guid Id { get; set; }
        public virtual Language Language { get; set; }
        public virtual int Version { get; set; }

        public virtual string Title { get; set; }
        public virtual string Body { get; set; }

        [SitecoreField(UrlOptions = SitecoreInfoUrlOptions.AlwaysIncludeServerUrl)]
        public virtual Link Link { get; set; }
    }

And it outputs this:

<a href="http://dev.glass.testing.local/Issue331">Issue331</a>

Which is correct. Do you still have the problem or can you supply more info?

Thanks

Mike

**Comment by mikeedwards83** [comment]
Closed in release 4.5.0.202
