### ISSUE TITLE
Issues  after upgrade to V4

### ISSUE THREAD

**Issue by ambujshukla1981** [mikeedwards83/Glass.Mapper#321]
I upgraded to Glass Mapper v4.   What is new syntax for below code
//create the resolver
            var resolver = DependencyResolver.CreateStandardResolver();

            //install the custom services
            var config = new Config();

            var container = resolver.Container;
            container.Install(new SitecoreInstaller(config));

            var assembliesSetting = Sitecore.Configuration.Settings.GetSetting("ConfigureIoc.Assemblies");
            var assemblies = assembliesSetting.Split(new[] {','}, StringSplitOptions.RemoveEmptyEntries);
            container.Install(new ControllerInstaller(assemblies));

            //create a context
            var context = Glass.Mapper.Context.Create(resolver);

            context.Load(
                new SitecoreAttributeConfigurationLoader(assemblies)
                );

            //register the Glass components
            container.Register(
                Component.For<ISitecoreContext>().ImplementedBy<SitecoreContext>().LifestyleTransient(),
                Component.For<ISitecoreService>().UsingFactoryMethod(() => new SitecoreService("master")).LifestyleTransient()
                );

            var controllerFactory = new WindsorControllerFactory(ControllerBuilder.Current.GetControllerFactory(), container.Kernel);

            ControllerBuilder.Current.SetControllerFactory(controllerFactory);

**Comment by mikeedwards83** [comment]
Hi

Information upgrading to V4 is here:

http://www.glass.lu/Mapper/Sc/Documentation/UpgradingToV4

Mike
