### ISSUE TITLE
Performing Sitecore updgrade from 8.1  to 8.2

### ISSUE THREAD

**Issue by gredkar** [mikeedwards83/Glass.Mapper#327]
Our organization is planning a Sitecore upgrade from current 8.1 to version 8.2 and we use GlassMapper heavily in our application code our current version in use is  4.3.4.197 .

The question we have is 

We have seen quite a few users have noted errors in GlassMapper post upgrade such as
https://sitecore.stackexchange.com/questions/3385/glass-mapper-problem-with-solution-upgraded-from-sitecore-8-1-to-8-2 
or 
https://sitecore.stackexchange.com/questions/5843/sitecore-8-1-to-8-2-glass-mapper-related-error

So are there any precautions or best practices  we can address before the upgrade to ensure a smooth transition and ensure no issues in glassMapper post the upgarde ?

**Comment by mikeedwards83** [comment]
Hi 

Glass has to be compiled against each version of the Sitecore.Kernel.dll  and System.Web.Mvc.dll assemblies. To ensure that you have a clean upgrade ensure that you update every project reference for these two assemblies. Afterwards you should either upgrade or remove and then re-add the Glass nuget, this will cause Glass to rescan and the correct assembly reference paths. 

If you need help during the upgrade I can supply consultancy.

Thanks

Mike

**Comment by gredkar** [comment]
Thanks a lot Mike will replay that to my Managers and get back to you.
