### ISSUE TITLE
Suspect that BeginRenderLink truncates URLs containing question marks

### ISSUE THREAD

**Issue by jesseglaves** [mikeedwards83/Glass.Mapper#328]
**I have a link that contains question marks. BeginRenderLink appears to be truncating the URL at the question mark. The value in the field is:**

`http://firstsearch.oclc.org/WebZ/FSPage?pagetype=return_frameset:linktype=servicelink:sessionid=fsapp6-41637-j79jaw2f-61y8dw:entitypagenum=10:0?entityframedscrolling=yes:entityframedurl=http%3A%2F%2Fwww.example.com:entityframedtitle=:entityframedtimeout=15`

**The link that is output is:**

`http://firstsearch.oclc.org/WebZ/FSPage`

**The class is:**

```
public class Promo
{
    ...
    public virtual string Title { get; set; }
    public virtual Link Link { get; set; } // Where Link is of type Glass.Mapper.Sc.Fields.Link
    ...
}
```

**The cshtml is:**

```
foreach (var Promo in Model.Promos)
{
    @using (BeginRenderLink(Promo, x => x.Link, isEditable: true))
    {
        @Editable(Promo, x => x.Title)
    }
}
```

If I view the value without using BeginRenderLink (i.e. @Model.Link.Url) it works as expected.

Thanks.

**Comment by jesseglaves** [comment]
Granted, this is a horribly formatted URL. And the issue doesn't appear to be with the question mark. I think it's actually the fact that this particular website uses colons as query string delimiters, instead of ampersands. I don't know if there is much the could be done to parse this particular URL.

**Comment by jesseglaves** [comment]
Oh, and there are also two question marks in the query string.

**Comment by mikeedwards83** [comment]
Hi

Thanks for reporting this issue, a fix has been pushed to the nightly build in the following commit:

https://github.com/mikeedwards83/Glass.Mapper/commit/8c61cd4ae396a228512c8f27251975d273a5d34f

You can access this from the nightly build.

**Comment by mjarosch** [comment]
We just ran into this bug, some of our links have a query string that needs to have "=" in the parameter values. What is your release schedule like? When do you think this will make it into a release?

Looking at the commit, you created your own split function. There is a String.Split that takes a maximum number of substrings to return. I was testing that out for a pull request until I saw that you had already fixed it. https://msdn.microsoft.com/en-us/library/c1bs0eda(v=vs.110).aspx

**Comment by mikeedwards83** [comment]
This has been released. Re-open if there is still an issue.
