### ISSUE TITLE
[4.5.0.4] Infertype appears to be broken

### ISSUE THREAD

**Issue by Wallyza** [mikeedwards83/Glass.Mapper#339]
Busy upgrading a project to Sitecore 9, so far so good except for Infertype on Children.

I've got the below bit of code with a few items deriving from BaseItem.

`[SitecoreChildren(InferType = true)]`
`public virtual IEnumerable<BaseItem> Children { get; set; }`

No matter the type of the item it'll always come back as BaseItem.

**Comment by mikeedwards83** [comment]
Hi

I have tested this locally and I don't experience this problem. Can you tell me how you are loading the types? Are you using the SitecoreAttributeConfigurationLoader?

**Comment by Wallyza** [comment]
Hi Mike,

Thanks for the response!  We're using automapping (AutoMap = true on our classes).  Could this be the cause of our woes?

**Comment by cardinal252** [comment]
I think @mikeedwards83 was referring to this (Glass site is currently not operational):

https://blog.krusen.dk/using-infertype-with-glass-mapper-for-sitecore/

**Comment by Wallyza** [comment]
You guys were 100% correct, we were missing the AttributeConfigurationLoader.  Thanks a million.  Closing this.
