### ISSUE TITLE
Language Fallback doesn't work for  glass Sitecore query

### ISSUE THREAD

**Issue by sunilaher** [mikeedwards83/Glass.Mapper#344]
I am trying to get fallback item using glass sitecoreQuery as per below
`  public partial interface T
{
    [SitecoreQuery("./*[@@templatename='TemplateName']", InferType =true, IsLazy = true, IsRelative = true)]
    T1 customProperty{ get; set; }

}` 

I am trying to get property of fallback item T (customProperty) using sitecore query, but no luck. 
Note: CustomProperty not returning null object as I have added versionCountDisabler in request begin pipeline.

**Comment by mikeedwards83** [comment]
The query is passed directly to the Sitecore Database SelectItems method and GMS will map any items returned. 

Can you see if this is your problem:
https://sitecore.stackexchange.com/questions/245/item-language-fallback-doesnt-work-for-sitecore-query

Can you try making the same query against the raw Sitecore API and see if you have the same issue?

**Comment by mikeedwards83** [comment]
Closing due to lack of response.
