### ISSUE TITLE
Glass Mapper doesn't behave correctly when retrieving Url for home item with languageEmbedding set to never

### ISSUE THREAD

**Issue by SoulOfUniverse** [mikeedwards83/Glass.Mapper#345]
If you set languageEmbedding to never, Url field, which is base Sitecore info field string type returns **"//"** url for home start item of the site definition. If languageEmbedding is set to asNeeded or Always, it does return expected url **"/en/"** of home start item of the site definition.

**Comment by mikeedwards83** [comment]
@SoulOfUniverse  Can you tell me which version of Glass.Mapper.Sc you are using?

**Comment by mikeedwards83** [comment]
Can you also tell me how you are setting the languagembedding flag?

**Comment by mikeedwards83** [comment]
Closing due to lack of response.
