### ISSUE TITLE
the Namespace "xxx.xxx.xxx.xxxx" already contains definition for "class" error

### ISSUE THREAD

**Issue by tarun0207** [mikeedwards83/Glass.Mapper#348]
HI,

i am getting this error while generating the code from TDS project using glassMapper. I am also getting duplicate namespace in that auto generated file.
Please help in resolving this.

**Comment by mikeedwards83** [comment]
TDS code generation issues should be raised on the TDS code generation project.  https://github.com/HedgehogDevelopment/tds-codegen

If you need further support please consult our support page: http://www.glass.lu/Support
