### ISSUE TITLE
Facing the Glassmapper issue in IIS log

### ISSUE THREAD

**Issue by Astleee** [mikeedwards83/Glass.Mapper#349]
11 00000054`4365c220 00007ffd`f343856c Glass_Mapper_Sc!Glass.Mapper.Sc.DataMappers.SitecoreFieldLinkMapper.GetField(Sitecore.Data.Fields.Field, Glass.Mapper.Sc.Configuration.SitecoreFieldConfiguration, Glass.Mapper.Sc.SitecoreDataMappingContext)+0x746
12 00000054`4365c4b0 00007ffd`f343822d Glass_Mapper_Sc!Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(Glass.Mapper.AbstractDataMappingContext)+0xfc
13 00000054`4365c550 00007ffd`f343815c Glass_Mapper!Glass.Mapper.AbstractDataMapper.MapCmsToProperty(Glass.Mapper.AbstractDataMappingContext)+0x5d
14 00000054`4365c660 00007ffd`f3437d6c Glass_Mapper_Sc!Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(Glass.Mapper.AbstractDataMappingContext)+0x8c
15 00000054`4365c6c0 00007ffd`f3437b25 Glass_Mapper!Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(System.Object, Glass.Mapper.IAbstractService, Glass.Mapper.AbstractTypeCreationContext)+0xec
16 00000054`4365c810 00007ffd`f32162a8 Glass_Mapper!Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.CreateObject(Glass.Mapper.Pipelines.ObjectConstruction.ObjectConstructionArgs)+0x285
17 00000054`4365c920 00007ffd`f320ab68 Glass_Mapper!Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.CreateConcreteTask.Execute(Glass.Mapper.Pipelines.ObjectConstruction.ObjectConstructionArgs)+0x178
18 00000054`4365c9d0 00007ffd`f320a493 Glass_Mapper!Glass.Mapper.Pipelines.AbstractPipelineRunner`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].Run(System.__Canon)+0x228
19 00000054`4365caf0 00007ffd`f3209e7e Glass_Mapper!Glass.Mapper.AbstractService.InstantiateObject(Glass.Mapper.AbstractTypeCreationContext)+0x1f3

**Comment by mikeedwards83** [comment]
Unfortunately we are not able to diagnose issue directly from stack traces. 

Could you supply further information? If your issue is urgent then can I suggest looking at our support page for info on how you can get immediate assistance: http://www.glass.lu/Support

**Comment by mikeedwards83** [comment]
Closing due to lack of response
