### ISSUE TITLE
media items does not render title attribute (by default)

### ISSUE THREAD

**Issue by DeathAngelDaemon** [mikeedwards83/Glass.Mapper#353]
Dear GlassMapper team,

I was just wondering if it is wanted behaviour that the `RenderImage` method is not rendering the title attribute by default (mapping to the "Title" (or "Image description") field of a Sitecore media item).
The only way to achieve this is to add the `Title` in the parameters object, isn't it?

Thanks in advance for clarification.

Best regards
Anna

**Comment by mikeedwards83** [comment]
Hi Anna.

Thanks for bring this to my attention. This is something that we will look to address as a bug fix in a future release or you can create a pull request and we can fix this problem sooner.

Thanks

Mike
