### ISSUE TITLE
Droplinks will not map to referenced object when EnforceTemplate = SitecoreEnforceTemplate.TemplateAndBase

### ISSUE THREAD

**Issue by AdamHess** [mikeedwards83/Glass.Mapper#354]
When  `EnforceTemplate = SitecoreEnforceTemplate.TemplateAndBase` for either the referred item and the item that refers it the item will not populate the object. 

See https://github.com/AdamHess/Sitecore-Glassmapper-Guid for example.

**Comment by mikeedwards83** [comment]
I have replicated this issue.

**Comment by mikeedwards83** [comment]
Fix available in alpha release 5.1.98-alpha

**Comment by mikeedwards83** [comment]
Closing this isssue
