### ISSUE TITLE
Feature Request: application wide rendering rules for links to not include language

### ISSUE THREAD

**Issue by AdamHess** [mikeedwards83/Glass.Mapper#355]
By default, glass mapper will render links with the language of the site prefixed; this can be problematic for single language sites.

Many links end up being
`/en/suburl`

the current way to remedy this is: 
`UrlOptions = SitecoreInfoUrlOptions.LanguageEmbeddingAsNeeded`

however, it can become quite cumbersome to set this attribute on every link field or include it in the item mapper. 

A configuration file based, or code based way to set the default for handling link fields would be much appreciated.

**Comment by mikeedwards83** [comment]
You should be able to do this via the standard Sitecore configuration. See the link manager definition in the Sitecore config.

```
<linkManager defaultProvider="sitecore">
<providers>
<clear/>
<add name="sitecore" type="Sitecore.Links.LinkProvider, Sitecore.Kernel" addAspxExtension="false" alwaysIncludeServerUrl="false" encodeNames="true" languageEmbedding="asNeeded" languageLocation="filePath" lowercaseUrls="false" shortenUrls="true" useDisplayName="false"/>
</providers>
</linkManager>
```
