### ISSUE TITLE
V5 Renders Empty Links

### ISSUE THREAD

**Issue by halovanic** [mikeedwards83/Glass.Mapper#363]
Hi,

After upgrading to 5.3.15 (9.1) from V4, I noticed that the behavior has changed for the usual Razor link rendering code `@RenderLink(x => x.Link)` when the link field is null (i.e, not set in the content editor).  With V4 (when not in editing mode) nothing would be rendered.  Now Glass is rendering an element like the following:
`<a href="" ></a>`
It will also set any attributes passed in, so you can easily get a visibly styled empty link.

It looks like this was changed in commit 64d239a3f03c1e4e103434f8c9c3bdc68b6e7ef5 to GlassHtml.cs:
The alwaysRender parameter was removed and `new Link()` is now used every time given a null Link, when before the code would explicitly return an empty RenderingResult.  I'm not positive of the intent, but maybe the alwaysRender == false behavior should have been kept instead?

With the null link, the Experience Editor still renders a link reading [No text in field] as it always did.  This is just an issue for normal mode.

Thanks,
Alex

**Comment by mikeedwards83** [comment]
Fixed in release 5.3.17
