### ISSUE TITLE
v5 SitecoreQueryMapper.MapToProperty(..) language issue?

### ISSUE THREAD

**Issue by vellemansf** [mikeedwards83/Glass.Mapper#368]
Hi,

I'm in the process of upgrading from **v4** to **v5.** One of my failing unit tests showed a difference in behavior regarding the **SiteQueryMapper's** **MapToProperty**(..) method. A substantial amount of code has been reduced by using **GetItemsByQueryOptions**, which is very cool. However, the old method used to take into account **the language of the item** (scContext.Item.get_Language() in v4), but in v5 the Language property of GetItemsByQueryOptions is left at null.
When I create my own implementation of this mapper and I set the language, my tests no longer fail:

`itemsByQueryOptions.Language = dataMappingContext.Item.Language;`

I'm not sure of this is a bug, or by intention. I can work around this issue by making my custom SitecoreQueryMapper part of my own solution, if needed.

Thank you!

**Comment by mikeedwards83** [comment]
Thanks for reporting this. I assume that you have this problem when running and absolute query?

**Comment by mikeedwards83** [comment]
I think this has been fixed in my last commit to the development branch.

**Comment by vellemansf** [comment]
Perfect.

**Comment by mikeedwards83** [comment]
Fixed in release 5.3.17
