### ISSUE TITLE
Map protected properties

### ISSUE THREAD

**Issue by VGBenjamin** [mikeedwards83/Glass.Mapper#369]
Hello,

We have a recurrent issue with the Glass Item classes. Sometimes developers modify the values of the mapped field manually as those items are cached and shard between users, it isn't a good practice at all.
So I would like to enforce the developers to put the mapped properties with a protected setter in place of a public one. But apparently Glass doesn't handle the non public properties. 
Do you think that it could be possible to also set the non public properties? 

Also, I have tried to fork and debug the source code but apparently the packages.config files are missing how can I fix it?

Regards,

Benjamin Vangansewinkel

**Comment by Glass-Build-Github** [comment]
Hi Benjamin

Thanks for contacting me. Glass should support protected properties have
you tested this? I am sure we have a unit test for this.

Cheers
*Mike Edwards*
E: mike@glass.lu
T: 07734 699316
W: http://www.glass.lu

Visit the website to find out about training, consultancy and development.

Glass is a trading name of M C Edwards Ltd, registered in England & Wales.
Registration number 08641300. Registered office: The Guild Hub, High Street
Bath BA1 5EB.

Why not checkout my other tool Refract DNS (https://refractdns.com/). Your
personal DNS.

**Comment by VGBenjamin** [comment]
Hello, 

Yes I have test it and when I put it in public it works so it is really realated to the property visibility.

Regards,
Benjamin

**Comment by mikeedwards83** [comment]
Hi Benjamin

I have just confirmed this is working as expected with a unit tests. Can you check your code?

https://github.com/mikeedwards83/Glass.Mapper/commit/4894730efa379be32906baae346b6ffe2b3a0e62

Thanks
Mike
