### ISSUE TITLE
[5.3.17 ]SitecoreService:populate method is not working ...

### ISSUE THREAD

**Issue by sebmourier** [mikeedwards83/Glass.Mapper#372]
... unless you use the signature public void Populate<T>(T target, GetOptions options) where T : class
with options of type GetItemOptions 

Example :   
```
GetItemOptions options = new GetItemOptions()
{
        Lazy = LazyLoading.Enabled
};

sitecoreService.Populate(result, options);
```

It's not working under certains circumstances ... I think it's when you have a children property in a Glass class.

I did some research on your code and I found the problem in the Glass.Mapper.Sc library , class SitecoreTypeCreationContext and that method

````
/// <summary>
/// Creates the data mapping context.
/// </summary>
public override AbstractDataMappingContext CreateDataMappingContext(object obj)
{
      var mappingContext = new SitecoreDataMappingContext(obj, Item, SitecoreService, Options as GetItemOptions);
       return mappingContext;
}

Your cast "as" is incorrect because by default you pass an object of type GetOptions and GetOptions is not of type GetItemOptions

**Comment by mikeedwards83** [comment]
Can you give me an example of the model that is causing a problem?

**Comment by sebmourier** [comment]
```
[SitecoreType(TemplateId = "{XXX}", AutoMap = true)]
public class ClassA
{
	[SitecoreField(FieldName = "NameProperty1")]
	[IgnoreIndexField]
	public virtual IEnumerable<ClassB> NameProperty1 { get; set; }
	[IndexField("NameProperty2")]
	public virtual IEnumerable<Guid> NameProperty2 { get; set; }
	public virtual string NameProperty3 { get; set; }
}


[SitecoreType(TemplateId = "{YYY}", AutoMap = true)]
public class ClassB
{
	[SitecoreField(FieldName = "NameProperty1")]
	public virtual string NameProperty1 { get; set; }

	[SitecoreField(FieldName = "NameProperty2")]
	public virtual bool NameProperty2 { get; set; }

	[SitecoreField(FieldName = "NameProperty3")]
	[IgnoreIndexField]
	public virtual Style.Style NameProperty3 { get; set; }

	[IndexField("NameIndexField")]
	public ID NameProperty4 { get; set; }

	[SitecoreParent(InferType = true)]
	public virtual ClassB Parent { get; set; }

	[SitecoreChildren(InferType = true)]
	public virtual IEnumerable<ClassB> Children{ get; set; }
}
```

NameProperty1 of ClassA is linked to a Sitecore field of type "TreeList".

FYI, only this property seems to have a problem because for this one when I debug your code, I get through the "SitecoreFieldIEnumerableMapper" class (method "GetFieldValue") and then through the "SitecoreFieldTypeMapper" class.
In that class (method "GetFieldValue"), the line 
````
 getOptions.Copy(context.Options);
````
raises an exception because `context context.Options = null` wich result from the point I gave you in my previous post (incorrect cast "as")

**Comment by mikeedwards83** [comment]
I have changed the options type on the populate method to GetKnownOptions to resolve this issue. See the associated commit.

**Comment by mikeedwards83** [comment]
https://github.com/mikeedwards83/Glass.Mapper/commit/63d55094dfa9495b2032d99fb17578c363b7c47d

**Comment by mikeedwards83** [comment]
This change  was in the last release. If you still have a problem please re-open this issue.
