### ISSUE TITLE
SitecoreItem attribute not working

### ISSUE THREAD

**Issue by florianalexanderscholz** [mikeedwards83/Glass.Mapper#376]
Hello, 

we have the problem, that the SitecoreItem attribute results in a null reference. The version is GlassMapper 5.3.17.

**Comment by mikeedwards83** [comment]
Hi 
I have written a unit test that shows this is working. Can you give me more information?

https://github.com/mikeedwards83/Glass.Mapper/commit/7b4a0a6369d9e0863c22983eaa339e5e2e58ae6e

Thanks

mike

**Comment by florianalexanderscholz** [comment]
public class SomeController : Controller
    {
        private readonly IMvcContext _mvcContext;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="mvcContext">Injects the Mvc Context</param>
        public SomeController(IMvcContext mvcContext)
        {
            this._mvcContext = mvcContext;
        }
        // Index Action
        public ActionResult Index()
        {
            var dsItem = _mvcContext.GetContextItem<ExtendedSomeModule>();
            if (dsItem == null)
            {
                return new EmptyResult();
            }
          //dsItem.SitecoreItem is null
        }
    }

    [SitecoreType(TemplateId = SomeModuleConstants.TemplateIdString)]
    public class ExtendedSomeModule: BSomeModule
    {
        /// <summary>
        /// Requires the Item
        /// </summary>
        [SitecoreItem]
        public Item SitecoreItem { get; set; }
    }

    [SitecoreType(Cache = Cache.Default, TemplateId = SomeModuleConstants.TemplateIdString)]
    public partial class SomeModule : GlassBase, ISomeModule
    {
...
    }

**Comment by D4rkiii** [comment]
Did you tried to set your property to virtual because of lazy loading?

[SitecoreItem]
public virtual Item SitecoreItem { get; set; }

**Comment by florianalexanderscholz** [comment]
I did.

**Comment by mikeedwards83** [comment]
Just to confirm that your model is now

```
[SitecoreType(TemplateId = SomeModuleConstants.TemplateIdString)]
public class ExtendedSomeModule: SomeModule
{
    /// <summary>
    /// Requires the Item
    /// </summary>
    [SitecoreItem]
    public virtual Item SitecoreItem { get; set; }
}
```

**Comment by florianalexanderscholz** [comment]
Can be closed ;-) Thank you.
