### ISSUE TITLE
FieldType Method issue with Glass Mapper V5

### ISSUE THREAD

**Issue by SharathMP** [mikeedwards83/Glass.Mapper#382]
FieldType method from Glass.Mapper.Sc.Configuration.Fluent is removed from V5, please suggest alternatives of handling FieldType method as stated in the below problem statement.

**We had this method in V4:**

Glass.Mapper.Sc.Configuration.Fluent {

public SitecoreField FieldType(SitecoreFieldType fieldType) { this.Configuration.FieldType = fieldType; return this; } }

**The Issue with FieldType since this has been revoked in V5: Code will fail to compile since FieldType in the below method has been revoked from V5**

public class MetadataMap : SitecoreGlassMap {

public override void Configure()
{
    Map(x =>
    {
        x.Field(y => y.NoIndex).FieldType(Glass.Mapper.Sc.Configuration.SitecoreFieldType.Checkbox).FieldName("NotIndex");
        x.AutoMap();
    });
}
}

**Comment by mikeedwards83** [comment]
I have answered on Github

https://sitecore.stackexchange.com/questions/19234/fieldtype-method-issue-with-glass-mapper-v5

**Comment by mmacehardyman** [comment]
@mikeedwards83 I have the same issue; the post on SSE is no longer there (apperently for reasons of moderation).

Can you please tell how to fix this? Thanks.

**Comment by mmacehardyman** [comment]
Answer I got from Mike on Slack:

> field type isn't required
> it was used by code first models
> but this was  feature that wasn't used by 99% of people and need rewriting
> so it was removed
