### ISSUE TITLE
Add ability to get RAW protected media image URL for resized image

### ISSUE THREAD

**Issue by AdamHess** [mikeedwards83/Glass.Mapper#383]
Some images are rendered as background images for a div specified inline. 

this is accomplished by getting the image source. 

however, we want to tap into sitecore's resizing engine to optimize the images and need an easy way to get the raw protected URL. 

A lot of the work already exists by simply changing the ImageTagFormat in the GlassHtml glass  to render the URL and not the tag; however, it's rather clunky to force upcasting for IGlassHtml top GlassHtml and change the rendered template.

**Comment by mikeedwards83** [comment]
This will be in the next release. Thanks for the suggestion.

**Comment by mikeedwards83** [comment]
In release 5.5.27
