### ISSUE TITLE
Glass mapper return different type - GlassBaseProxy in Glass mapper 5.3

### ISSUE THREAD

**Issue by cv1998** [mikeedwards83/Glass.Mapper#389]
We use Glass mapper 5.3

TDS generate this code

public partial class AggregatorComponentItem : GlassBase, IAggregatorComponentItem
public partial class GNR_Press_ReleaseItem : GlassBase, IGNR_Press_ReleaseItem

we have this partial class

public partial class AggregatorComponentItem
{
  [SitecoreField(IAggregatorComponentItemConstants.FeaturedItemIdFieldName, Setting = SitecoreFieldSettings.InferType)]
  public virtual GlassBase FeaturedItem { get; set; }
}

i get this error
"Unable to cast object of type 'Castle.Proxies.GlassBaseProxy' to type 'TDS.Newsroom.Models.GNR_Press_ReleaseItem'" on this code

GNR_Press_ReleaseItem featuredPressRelease = (GNR_Press_ReleaseItem)Model.FeaturedItem;

why does FeaturedItem return type Castle.Proxies.GlassBaseProxy, not GlassBase ?

Thanks

**Comment by cv1998** [comment]
I figured this out. It's an inferred type issue. thanks

**Comment by mikeedwards83** [comment]
Cool! I will close.
