### ISSUE TITLE
Change the File field SRC to not internal set

### ISSUE THREAD

**Issue by richdman** [mikeedwards83/Glass.Mapper#392]
I want to override the File Src, unfortunately it is currently set to internal and not possible.
Please change it to a normal 'set' instead of 'internal set'.

namespace Glass.Mapper.Sc.Fields
{
  [Serializable]
  public class File
  {
    **public string Src { get; internal set; }**
    public Guid Id { get; set; }
  }

Thanks!

**Comment by mikeedwards83** [comment]
This will be fixed in the next release

**Comment by mikeedwards83** [comment]
Now in Release 5.6.129
