### ISSUE TITLE
Curly bracket cause attribute rendering issue

### ISSUE THREAD

**Issue by cusofx** [mikeedwards83/Glass.Mapper#393]
@Html.Glass().RenderLink(m => m.LoginLink, new {data_dl_action = "{token}"}, true)
In the link rendering if a attribute contains {}, glass will throw "**Input string was not in a correct format**" error.
Issue caused by 
![image](https://user-images.githubusercontent.com/42591340/66613019-afd2c080-ec0f-11e9-9ca7-f95822aa2472.png)

**Comment by mikeedwards83** [comment]
This will be fixed in the next release.

**Comment by mikeedwards83** [comment]
Now in Release 5.6.129
