### ISSUE TITLE
Html.Glass.Editable() not honoring content version selected in XP editor

### ISSUE THREAD

**Issue by jenluong-deepend** [mikeedwards83/Glass.Mapper#395]
Sitecore Version: 9.0.1 (Revision 171219)
GlassMapper Version: 4.5.0.4

When using `@Editable` in the XP editor, it always shows the latest version no matter what version is selected. 

I tested using the default `@Html.Sitecore().Field("fieldAlias")` and this shows the correct content for the version selected when in XP Editor. I can confirm this by selecting the version in the Page Editor.

Here are some screenshots to show the Page Editor content vs XP Editor content when switching between versions.

Version 1:
![version1-editor](https://user-images.githubusercontent.com/40009643/68561899-95ecfd80-049b-11ea-98cb-666b5b52ad6e.JPG)

Version 2:
![version2-editor](https://user-images.githubusercontent.com/40009643/68561900-95ecfd80-049b-11ea-8f75-720ca3a6a01f.JPG)

**Comment by mikeedwards83** [comment]
Hi, 

Does you model have a property that represents the item version?

For example:
```
[SitecoreInfo(SitecoreInfoType.Version)]
public virtual int Version { get; set; }
```

**Comment by jenluong-deepend** [comment]
The model did not have the Version property so I did try add it in, but even with that it's still not showing the correct version :(

**Comment by mikeedwards83** [comment]
Can you show me you whole model?

**Comment by jenluong-deepend** [comment]
Hi sorry for the very delayed reply!

[code.zip](https://github.com/mikeedwards83/Glass.Mapper/files/4014526/code.zip)

**Comment by jenluong-deepend** [comment]
Sorry to bump this! 
Our client is requesting an update and was hoping to find out if you were able to find anything. If there's anything else you need, please let me know 😃 Thanks!

**Comment by mikeedwards83** [comment]
Sorry, for not responding. I don't see anything specifically wrong with the model. If you output the value of "Version" to the page what do you see? Is it the correct version?

**Comment by mikeedwards83** [comment]
You should also add a language property to your model/

**Comment by jenluong-deepend** [comment]
Thank you! Adding `Language` to the base item model seems to have fixed (I think together with `Version` property as well).
