### ISSUE TITLE
Getting Sitecore.Kernel 11.0 version issue

### ISSUE THREAD

**Issue by ganeshkumarvkm** [mikeedwards83/Glass.Mapper#404]
I am getting the below error while trying to create IGlassContext or IMVCContext in unit test project. I am using Glass.Mapper.Sc.90.Mvc and the Sitecore.Kernel assembly is of SItecore 9.0.

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Sitecore.Kernel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by markgibbons25** [comment]
You'll need to include all required dependencies in your unit test project.

**Comment by mikeedwards83** [comment]
As @markgibbons25  said, you need to be sure you have all the correct dependencies.

**Comment by ganeshkumarvkm** [comment]
I added the Sitecore.Kerne.9.0.180604 nuget pack to unit test project already. It is throwing error for assembly version Sitecore.Kernel 11.0.0.0. But Sitecore.Kernel.9.0.180604 is with 11.1.x.x. version.
