### ISSUE TITLE
Some methods have optional parameters but the methods require the value to not be null

### ISSUE THREAD

**Issue by mwillebrands** [mikeedwards83/Glass.Mapper#405]
Hi Mike,

A few methods have a parameter for the GetKnownOptions which defaults to null, however the underlying method requires it to not be null:
` Assert.IsNotNull(options, "options must no be  null");`

The following class and methods are at fault:
**GlassController**
GetContext
GetDataSource
GetLayout

I'd rather have the parameter default to a `new GetKnownOptions()`, or remove the optional parameter and make it required. What's your take on this?
I'm aware that this class will be removed, however this will help people have less problems when doing a Glass upgrade from V4 to V5.

**Comment by mikeedwards83** [comment]
I thin defaulting to ```new GetKnownOptions``` makes a lot of sense

**Comment by mwillebrands** [comment]
Added a PR to implement this change.

**Comment by muso31** [comment]
Merged
