### ISSUE TITLE
SC93 Experience Editor <p></p> added to content on save 

### ISSUE THREAD

**Issue by edlane088** [mikeedwards83/Glass.Mapper#409]
Similar to this issue: https://sitecore.stackexchange.com/questions/25326/extra-p-tag-is-added-in-single-line-text-while-updating-from-experience-editor-i

When hitting save within experience editor after entering text into a single or multiline text field it adds <p></p> around the content. This previously worked with SC91 and having recently upgraded to SC93 we have now noticed this.

Any guidance on how to resolve this?

**Comment by mikeedwards83** [comment]
My suspicion is that this something SC9.3 is doing and not a Glass issue. When in a field is in edit mode, the field is passed through the render field pipeline. I suspect that either the problem lines in this pipeline or in the saving mechanism Sitecore uses.

**Comment by edlane088** [comment]
Thanks Mike appreciate the quick turn around, will have a comb throw the Sitecore RenderField pipeline and the Save pipeline to see if I can spot anything obvious. The only patch we currently have on either pipeline is to show the title of the field when blank so that won't be affecting it. If all else fails will contact Sitecore support.

**Comment by mikeedwards83** [comment]
A quick test would be just try the raw sitecore api and see if it gives you the same result.

@Sitecore().Field("something") 

I think ;-)

**Comment by edlane088** [comment]
Just wanted to say thanks for the steer, Sitecore provided a hotfix for it. Appreciate it.

**Comment by ethan-schofer** [comment]
@edlane088 I have installed the Hotfix and it has not solved this issue for me. Were you able to fix it with the hotfix?

**Comment by edlane088** [comment]
@ethan-schofer, to a certain extent yes it solved it, however it looks like there is another portion to this where if the single text is within a link then this issue rears its head again. Sitecore have logged a bug for it **409828** . However, their workaround was to change the Single Line Text to an html field and this resolves it for them. I have not tried this myself as I have not had time.
