### ISSUE TITLE
GlassHtml throws NullReferenceException after upgrading to Sitecore 8.2

### ISSUE THREAD

**Issue by imranhamid83** [mikeedwards83/Glass.Mapper#435]
Hi there,
I upgraded from SC 7.2 to 8.2 and use the following versions for Glass.Mapper
Glass.Mapper - 3.0.13.25 
Glass.Mapper.Sc - 3.2.2.45 
Castle.Core - 3.2.0.0
 Castle.Windsor - 3.2.0
 Glass.Mapper.Sc.CastleWindsor - 3.2.1.23

Following line in the code throws **System.NullReferenceException: Object reference not set to an instance of an object.** - Please note, it works fine in CS 7.2
 this.Model.ModuleSettings = GlassHtml.GetRenderingParameters<Base.Models.ModuleSettings>(this.Attributes["sc_parameters"]);

**ModuleSettings.cs**

    [SitecoreType(TemplateId = "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX}")]
    public class ModuleSettings
    {
        /// <summary>
        /// Gets or sets the mobile width
        /// </summary>
        [SitecoreField]
        public virtual WidthOption Span { get; set; }
    }

Not sure, what I am missing here. DO I need to upgrade the Mapper libraries? It's a multisite project heavily relies on Mapper and upgrading is the path I want to avoid if I can. Any help is much appreciated. 
![glass-error](https://user-images.githubusercontent.com/42209423/108278856-96cb0f80-7173-11eb-9ca3-b025c6a7cf17.png)

**Comment by mikeedwards83** [comment]
Is your model configuration being correctly pre-loaded when the application starts?

**Comment by imranhamid83** [comment]
Hi Mike,
Yes the model is pre-loaded as you can see in the image attached "Base.Models.ModuleContainerModel" to my first thread. 
It also loads ISitecoreContext context.
Also, the prior components which use sitecore context to get items work fine. It only throws null reference exception on Glass.Mapper.Sc.GlasshHtml. 

Wondering if the Sitecore 8.2 is not comptiable with current version Glass.Mapper.Sc? or I am missing configuration some where. I checked all the relavent files. Everything is same as the previous version 7. I used the migration tool to copy the sitecore data and files. Any help is much appreciated. Thanks in advance.

**Comment by imranhamid83** [comment]
Hi Mike,
I manage to fix the issue with GlassHtml. A reference to the binding was missing. Now I am seeing the following.

Now I get  Method not found: 'Boolean PageMode.get_IsPageEditorEditing()'. exception on the following line:

GlassHtml.GetRenderingParameters<Base.Models.ModuleSettings>(this.Attributes["sc_parameters"]);

Do I need to upgrade GlassMapper to version 4? or is there a way to override the property?

**Comment by muso31** [comment]
@imranhamid83 I'm closing this as it's not an issue with Glass. IsPageEditorEditing is obsolete
