### ISSUE TITLE
A/B Test with view rendering errors out with exception - Model item passed as rendering instead of model. 

### ISSUE THREAD

**Issue by Medi1480** [mikeedwards83/Glass.Mapper#437]
**Sitecore version** - 9.3.0  
**Glass mapper version** - 5.6.163 ( I updated version till 5.6.170 but error still exists) 
**Objective** - setting up a simple A/B test with view rendering by changing data source. 
**Error** -  Inner Exception: The model item passed into the dictionary is of type "Sitecore.Mvc.Presentation.RenderingModel", but the dictionary requires a model item of type <MODEL>

I also noticed that in the "Test the Component" window, the "Test Content Item" field starts changes to the rendering instead of the actual content item it was assigned earlier.

![image](https://user-images.githubusercontent.com/80091608/110168159-a1a8b580-7dab-11eb-9375-b63177429202.png)

If I remove the A/B test then it starts working just fine. 

Thanks

**Comment by LCZ86** [comment]
@Medi1480 I had the same problem, actually this is a sitecore bug please ask the support for SC Hotfix 460835-1
