### ISSUE TITLE
Issue with [SitecoreType] and generic classes

### ISSUE THREAD

**Issue by aquasonic** [mikeedwards83/Glass.Mapper#85]
Hi Mike,

let's assume I have the following model (based on the Sitecore sample items):

    [SitecoreType]
    public class ItemBase
    {
        [SitecoreId]
        public virtual Guid ItemId { get; set; }
    }

    public abstract class Generic<T> : ItemBase
    {
        public T Value { get; set; }

        [SitecoreField("Text")]
        public string Text { get; set; }
    }

    [SitecoreType(TemplateId = "{76036F5E-CBCE-46D1-AF0A-4143F9B557AA}")]
    public class Sample : Generic<string>
    {
        [SitecoreField("Title")]
        public string Title { get; set; }
    }

And I register the assembly for that in the `GlassMapperScCustom` class:

    public static IConfigurationLoader[] GlassLoaders(){			
        var model = new AttributeConfigurationLoader(HostingEnvironment.MapPath("/bin/Website.dll"));
        return new IConfigurationLoader[] { model };
    }

Then I got the following exception while loading the Glass context:

    Type Website.Models.Generic`1[T] is a generic type definition

Strack Trace:

    [ArgumentException: Type Website.Models.Generic`1[T] is a generic type definition]
       System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method) +5811550
       Glass.Mapper.Utilities.GetPropertyFunc(PropertyInfo property) +392
       Glass.Mapper.Configuration.AbstractPropertyConfiguration.set_PropertyInfo(PropertyInfo value) +75
       Glass.Mapper.Configuration.Attributes.AbstractPropertyAttribute.Configure(PropertyInfo propertyInfo, AbstractPropertyConfiguration config) +64
       Glass.Mapper.Configuration.Attributes.FieldAttribute.Configure(PropertyInfo propertyInfo, FieldConfiguration config) +109
       Glass.Mapper.Sc.Configuration.Attributes.SitecoreFieldAttribute.Configure(PropertyInfo propertyInfo, SitecoreFieldConfiguration config) +2083
       Glass.Mapper.Sc.Configuration.Attributes.SitecoreFieldAttribute.Configure(PropertyInfo propertyInfo) +121
       Glass.Mapper.Configuration.Attributes.AttributeTypeLoader.ProcessProperty(PropertyInfo property) +756
       Glass.Mapper.Configuration.Attributes.<LoadPropertiesFromType>d__2.MoveNext() +397
       Glass.Mapper.Configuration.Attributes.AttributeTypeLoader.LoadType(Type type) +641
       Glass.Mapper.Configuration.Attributes.AttributeTypeLoader.Load() +100
       Glass.Mapper.Configuration.Attributes.AttributeConfigurationLoader.LoadFromAssembly(Assembly assembly) +391
       Glass.Mapper.Configuration.Attributes.AttributeConfigurationLoader.<Load>b__0(String assemblyName) +94
       System.Linq.WhereSelectArrayIterator`2.MoveNext() +82
       System.Linq.Enumerable.Aggregate(IEnumerable`1 source, Func`3 func) +123
       Glass.Mapper.Configuration.Attributes.AttributeConfigurationLoader.Load() +273
       Glass.Mapper.Context.<Load>b__0(IConfigurationLoader loader) +76
       System.Linq.WhereSelectArrayIterator`2.MoveNext() +82
       System.Linq.Enumerable.Aggregate(IEnumerable`1 source, Func`3 func) +123
       Glass.Mapper.Context.Load(IConfigurationLoader[] loaders) +396
       Website.App_Start.GlassMapperSc.Start() in d:\Sitecore\Playgrounds\sc72rev140526\Website\App_Start\GlassMapperSc.cs:28

    [TargetInvocationException: Exception has been thrown by the target of an invocation.]
       System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
       System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +229
       System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
       System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
       WebActivatorEx.BaseActivationMethodAttribute.InvokeMethod() +341
       WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +879
       WebActivatorEx.ActivationManager.RunPostStartMethods() +40
       WebActivatorEx.StartMethodCallingModule.Init(HttpApplication context) +159
       System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +530
       System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
       System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
       System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

    [HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
       System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12617364
       System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
       System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12456981

When I remove the `[SitecoreType]` attribute on the `ItemBase` class it seems to work. The issue I found is, that in `SitecoreFieldAttribute.Configure()` the property `propertyInfo.DeclaringType` does not contain the generic type if the `[SitecoreType]` attribute is set. If I don't set the attribute, then the declaring type does correctly have `string` as the generic parameter.

**Comment by mikeedwards83** [comment]
I finally got round to investigating this issue. It turns out that it is actually a problem with the attribute on ItemBase.  GM sees that Generic<> inherits it and then tries to map the Generic type. I have added checks to skip Generic type definitions. 

https://github.com/mikeedwards83/Glass.Mapper/commit/1ad5da91d03ae5b3d76962e1c3090e571a9511ae

**Comment by mikeedwards83** [comment]
Released

**Comment by argha007** [comment]
How to deal with Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object

Getting this issue after upgrading to latest Glass Glass.Mapper.Sc 4.3.4.197

Strange when i revert to 4.0.1 its working.....
How to make this work with latest version???
