### ISSUE TITLE
Problem when mapping IEnumerables to Objects

### ISSUE THREAD

**Issue by acmetz** [mikeedwards83/Glass.Mapper#89]
Hi, 
I have been using Glass.Mapper for well over a year and all works fine. I recently upgraded DLL's and an issue has been intermittently appearing when loading the menus on my site. I waited a couple weeks and tried to upgrade to the latest version of DLL's, but I have had no luck, and the problem remains. It seems to happen the most after the first compilation and run of the site. It will cycle through all of the menus, throwing a similar error, and then it will work fine for a while.

###Place where my code fails:
 ( This line: var shouldShowPage = menu.Page != null && !menu.ShowMegaMenu;)
@foreach (var menu in Model)
                    {
                        var menuRight = menuCount++ < 5 ? string.Empty : "menu-box-r";
                        var shouldShowPage = menu.Page != null && !menu.ShowMegaMenu;
                        var tagInfo = shouldShowPage ? "href=\"" + menu.Page.Url + "\"" : "data-nav-component=\"active\" id=\"mobile-nav\"";

###Stack trace:
[NullReferenceException: Object reference not set to an instance of an object.]
   Glass.Mapper.AbstractService.RunConfigurationPipeline(AbstractTypeCreationContext abstractTypeCreationContext) +281
   Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) +86
   Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) +720
   Glass.Mapper.Sc.DataMappers.SitecoreFieldTypeMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +1039
   Glass.Mapper.Sc.DataMappers.<>c__DisplayClass3.<GetFieldValue>b__1(String x) +168
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +81
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +519
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +102
   Glass.Mapper.Sc.DataMappers.SitecoreFieldIEnumerableMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +753
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +153

[MapperException: Failed to map field SubMenus1 with value {02FB881E-55DF-4BC5-BB2D-8085DC0F10F4}|{97792B14-2FB2-4680-96CC-0442722047BC}]
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +389
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext) +352
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +99

[MapperException: Failed to map to property 'SubMenus1' on type 'IPC.IPCoop.Core.Data.MenuItem']
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +627
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +164
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +305

[MapperException: Failed to map property SubMenus1 on IPC.IPCoop.Core.Data.MenuItem]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +855

[MapperException: Failed to map properties on /sitecore/content/Home/Food and Beverage.]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +1206
   Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.<>c__DisplayClass6.<Execute>b__0(Object target) +174
   Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.LazyObjectInterceptor.Intercept(IInvocation invocation) +236
   Castle.DynamicProxy.AbstractInvocation.Proceed() +604
   Castle.Proxies.MenuItemProxy.get_Page() +157
   ASP._Page_Views_Shared__navBar_cshtml.Execute() in c:\development\ipcoop\IPC.IPCoop\IPC.IPCoop.Web\Views\Shared\_navBar.cshtml:16
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +126
   System.Web.WebPages.StartPage.ExecutePageHierarchy() +143
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +110
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +380
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +879

###Model I am trying to Map:
#region ~Properties~

        [SitecoreField]
        public virtual string MenuTitle { get; set; }

        [SitecoreField]
        public virtual Image Icon { get; set; }

        [SitecoreField]
        public virtual bool ShowMegaMenu { get; set; }

        [SitecoreField]
        public virtual Link Page { get; set; }

        #region SubMenu Information

        [SitecoreField]
        public virtual ItemCollection Links { get; set; }

        [SitecoreField]
        public virtual int MaxLinksToShow { get; set; }

        [SitecoreField]
        public virtual IEnumerable<Tag> Tags { get; set; }

        [SitecoreField]
        public virtual ItemCollection FeaturedLinks { get; set; }

        [SitecoreField]
        public virtual bool OrderLinksByLatest { get; set; }

        [SitecoreIgnore]
        protected virtual IWebHelper WebHelper
        {
            get { return _webHelper ?? (_webHelper = ServiceFactory.Create<IWebHelper>()); }
        }

        [SitecoreIgnore]
        protected virtual IWebSecurityService WebSecurityService
        {
            get { return _webSecurityService ?? (_webSecurityService = ServiceFactory.Create<IWebSecurityService>()); }
        }

        #endregion

        #region First Column Display Data

        [SitecoreField]
        public virtual IEnumerable<MenuItem> SubMenus1 { get; set; }

        [SitecoreField]
        public virtual bool ShowFeaturedArticle1 { get; set; }

        [SitecoreField]
        public virtual IEnumerable<Tag> Tags1 { get; set; }

        [SitecoreField]
        public virtual bool ShowLatestFeaturedArticle1 { get; set; }

        [SitecoreField]
        public virtual Link FeaturedArticle1 { get; set; }

        [SitecoreField]
        public virtual bool ShowLinksByLatest1 { get; set; }

        [SitecoreField]
        public virtual bool ShowNewsOnly1 { get; set; }

        [SitecoreField]
        public virtual bool ShowSubMenus1 { get; set; }

        [SitecoreField]
        public virtual int MaxLinksToShow1 { get; set; }

        #endregion

        #region Second Column Display Data

        [SitecoreField]
        public virtual IEnumerable<MenuItem> SubMenus2 { get; set; }

        [SitecoreField]
        public virtual bool ShowFeaturedArticle2 { get; set; }

        [SitecoreField]
        public virtual IEnumerable<Tag> Tags2 { get; set; }

        [SitecoreField]
        public virtual bool ShowLatestFeaturedArticle2 { get; set; }

        [SitecoreField]
        public virtual Link FeaturedArticle2 { get; set; }

        [SitecoreField]
        public virtual bool ShowLinksByLatest2 { get; set; }

        [SitecoreField]
        public virtual bool ShowNewsOnly2 { get; set; }

        [SitecoreField]
        public virtual bool ShowSubMenus2 { get; set; }

        [SitecoreField]
        public virtual int MaxLinksToShow2 { get; set; }

        #endregion

        #region Third Column Display Data

        [SitecoreField]
        public virtual IEnumerable<MenuItem> SubMenus3 { get; set; }

        [SitecoreField]
        public virtual bool ShowFeaturedArticle3 { get; set; }

        [SitecoreField]
        public virtual IEnumerable<Tag> Tags3 { get; set; }

        [SitecoreField]
        public virtual bool ShowLatestFeaturedArticle3 { get; set; }

        [SitecoreField]
        public virtual Link FeaturedArticle3 { get; set; }

        [SitecoreField]
        public virtual bool ShowLinksByLatest3 { get; set; }

        [SitecoreField]
        public virtual bool ShowNewsOnly3 { get; set; }

        [SitecoreField]
        public virtual bool ShowSubMenus3 { get; set; }

        [SitecoreField]
        public virtual int MaxLinksToShow3 { get; set; }

        #endregion

**Comment by mikeedwards83** [comment]
Sorry this thread went stale. Is this still and issue?

**Comment by acmetz** [comment]
No, your suggestions fixed all of the issues. Thanks.

**Comment by Nickunj** [comment]
I recently encounter similar problem in my mulitisite sitecore environment.

Site one works fine but in site I am having issues saying "Unable to cast object of type 'System.String' to type 'Glass.Mapper.Sc.Fields.Link'."

my code looks like 
items = context.QueryRelative<Link>(string.Format("./ancestor-or-self::*[@@templateid='{0}' or @@templateid = '{1}']/Data/Primary Navigation/*", IdpTemplates.SiteTemplateId, IdpTemplates.NetworkSiteTemplateId)).ToList();

Link model:
[SitecoreType(AutoMap = true)]
    public class Link
    {
        [SitecoreId]
        public virtual Guid Id { get; set; }

        public virtual string Title { get; set; }

        [SitecoreField("Link")]
        public virtual Glass.Mapper.Sc.Fields.Link Url { get; set; }
    }

Can please guide to resolve the issue?

**Comment by mikeedwards83** [comment]
Closing due to age, please re-open if this is still a problem.

**Comment by argha007** [comment]
Configuration Resolver pipeline did not return a type. Has the type been loaded by Glass.Mapper. Type: System.Object getting this issue after latetst glass update Glass.Mapper.Sc 4.3.4.197...

Pleaase help

**Comment by pberglund** [comment]
@argha007, i am as well, did you ever find a work around? I downgraded to Glass.Mapper.Sc 4.3.4.196 which is working in another project but not in my current one
