### ISSUE TITLE
Image size properties configured on the Sitecore fields are ignored

### ISSUE THREAD

**Issue by DavyCool84** [mikeedwards83/Glass.Mapper#92]
Sitecore allows to set a specific width and height when selecting an image in an image field. Glass uses it's own img tag rendering logic that ignores this completly.
 In page editing mode this works fine because Sitecore does the rendering of the image tag.

**Comment by BenGGolden** [comment]
I think the custom image rendering logic is a problem.  Shouldn't it always use the a FieldRenderer so that any processors defined there have the chance to modify the output.  It's a pretty core piece of Sitecore functionality that is being skipped over.

**Comment by mikeedwards83** [comment]
Hi, this is a bug. I will be putting out a hotfix today.

**Comment by mikeedwards83** [comment]
A fix for this has been pushed to the develop branch and will be available as part of the nightly builds tomorrow. 

The new solution matches closer to Sitecore's normal method of rendering image fields. This means a width and height attribute are always outputted.

**Comment by mikeedwards83** [comment]
I have also added a feature for controlling the output of the width and height attributes, (personally I am not a fan).

**Comment by rootix** [comment]
Hi Mike

While testing Issue 97, i saw that the images go wild in our solution because of this.

We call GlassHtml.RenderImage with the following parameters list:
- mw = 464
- data-responsive = image

The Resulting Image URL is (Original Size: 960x593):
image.jpg?la=de&vs=1&data-responsive=image&h=593&w=960&mw=464

Which results in a Image with a with of 464 but a height of 593 with black bars above and below the image because the aspect ratio is respected. This new behavior will break all our custom image sizes. 

Will we be able to remove the w and h parameter according to your last comment?

**Comment by mikeedwards83** [comment]
Pascal 

Could you try something like the following:

    html.RenderImage(model, x => x.Image, new { Width = 380, h = (string)null }, true, false);

Where you pass a null in the the W value.

I can explicitly remove the h because it gets passed from the Sitecore Image field and it is then up to your application to decided if it should or should not use those field values.

Mike

**Comment by mikeedwards83** [comment]
@rootix 

I have update the latest release to strip either W or H if one of the values as been explicitly set.

Mike

**Comment by rootix** [comment]
**Before:**
var parameters = new { mw = 464, data_responsive = true };
Result: image.jpg?la=de&amp;vs=1&amp;data-responsive=image&amp;h=593&amp;w=960&amp;mw=320

**After:**
var parameters = new { mw = 464, data_responsive = true, h = (string)null };
Result: image.jpg?la=de&vs=1&data-responsive=image&mw=320

For me this works. But i find it a bit confusing that setting h or w to null strips both sizes out. But i cannot tell you what the Sitecore behavior with this parameters is in detail, so i cannot say whether this is the best behavior.

In our case we can live with this. Thanks!

**Comment by mikeedwards83** [comment]
Released

**Comment by aquasonic** [comment]
Hi Mike,

the solution you proposed for Pascal doesn't seem to work in the Page Editor. With the above example (`h=null`) the ourput for the image-tag is as follow:

    <img src="Image.jpg?h=593&la=de&vs=1&w=960&mw=480" width="960" height="593" h&mw="464" >

Please notice the newly added attribute `h&mw` and the invalid `mw` parameter on the image source ;-) When I don't set `h=null` then the attributes are ok, but the dimensions are wrong again.

Is there also a way in the Page Editor to remove width/height parameters and have the same image source as without editing?

Regards,
Kevin

**Comment by pveller** [comment]
Just wanted to share what we're doing for image sizes that you want to control with CSS (e.g. responsive image) in SCORE. With out of the box Sitecore API it looks like this:

```csharp
@Html.Sitecore().Field("Image One", new { HideSize = true } )
```

by the way, does `Editable` supports passing *rendering* parameters to the `renderField` ? Anyway. The implementation of stripping out the `width` and `height` is fairly straightforward. The processor:

```csharp
args.Result.FirstPart = StripParam(args.Result.FirstPart);
// ...
public virtual string StripSize(string ml)
{
    return ml.StripHtmlAttribute("(width|height)");
}
```

And the `StripHtmlAttribute` extension method does a regex replace. I am glad to contribute this to Glass if @mikeedwards83 thinks it'll fit. We do a lot of parameter-based *intrusions* into how Sitecore renders fields for Page Editor and `HideSize` for images is one example.
