### ISSUE TITLE
Sitecore 7.5 Media request protection not supported by GlassHtml.RenderImage

### ISSUE THREAD

**Issue by joosthollander** [mikeedwards83/Glass.Mapper#93]
In Sitecore 7.5 media request protection is added. Mediaurls (width w / h parameters) needs to be signed with a hash query string paramater. Since GlassHtml.RenderImage does not go through the renderfield pipeline the urls will not be signed automatically. Further explanation in the 7.5 release notes:
http://sdn.sitecore.net/Products/Sitecore%20V5/Sitecore%20CMS%207/ReleaseNotes/ChangeLog.aspx

Quote:
If you have code in your solution that manually appends image scaling parameters to image URLs without passing the parameters to the <sc:image> control, you must rewrite the code to append a hash value using one of the helper methods or rewrite it to use the <sc:image> control. In XSLT renderings, you can use sc:SignMediaUrl(url) or sc:GetSignedMediaUrl(…). In C# code, you can use HashingUtils.ProtectAssetUrl(url) which appends a hash value to the provided URL, or you can use GetAssetUrlHash(url) to only return the hash value for the provided URL.

**Comment by jacksodj** [comment]
any update on this?

**Comment by mikeedwards83** [comment]
Hi 

This is now supported in V4 so I will close.

Mike

**Comment by ashugoyal220** [comment]
Hi MIke,

I am using upgraded version of Glass mapper 4.0.11.63, Still I am getting the same error "MediaRequestProtection: An invalid/missing hash value was encountered. The expected hash value:"

Is it fixed in any specific version?
