### ISSUE TITLE
Caching issues when not in editing mode

### ISSUE THREAD

**Issue by kevinbrechbuehl** [mikeedwards83/Glass.Mapper#95]
Hi Mike,

I got an issue with the newly added performance improvements (see [this commit](https://github.com/mikeedwards83/Glass.Mapper/commit/1039e5025df441c7922392d39926d5ae1286de0d) in `GlassHtml.GetCompiled()`) when having an `@Editable()` within a foreach-loop. Let's say we have a main navigation and iterate over them:

```
@foreach (var item in Model.MainNavigation)
{
    @Editable(m => item.Title)
}
```

Then the cache key in the `GetCompiled()` method is always the same and therefor the output is always the same (every item has the same title). I could get rid of them when iterating with a for-loop:

```
@for(var i=0; i < Model.MainNavigation.Count(); i++)
{
    @Editable(m => item[i].Title)
}
```

But this isn't very nice. Additionally we are working with display templates, where this approeach is not possible, as we have the `@Editable()` within the display template and therefor the cache key is the same again for every item.

Could you please take a look into this? Is there a way to disable the cache temporarly?

Thanks and best regards,
Kevin

**Comment by sarcjack** [comment]
I've also noticed that even without a loop when you use code like this:

@Editable(x => Model.GlassItem.TitleLink)

And the rendering is used multiple times on the page. It will only show the first TitleLink that gets into cache although with cache disabled in page editor it works correctly. This code fixes it:

 @Editable(Model.GlassItem.TitleLink, x => x)

Maybe that's just best practice, but it's easy to not follow it with the extra options.

**Comment by mikeedwards83** [comment]
Sarjack

Glass caches the lambdas to make  rendering quicker. In the examples above should rewrite the first to:
    
    @Editable(x=> x.GlassItem.TitleLink) 

When  writing it like this the Model is inferred from the rendering context.

The second should be written like so:

    @Editable(Model, x=> x.GlassItem.TitleLink)

Here the model is taken from the first  parameter passed in which is useful for links.

Using it this way follows the standard MVC convection, for example EditorFor:

@Html.EditorFor(x=> x.GlassItem.TItleLink)

**Comment by sarcjack** [comment]
Thanks that clears things up.

**Comment by smyadam** [comment]
Hello Mike,

    We are also facing the same problem, where if we don't pass the model, the value is cached. 

    The problem with us is we have to update 600 line of code in order to pass the model and the lambda expression. It would be extremely difficult to change and test all these updates.

   Can you please add the feature to disable cache and provide us the code how to do this, so that we can update glass.mapper to the latest version.

Thanks,
Shashi.
