### ISSUE TITLE
GlassMapper with CA Wily and Sitecore 7.2 Update 2 MVC causes "Invalid program detected"

### ISSUE THREAD

**Issue by corywdixon** [mikeedwards83/Glass.Mapper#96]
With CA Wily monitoring agents running, we get the following stacktrace whenever Glass is invoked to populate the models. This issue does not occur when CA Wily agents are disabled. Have an open case with CA on the issue - posting here to see if any other reports or similar behavior has been observed. Renderings that do not cause Glass to inject work properly. My thought is that this is a conflict between reflection/il generation and CA's monitors during construction.

[InvalidProgramException: Common Language Runtime detected an invalid program.]
   System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method) +0
   System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target) +41
   System.Linq.Expressions.Expression`1.Compile() +189
   Glass.Mapper.Utilities.GetPropertyFunc(PropertyInfo property) +579
   Glass.Mapper.Configuration.AbstractPropertyConfiguration.set_PropertyInfo(PropertyInfo value) +75
   Glass.Mapper.Sc.DataMappers.SitecoreFieldIEnumerableMapper.Setup(DataMapperResolverArgs args) +594
   Glass.Mapper.Pipelines.DataMapperResolver.Tasks.DataMapperStandardResolverTask.Execute(DataMapperResolverArgs args) +686
   Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args) +616
   Glass.Mapper.Context.ProcessProperties(IEnumerable`1 properties) +511
   Glass.Mapper.Context.Load(IConfigurationLoader[] loaders) +1479
   Glass.Mapper.Sc.Pipelines.Response.GetModel.GetObject(String model, Database db, Rendering renderingItem) +879
   Glass.Mapper.Sc.Pipelines.Response.GetModel.GetObject(String model, Database db, Rendering renderingItem) +233
   Glass.Mapper.Sc.Pipelines.Response.GetModel.Process(GetModelArgs args) +225
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args, Func`2 resultGetter) +197
   Sitecore.Mvc.Presentation.Rendering.GetModel() +337
   Sitecore.Mvc.Presentation.Rendering.get_Model() +27
   Sitecore.Mvc.Presentation.ViewRenderer.get_Model() +167
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +154
 
[InvalidOperationException: Error while rendering view: '/Views/Content/RectangularPodItem.cshtml'.
]
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +777
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) +27
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) +62
   (Object , Object[] ) +83
  Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Pipelines.Response.RenderPlaceholder.PerformRendering.Render(String placeholderName, TextWriter writer, RenderPlaceholderArgs args) +203
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Helpers.SitecoreHelper.Placeholder(String placeholderName) +311
   ASP._Page_Views_Containers_RectangularPod_cshtml.Execute() in d:\inetpub\wwwroot\sitecorecms\Website\Views\Containers\RectangularPod.cshtml:6
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +125
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +125
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +139
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +217
 
[InvalidOperationException: Error while rendering view: '/Views/Containers/RectangularPod.cshtml' (model: 'Sitecore.Mvc.Presentation.RenderingModel, Sitecore.Mvc').
]
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +777
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) +27
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) +62
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Pipelines.Response.RenderPlaceholder.PerformRendering.Render(String placeholderName, TextWriter writer, RenderPlaceholderArgs args) +203
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Helpers.SitecoreHelper.Placeholder(String placeholderName) +311
   ASP._Page_Views_PageFrames_PublicPageFrame_cshtml.Execute() in d:\inetpub\wwwroot\sitecorecms\Website\Views\PageFrames\PublicPageFrame.cshtml:21
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +125
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +125
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +139
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +217
 
[InvalidOperationException: Error while rendering view: '/Views/PageFrames/PublicPageFrame.cshtml' (model: 'Duke.Common.Model.Glass.PageBase, Duke.Common.Model').
]
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +777
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) +27
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) +62
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Pipelines.Response.RenderPlaceholder.PerformRendering.Render(String placeholderName, TextWriter writer, RenderPlaceholderArgs args) +203
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Helpers.SitecoreHelper.Placeholder(String placeholderName) +311
   ASP._Page_Views_Shared_Layout_cshtml.Execute() +693
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +125
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +125
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +139
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +217
 
[InvalidOperationException: Error while rendering view: '/Views/Shared/Layout.cshtml' (model: 'Sitecore.Mvc.Presentation.RenderingModel, Sitecore.Mvc').
]
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +777
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args) +27
   Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Process(RenderRenderingArgs args) +62
   (Object , Object[] ) +83
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +291
   Sitecore.Mvc.Pipelines.PipelineService.RunPipeline(String pipelineName, TArgs args) +186
   Sitecore.Mvc.Presentation.RenderingView.Render(ViewContext viewContext, TextWriter writer) +297
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +380
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +109
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +890
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +97
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +709

**Comment by mikeedwards83** [comment]
Closing this as it has now been resolved. Fix unknown, possibly an update to CA Wily sorted the issue but no Glass changes were required.
