### ISSUE TITLE
Link Resolving Issue

### ISSUE THREAD

**Issue by rootix** [mikeedwards83/Glass.Mapper#97]
I found an issue on generating links with the SiteResolver flag enabled. With this property in the UrlOptions, i can link to an item which is placed below another site tree. If the other site has the same hostname (only virtualFolder differs), the resolved Link will be relative (e.g. /en/othersite/otheritem). If the other Site is configured under another hostname, the resolved Link will be absolute with protocol and domain.

Debugging showed me, that when i use the SitecoreUrl attribute with "UrlOptions =  SitecoreInfoUrlOptions.SiteResolving" (a SitecoreField for mapping a Link type has the same issue), the UrlOptions object generated by "Utilities.CreateUrlOptions(SitecoreInfoUrlOptions)" sets the defaultUrlOptions.AlwaysIncludeServerUrl to true as well. Even if the Flag isn't present on the Attribute and the default value in the LinkManager configuration is set to false. It looks to me that the Bit Flags you use in the SitecoreInfoUrlOptions has a problem, since comparing the AlwaysIncludeServerUrl Flag (2) returns true when the provided Flags have the value of SiteResolving (1298).

Because of this behavior, even links which are within the same site as the context site gets generated with an fully qualified url instead of a relative link, which would be normal Sitecore behavior.

**Steps to reproduce:**

Add the following property to your context item domain model:

```
[SitecoreUrl(UrlOptions = SitecoreInfoUrlOptions.SiteResolving)]
public virtual string Url { get; set; }
```
The resulting value of the mapped property will be a fully qualified link and the UrlOptions.AlwaysIncludeServerUrl will be true, even if it is false in the configuration.

**Expected behavior:**

Those two UrlOptions properties should work for themselves and should not be set by a single Attribute flag.

**Comment by mikeedwards83** [comment]
Hi

This should be resolved in the latest nightly build. Please download and let me know how you get on.

Mike

**Comment by rootix** [comment]
Hi Mike

Sorry for the delay. I installed the newest Nightly Build and it worked as i would expect it. Thanks!

Do you have any ETA for this fix in the normal release?

Regards,
Pascal

**Comment by mikeedwards83** [comment]
Pascal

Sorry for my slow reply. It will be soon, I have another couple of bugs that I would like to get ready before we release.

Cheers

Mike

**Comment by mikeedwards83** [comment]
Released
